### PR TITLE
1502: Mark All Read Removal

### LINKED ISSUE #1502: Mark All Read Removal
Given that we've added the mark all read button in most of the channels, I suggest we remove the older control: 

Old Mark All Read

And we replace it with our icons: 

Channel Icons

In cases where filtering and archive are not relevant, we don't include them. 

Let me know your thoughts.

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1502

### CODE REVIEW

**Comment by lebaphi** [comment]
https://user-images.githubusercontent.com/26705621/164407029-7c8f3f3f-3139-454f-9062-308673b4724e.mp4

**Review by IanMayo — APPROVED** [review]

**Comment by ShendMikullovci** [comment]
Love the disappearing button once its been clicked on. Great work @lebaphi !

**Comment by ShendMikullovci** [comment]
Small problems though. It seems it wasn't merged in the game:

https://user-images.githubusercontent.com/85491794/164535946-f93b5492-2c8a-47e6-a306-c474135eec6d.mp4

The chat message was sent twice. Furthermore, there are some issues with the chat envelope not being opened/closed correctly upon clicking, as you can see above.

**Comment by IanMayo** [comment]
Good morning @ShendMikullovci - Heroku had a security issue, and isn't accepting automatic deployments from GitHub right now. So, I'm afraid `serge-review` isn't being updated.  If it's not fixed in a couple of days we'll have to find another solution.

Sadly, the video walkthroughs are all you have right now.

**Comment by ShendMikullovci** [comment]
> Sadly, the video walkthroughs are all you have right now.

In that case, it looks great!

**Pull request merged**
