### PR TITLE
remove spaces countries list

### LINKED ISSUE #1076: Reduce wasted space in Countries List
In the COA form, there is some wasted space around the Countries list - particularly when the form is disabled.

image

Could we introduce some CSS to remove the wasted components/white space for arrays when the component is disabled?

Steps to reproduce:
* play as Blue > Blue Senior
* switch to Blue COA tab
* create new COA message, including one or more countries.
* `Submit` the message
* expand the message - read-only view of countries should be shown.

### PR DESCRIPTION
**Pull request by sanjayradadiya**
## 🧰 Issue

fixes #1076 
image

## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks - are we able to drop the rectangles?

**Comment by sanjayradadiya** [comment]
> Thanks - are we able to drop the rectangles?

image
image

**Comment by IanMayo** [comment]
Could we experiment with dropping the array numbering labels?  `Europe 1`, `Europe 2`, ...

_Ideally_ via those `json-editor` properties, but otherwise via CSS.

**Comment by sanjayradadiya** [comment]
> Could we experiment with dropping the array numbering labels? `Europe 1`, `Europe 2`, ...
> 
> _Ideally_ via those `json-editor` properties, but otherwise via CSS.

image
image

**Review by IanMayo — APPROVED** [review]
Works fine, good solution.

**Pull request merged**
