### PR TITLE
1261: Make option clickable

### LINKED ISSUE #1261: Make Options Appear Clickable
The force name, icon change tabs, and the color chart should be rendered to appear more clickable:
Make appear clickable admin page
 
This could be done simply by underlining the force name and the "Change Icon". As for the color chart, its outline could be dimmed.

### PR DESCRIPTION
**Pull request by lebaphi**
Fixed #1261

### CODE REVIEW

**Comment by IanMayo** [comment]
@lebaphi said:

Hi @IanMayo and @ShendMikullovci ,
I've update the UI:
- The text editing, I add the border bottom to make it like editing field
- Color picking, I don't think add the underline is a good UI, so I think we set the cursor to point is good enough.
- Change icon, I added the underline and change cursor to pointer.
How do you think, guys?

image

**Comment by IanMayo** [comment]
For this `White` force (above) it isn't obvious that there is the clickable color block there.  A dark solid border would show the user there's something there.

Hmm, @ShendMikullovci - should we put a `Color` label to the left of the color block?

**Comment by ShendMikullovci** [comment]
That sounds good! However, the deployment link is sending me to the game, not the admin page, so I can't really see what it looks like!

**Comment by ShendMikullovci** [comment]
I definitely like keeping the point cursor for all of the options, as well as add a darker border for the team color icon.

**Comment by IanMayo** [comment]
> That sounds good! However, the deployment link is sending me to the game, not the admin page, so I can't really see what it looks like!

From the game page you click on the `Admin` icon at the upper-right:
image

**Comment by IanMayo** [comment]
>  as well as add a darker border for the team color icon.

@lebaphi - could you add a darker border around the force color icon?

**Comment by lebaphi** [comment]
> > as well as add a darker border for the team color icon.
> 
> @lebaphi - could you add a darker border around the force color icon?

sure @IanMayo 👍

**Comment by IanMayo** [comment]
Hello @lebaphi - if you set that darker border color, we can get this PR merged :-)

**Comment by lebaphi** [comment]
Hi @IanMayo @ShendMikullovci , which one do you think better:

border 1px:
image

border 2px
image

I pushed the change with 1px border. but if you guys think it should be bolder, I will update 😄

**Comment by ShendMikullovci** [comment]
Both look great to me. If you've pushed 1px then let's stick to it. 
Thanks guys!

**Pull request merged**
