### PR TITLE
1378: Fix minors issues

### LINKED ISSUE #1378: New Platform UX issues
Multiple things here: 

https://user-images.githubusercontent.com/85491794/156880045-6baf8503-d52c-45c0-953a-0484e1da9611.mp4

1. The issue with adding elements (#1372) persists with New Platforms as well.

2. When I create a New Platform, it pops up at the bottom of the screen. Could we have it pop up at the top? In a wargame with plenty of platforms, it adds another step of scrolling down to find the newly created platform for the user that is unnecessary. 

3. If I accidentally hit Delete on the New Platform, the element display page behaves like I confirmed the deletion. Once I hit cancel, the elements don't reappear, and I'm forced to click on New Platform again to view the elements. These are all extra steps that prolong the game creation process. If we could have the screen stay still behind the "Are you sure?" pop-up and only disappear once the deletion is confirmed, that'd be great.

### PR DESCRIPTION
**Pull request by lebaphi**
Fix #1378

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks @lebaphi - could we have some screenshots or screen-recordings of the changes please?

**Comment by lebaphi** [comment]
Yep, here it is @IanMayo 😄 
https://user-images.githubusercontent.com/26705621/157474619-ddb3ff74-8620-4046-93a7-a2bdd9405231.mov

**Comment by IanMayo** [comment]
Could you play with this Pull Request please @ShendMikullovci ?  (`View deployment` above)

**Comment by ShendMikullovci** [comment]
> Could you play with this Pull Request please @ShendMikullovci ? (`View deployment` above)

Sure. The deployment is taking me to the game though, not the admin page.

**Comment by ShendMikullovci** [comment]
> Yep, here it is @IanMayo smile https://user-images.githubusercontent.com/26705621/157474619-ddb3ff74-8620-4046-93a7-a2bdd9405231.mov

The link won't open for some reason :(

**Comment by IanMayo** [comment]
> > Could you play with this Pull Request please @ShendMikullovci ? (`View deployment` above)
> 
> Sure. The deployment is taking me to the game though, not the admin page.

From the game welcome page, you go into admin using one of the buttons at the top right.

**Comment by ShendMikullovci** [comment]
> > > Could you play with this Pull Request please @ShendMikullovci ? (`View deployment` above)
> > 
> > 
> > Sure. The deployment is taking me to the game though, not the admin page.
> 
> From the game welcome page, you go into admin using one of the buttons at the top right.

Deployment Error

I don't think we're talking about the same screen? Is the link good?

**Comment by IanMayo** [comment]
Aah @ShendMikullovci - the links are on the previous page:
image

**Comment by ShendMikullovci** [comment]
I never get that page when I click on the deployment link. Can you just copy paste the link here maybe?

**Comment by IanMayo** [comment]
> I never get that page when I click on the deployment link. Can you just copy paste the link here maybe?

When I click on `View deployment` (above) it takes me to that page.

**Comment by ShendMikullovci** [comment]
> > I never get that page when I click on the deployment link. Can you just copy paste the link here maybe?
> 
> When I click on `View deployment` (above) it takes me to that page.

As you can see, it turns into the game page before I can click on the icons for some reason: 

https://user-images.githubusercontent.com/85491794/157695573-6189c5db-cfc6-4dee-9101-703855672cd0.mp4

**Comment by IanMayo** [comment]
Hmm, I see the button(s) at 0:16 in the video. Could it have got pushed up the page when the Serge icon loaded?

**Comment by ShendMikullovci** [comment]
> Hmm, I see the button(s) at 0:16 in the video. Could it have got pushed up the page when the Serge icon loaded?

I can't go higher on the page. Seems like the button disappeared under the chrome taskbar and can't be accessed. @lebaphi 's MP4 link won't open either IDK why. Could you guys provide screenshots? Or try to directly upload the video? Usually the github video players work great.

**Comment by IanMayo** [comment]
In that case I think you need to reduce the zoom on the browser page (or zoom out).

**Comment by ShendMikullovci** [comment]
Sorry for all the hassle guys. Everything looks perfect. Great job @lebaphi !

**Review by ShendMikullovci — APPROVED** [review]

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
