### PR TITLE
Introduce "Mark message as unread"

### LINKED ISSUE #903: Introduce `Mark message as unread`
While some players skim through all new messages, they may wish to highlight some that still require some action from them.

They could do this if we offered `mark message as unread` support.  This would clear the `read` cookie for that message.

A Natural UI element for this would be the dark-blue `Read` indicator.  Clicking on it would collapse the message, and clear the read flag:

image

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #903

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks for this @lebaphi 

You are aware that the vertical line should be semi-transparent for read messages.  @ShendMikullovci  also requested that the unread messages have a lighter background, as in the screenshot here:
https://github.com/serge-web/serge/issues/903#issuecomment-873046940

Any other feedback @ShendMikullovci ?  Here's a link into a game:
https://serge-903-mark-message--omqycc.herokuapp.com/?wargame=wargame-kqgy546g&access=pkoiqu5ev

**Comment by IanMayo** [comment]
One last bit. please @lebaphi :
>  @ShendMikullovci  also requested that the unread messages have a lighter background, as in the screenshot here:
https://github.com/serge-web/serge/issues/903#issuecomment-873046940

**Comment by lebaphi** [comment]
> One last bit. please @lebaphi :
> 
> > @ShendMikullovci  also requested that the unread messages have a lighter background, as in the screenshot here:
> > [#903 (comment)](https://github.com/serge-web/serge/issues/903#issuecomment-873046940)

ah okay, will update now

**Comment by lebaphi** [comment]
done @IanMayo 👍

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
