### PR TITLE
complex wargame

### LINKED ISSUE #988: As a stakeholder I wish to review a complex wargame
The players are planning a complex wargame that will run for several months.

The wargame includes many forces and players.

We should create a mock version of the wargame to help the players verify that Serge is meeting their requirement.

I have documented the forces/roles/channel membership here: https://docs.google.com/spreadsheets/d/1WHCPC6rdqwVNYPQxUIoGfTWaBx0xEl-SjN05JrD6Dno/edit?usp=sharing

The wargame should also have these characteristics:
* name: `Papa Foxtrot`
* turn presentation: `Turn-pair-letters` (this is a new format: `0.a, 0.b, 1.a, 1.b`
* turn size: `Two months` (once we allow this in UI. For now we'll use a period of 60 days).

(please feel free to comment with questions)

### PR DESCRIPTION
**Pull request by sanjayradadiya**
## 🧰 Issue

Fixes #988 

## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks @sanjayradadiya - nice start

I see other forces need to be added to the `Blue RFI` and `Red RFI` channels.  Note: `Red` are also present in `Blue RFI`.

Also note: when all members of a force are present in a channel, it is better to leave the `Roles` column blank - this will ensure that any other new roles in that force are present in the channel.

**Comment by IanMayo** [comment]
Aah, I see we still have some unnecessary restrictions:
image

For the second Blue role, we can just leave the `role` blank - which will include all rows (including any future blue ones).

Could you switch to this way of specifying it please?

**Comment by IanMayo** [comment]
Oops, unclear requirements from me:
image

Those with `create` ability will only be able to create `RFIs` OR `COAs` - depending on the type of channel it is. So, in the `BLUE RFI` channel, `Blue` will be able to create an `RFI` - but not a COA, etc, etc.

Definition of `create` improved:
image

**Comment by IanMayo** [comment]
All of red need to be able to submit (create) a COA:
image

**Comment by IanMayo** [comment]
`Rainbox` force should be `Rainbow` - sorry, my mistake.

**Comment by IanMayo** [comment]
Rainbow messages are: chat, SME comment, and Request Infrastructure.  Not `PFT RFI`.
image

Above example from `Blue & SME`.

**Comment by sanjayradadiya** [comment]
> Aah, I see we still have some unnecessary restrictions:
> image
> 
> For the second Blue role, we can just leave the `role` blank - which will include all rows (including any future blue ones).
> 
> Could you switch to this way of specifying it please?

Yes, All Roles applied for Blue role.

**Comment by sanjayradadiya** [comment]
> Rainbow messages are: chat, SME comment, and Request Infrastructure. Not `PFT RFI`.
> image
> 
> Above example from `Blue & SME`.

PFT RFI template changed to SME Comment.

**Comment by sanjayradadiya** [comment]
> `Rainbox` force should be `Rainbow` - sorry, my mistake.

Rainbox force name changed to Rainbow.

**Comment by IanMayo** [comment]
Oops, spotted another one :-)

image

Only Red should be able to create messages in `Red RFI`.  The other participants should have templates `empty` please.  We're using the presence of a custom template as the marker for `create` permission.

**Comment by IanMayo** [comment]
Oh dear, please don't be cross with me @sanjayradadiya 

The `RFI` templates actually need to be `PFT RFI`.  Sorry.

image

**Review by IanMayo — APPROVED** [review]
Nice work, thanks.

**Pull request merged**
