### PR TITLE
2799_Core_Mapping_Health_Indicator

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Comment by lilitkarapetyan** [comment]
fixes #2799

**Comment by IanMayo** [comment]
Thanks @lilitkarapetyan - any chance of a screenshot of the new marker?

(I'm too impatient to wait for the deployment 🤣 )

**Comment by lilitkarapetyan** [comment]
> Thanks @lilitkarapetyan - any chance of a screenshot of the new marker?
> 
> (I'm too impatient to wait for the deployment 🤣 )

screenshot

**Comment by IanMayo** [comment]
Nice start. Are you able to make these changes please?
- could the line move outside the symbol, so it's beneath it?
- the line appears to have rounded ends.  Could they be square, so it's a proper rectangle?

**Comment by Tristina1788** [comment]
@IanMayo  Do you think the all items on map should show Health Indicator? Some items are missing Health Indicator from map although from Items panel still has Health Indicator .

image

**Comment by lilitkarapetyan** [comment]
> Nice start. Are you able to make these changes please?
> 
>     * could the line move outside the symbol, so it's beneath it?
> 
>     * the line appears to have rounded ends.  Could they be square, so it's a proper rectangle?



> Nice start. Are you able to make these changes please?
> 
>     * could the line move outside the symbol, so it's beneath it?
> 
>     * the line appears to have rounded ends.  Could they be square, so it's a proper rectangle?

Hello @IanMayo , yes I will make those changes

**Comment by IanMayo** [comment]
> @IanMayo Do you think the all items on map should show Health Indicator? Some items are missing Health Indicator from map although from Items panel still has Health Indicator .

Hello @Tristina1788 - no the plain shapes do not require a health indicator.

**Comment by Tristina1788** [comment]
> > @IanMayo Do you think the all items on map should show Health Indicator? Some items are missing Health Indicator from map although from Items panel still has Health Indicator .
> 
> Hello @Tristina1788 - no the plain shapes do not require a health indicator.

But the items for plain shapes still show health indicator in left panel.  We should not draw health indicator for them?

image

**Comment by IanMayo** [comment]
Thanks @Tristina1788 

There could be a couple of underlying issues:
1. The underlying data may be inconsistent (shapes having health properties, when they shouldn't)
2. We should not be trying to show a military symbol for a shape - that's why it's an upside down question mark.

I'll investigate.

Update: to be fixed in #2827

**Comment by IanMayo** [comment]
Thanks @lilitkarapetyan - are you able to resolve the conflicts please?

**Comment by lilitkarapetyan** [comment]
> Thanks @lilitkarapetyan - are you able to resolve the conflicts please?

Yes I will solve it

**Comment by lilitkarapetyan** [comment]
Hello @IanMayo, Upon clicking 'Show symbol labels,' the dashed line directing towards 'health' relocates to the center of the name (svg). it is true? - https://gyazo.com/e1e5f7b9ff555206c5b889a2e96e27f4

**Comment by Tristina1788** [comment]
Checking on branch `2799_Core_Mapping_Health_Indicator` , now the health indicator is not show for shape. 

image


But I can't create the item with shape (Draw Polyline, Draw Polygons, Draw Circle, Text). @lilitkarapetyan Could you check again

image

More details on video  :

https://github.com/serge-web/serge/assets/107697044/976bc386-4054-4727-ac5d-9f83cadb1d1f

**Comment by Tristina1788** [comment]
> Checking on branch `2799_Core_Mapping_Health_Indicator` , now the health indicator is not show for shape.
> 
> image
> 
> But I can't create the item with shape (Draw Polyline, Draw Polygons, Draw Circle, Text). @lilitkarapetyan Could you check again
> 
> image
> 
> More details on video :
> 
>  cannot-draw-items.mp4

@IanMayo  I've checked again on branch 'develop' and the issue is also happened. So I think the issue from merge develop to this branch.

**Review by IanMayo — APPROVED** [review]
Merging, since this resolves original requirement.

This branch is `broken` because of bug in `develop`, but we'll solve that separately.

**Pull request merged**
