### PR TITLE
[SERGE-604] Implement RFI Status Board

### PR DESCRIPTION
**Pull request by zukilover**
## 🧰 Issue
Closes #630 

## 🚀 Overview: 
Updates data-table and rfi-form components, and implement in channel factory

## 🤔 Reason: 
It includes the provision of a dedicated UI panel for RFIs, only visible to members of Umpire force

## 🔨Work carried out:

- [x] Tests pass
- [x] Update `data-table` component
- [x] Update `rfi-form` component
- [x] Implement updates to channel factory

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have assigned myself to this PR.
- [x] I have chosen an appropriate label for the PR.
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.
- [x] I confirm that I have checked for required README updates and acted accordingly.

****

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks for this @Heri, it's good.

I have just played with it - to ensure only the most recent version of a message is displayed. You'll see the change in `data-table` \ `index.stores.tsx`.  I've also tried to populate the filters from the message content. I've got that working in the story, but really we need that in the core Serge code.

Oh bugger - I've just found your code that does exactly that!  And it does it better than my code does 😆 

Aah, now I understand it better.  You've integrated it into the factory - that's exactly the right thing to do :-)

Ok, I have more playing/learning to do.

But, can I record a couple of bugs?
- ~~we aren't showing the private message or response in the `RFI-Form` for some messages, but we can see the content in the mock data~~ Done. Once we're updating RFIs we should see the other fields populated.
- the filters don't seem to work. If I select one, the table goes empty
- could the RFI Form be the minimum size necessary to show the text areas please ?

Aah, one last comment.  Lilit is working on the RFI editor that sits in a specific RFI channel.  For this phase we're just going to allow them to be managed from inside the channel (Red RFI / Blue RFI, etc).  The RFI Status Board will be read-only.  Could you please comment out the code to show the buttons, or to respond to the buttons please?  We can reinstate it later.

**Comment by IanMayo** [comment]
Tomorrow I'll work on adding some real RFIs to a wargame database, so we have some real data to plot.

**Comment by IanMayo** [comment]
Hello @zukilover -  I've added/improved the mock data.

There are now some new RFI messages, and an `rfis` channel:
image

In getting to the above, I've seen how much effort you've put into sending/managing RFIs.  Sorry about that - I though you had just handled the rendering when I asked Lilit to step in.  

Sorry about the mistake in the communication there.

Fixes to the filtering/layout and commenting out the handlers would still bring value to me.

Thanks,
Ian

**Comment by zukilover** [comment]
Thank you for the feedbacks.

I've fixed the following:
- [x] the filters don't seem to work. If I select one, the table goes empty
- [x] could the RFI Form be the minimum size necessary to show the text areas please ?
- [x] temporary disable action buttons

**Comment by IanMayo** [comment]
Great,
thanks @zukilover  - I'm dying to have a play :-)

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
