### PR TITLE
2521: Introduce leaflet-dialog, to show story of timeline

### LINKED ISSUE #2521: Introduce leaflet-dialog, to show story of timeline
Here is a react wrapper for a popup dialog:
https://github.com/mhasbie/react-leaflet-dialog

I'd like us to integrate it into the planning channel.  It will be visible when `showTimeControl` is true.  I will need an example of how to set the content.

Initially, I'd like it to be in the bottom-left of the map, about 300px wide and high.

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #2521 

image

### CODE REVIEW

**Review by IanMayo — DISMISSED** [review]
Good ground-work, thanks

**Comment by IanMayo** [comment]
Thanks @philb89 

>  I will need an example of how to set the content.

Could you also add a prop for the content?  As a demo of how to `drive` the content of the dialog panel, I'd like it to show the contents of the right-click array, as demonstrated here:
https://github.com/serge-web/serge/pull/2543/commits/d883005e83b01d9b3ab6bf2cc69d7775630c7c91

So, once you've added the new prop - we'll be able to call `setReplayDialogContent` - a state setter which will update the content of the dialog.

**Comment by IanMayo** [comment]
Hello @lebaphi  - there is a bit more work to do this too, please:
https://github.com/serge-web/serge/pull/2543#issuecomment-1453769049

**Comment by lebaphi** [comment]
Sure @IanMayo, I will update it

**Pull request closed without merging**
