### PR TITLE
RFI Response lost if UI updates

### LINKED ISSUE #944: RFI Response lost if UI updates
Issue #892 covered an issue where partially completed templates were lost when the UI updated (such as when receiving a new message).

This issue is also present in the RFI Editor page.

So, when a user has "taken ownership" of an RFI, and has partially completed their response, when a new message is received (such as a new Game Admin message), the RFI form updates, and the response is lost.

The form should not be reset.

Steps to reproduce:
* Login to game `CMDWK-HIGH DATA` as `Game Control`
* Navigate to RFIs page
* Open the `In Progress` RFI titled `Third Blue RFI`
* Write some text into the `Answer` box, such as `sample response`
* Write text into `Game Admin` channel, press enter
* The `Sample response` is lost

Note: the data for the above scenario won't be present until PR #945 merged

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #944

### CODE REVIEW

**Comment by IanMayo** [comment]
One issue, please @lebaphi 

We need to remember the private message, as well as the response.

screencast

**Review by IanMayo — CHANGES_REQUESTED** [review]
Need to remember private message, in addition to response.

**Comment by lebaphi** [comment]
> Need to remember private message, in addition to response.

Fixed @IanMayo

**Comment by IanMayo** [comment]
Hello @lebaphi - the Heroku build is failing. I see this in the error log:
image

I've tried to re-deploy a couple of times. Any suggestions?

**Comment by lebaphi** [comment]
> Hello @lebaphi - the Heroku build is failing. I see this in the error log:
> image
> 
> I've tried to re-deploy a couple of times. Any suggestions?

weird, let me check this 🤔

**Comment by lebaphi** [comment]
@IanMayo the code changes look fine, `yarn build` and `yarn test-unit` passed in my local machine. Let me create a new PR to see how it goes 🤔

**Comment by IanMayo** [comment]
> @IanMayo the code changes look fine, `yarn build` and `yarn test-unit` passed in my local machine. Let me create a new PR to see how it goes 🤔

It appears to be a fairly common error: https://www.google.com/search?q=92%25+chunk+asset+optimisation+terserplugin

There seem to be a number of causes.

**Comment by lebaphi** [comment]
move to https://github.com/serge-web/serge/pull/971

**Pull request closed without merging**
