### PR TITLE
1429: Should show the confirm dialog before removing participant

### LINKED ISSUE #1429: "Are You Sure" pop-up Permissions
Physical Proximity Edit Pen Garbage Bin

Considering the physical proximity of the edit pen to the garbage bin, we should add an "Are you sure you want to permanently delete this role?" pop-up when clicking on the garbage bin.

I've already accidentally deleted a force trying to edit it.

### PR DESCRIPTION
**Pull request by lebaphi**
Fix #1429

### CODE REVIEW

**Comment by lebaphi** [comment]
image

**Review by IanMayo — DISMISSED** [review]

**Comment by ShendMikullovci** [comment]
> image

Excellent. I think our previous pop-up works well: 

Are you sure delete

The text here would thus be 
"Delete Permission
Are you sure you want to permanently delete this permission?"

It would be ideal to also have the pop-up show the name of the user whose permission is being deleted, to emphasize the feature. Something like this:

Delete Permission

**Comment by lebaphi** [comment]
image

**Comment by IanMayo** [comment]
Thanks for moving this forward guys.

We need to called it a "participation" rather than a "permission".  It describes how a role (or group of roles) participate in a channel.  Can you rename the dialog please @lebaphi ?

**Comment by ShendMikullovci** [comment]
> image

Looks great! If you could change Permission to Participation like Ian said, and deploy it, that'd be good for me.

**Comment by ShendMikullovci** [comment]
I just checked deployment and it looks like you might have accidentally edited the Platform pop-up instead of the Participation one: 

Permission Platform Bug

**Comment by lebaphi** [comment]
I've updated @ShendMikullovci @IanMayo 

Screen Shot 2022-03-26 at 9 45 06 AM
Screen Shot 2022-03-26 at 9 45 17 AM

**Comment by ShendMikullovci** [comment]
Just checked the deployment. The feature is functional. 
A couple of things: 

1. It'd be nice to have the same format of pop-up throughout the screens. Both pop-ups dim the background and are centered in the screen to attract maximum attention. I have a small preference over the navy blue pop-up (platform one), though the delete button is less visible there. What do you guys prefer?
2. In the white pop-up, the affirmative button (yes/delete) should be placed on the right and the cancel/no button on the left.

**Comment by lebaphi** [comment]
I prefer the first popup, it looks neat and has a bit of a professional 😄 How to you think @IanMayo ?

**Comment by IanMayo** [comment]
@ShendMikullovci is right that the buttons are less clear on the darker popup .

A good _quick fix_ is for us to standardize on the lighter popup (with the white background on the central area).

Let's do that, please @lebaphi

**Comment by ShendMikullovci** [comment]
> @ShendMikullovci is right that the buttons are less clear on the darker popup .
> 
> A good _quick fix_ is for us to standardize on the lighter popup (with the white background on the central area).
> 
> Let's do that, please @lebaphi

Excellent. We should stick to "Cancel" (left) and "Delete" (right) instead of yes/no for the buttons. Have the delete button in navy blue and the cancel button in grey as usual.

**Review by IanMayo — APPROVED** [review]

**Review by IanMayo — APPROVED** [review]

**Comment by ShendMikullovci** [comment]
Just checked this. Works great! Thanks guys!

**Pull request merged**
