### PR TITLE
2366: When adding a Standard Area to a planning order - show the area

### LINKED ISSUE #2366: When adding a `Standard Area` to a planning order - show the area
For polygons in orders, players can either add them by drawing them, or add them from the drop-down list.

If they draw them, they are able to see the shape on the map.  But, if they select it from the list it isn't shown.

It would be good if _Somehow_ we could add the new shape to the drawing layer - so it gets drawn and the player can review what they are doing.  It also helps the player plan their `route back`.

We _probably_ have to push the `Layer` for the new shape into the GeoMan layer in `OrderDrawing`.   Hmm, if we do that, _maybe_ we no longer need to insert the shape ourselves - maybe the `GeoMan`  handler will jump onto it.

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #2366

### CODE REVIEW

**Comment by IanMayo** [comment]
Hey - this is scary stuff @philb89  - well done :-)

Can you explain why we need two copies of `leaflet.select.js`?  Is it just for storybook to work?

**Comment by IanMayo** [comment]
Ooh, we're not quite there.

I just started to create orders for Land > Patrol.  I drew the `route out`, selected a standard area (which appeared on the map :-) ), but then it didn't invite me to draw the `route back`.  This _used_ to work.

I think we need to create a `pendingGeometries` object to move things forward, and `onCreate` used to handle that.

**Comment by lebaphi** [comment]
> Hey - this is scary stuff @philb89 - well done :-)
> 
> Can you explain why we need two copies of `leaflet.select.js`? Is it just for storybook to work?

Hi @IanMayo, I update the leaflet.select.js to support new property `showSelectedIcon: true`

image

then we can determine which area is selecting.

**Comment by lebaphi** [comment]
> Ooh, we're not quite there.
> 
> I just started to create orders for Land > Patrol. I drew the `route out`, selected a standard area (which appeared on the map :-) ), but then it didn't invite me to draw the `route back`. This _used_ to work.
> 
> I think we need to create a `pendingGeometries` object to move things forward, and `onCreate` used to handle that.

ah sorry, I think I forgot to uncomment these lines 🤣

**Comment by IanMayo** [comment]
> then we can determine which area is selecting

I noticed the change.  I'm pretty sure we don't need to display the radio button.  We're treating this as a "command button" menu - that ends with a click.  We're not providing it to allow a user to investigate a tree of data.

Also:
> Can you explain why we need two copies of leaflet.select.js? Is it just for storybook to work?

**Comment by lebaphi** [comment]
> > then we can determine which area is selecting
> 
> I noticed the change. I'm pretty sure we don't need to display the radio button. We're treating this as a "command button" menu - that ends with a click. We're not providing it to allow a user to investigate a tree of data.
> 
> Also:
> 
> > Can you explain why we need two copies of leaflet.select.js? Is it just for storybook to work?

okay, let me update

**Comment by IanMayo** [comment]
One remaining issue, please.

The new rectangle is left drawn on the map when we finish creating the shapes.  I think we need to (optionally) remember it in state, and delete it when we finish.

Demo:  https://i.gyazo.com/ff89650eea2207523dc874c55fda21a6.mp4

**Review by IanMayo — APPROVED** [review]
Good solution, thanks.

**Comment by IanMayo** [comment]
Aah, hold on. There is a remaining issue.  We need to remove the `Standard Area` select control when the standard area has been selected.

Demo here: https://i.gyazo.com/01a67d7620e6c037fb74acd3d2537621.mp4

Could you also check that the `standard areas control` and the `standard polygon` are removed if the player `Cancels` planning the orders?

**Review by IanMayo — CHANGES_REQUESTED** [review]
Changes requested [here](https://github.com/serge-web/serge/pull/2501#issuecomment-1445033866) please.

**Comment by lebaphi** [comment]
> Changes requested [here](https://github.com/serge-web/serge/pull/2501#issuecomment-1445033866) please.

sure @IanMayo, I will update after dinner 👍🏻

**Comment by IanMayo** [comment]
Working fine :-)

**Comment by IanMayo** [comment]
Sorry @lebaphi -  I think this still isn't quite right.  As soon as we have planned the polygon (either by selecting a standard area, or drawing a polygon) - then the standard-areas menu should disappear. I know we don't want it there when the `route back` line is being drawn.  The logic to control this is in the `standardPolygons` state.  When this is zero or undefined, the we should not show the standard area menu.  Looking at it another way, we should only show the standard area menu when `standardPolygons` is contains items.

**Comment by IanMayo** [comment]
Working perfectly :-)

**Pull request merged**
