### PR TITLE
2416: Persistent Planning Channel layout/status (P2)

### LINKED ISSUE #2416: Persistent Planning Channel layout/status
It would be great if we could make these aspects of the PlanningChannel persistent between browser reloads (via storing as cookies, like we do for page layout):
* [x] Current tab
* [x] Current width of support panel
* For tables:
    * [x] Currently visible columns
    * [x] Whether filters are shown
    * [x] Which filters are applied
    * [x] Sort on any columns
    * [x] Number of rows visible
    * [x] Current turn number (_think_ this is stored in `ChannelPlanning` - so it would probably be stored/retrieved from there)

Note: I'd like the key to start with `serge.planning` and be suffixed with the current role-id (`selectedRoleId` - passed down from `SupportPanel` if necessary)

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #2416 - P2

* [x] Current tab
* [x] Current width of support panel
* For tables:
    * [x] Currently visible columns
    * [x] Whether filters are shown
    * [x] Which filters are applied
    * [ ] Sort on any columns

### CODE REVIEW

**Comment by lebaphi** [comment]
There is 1 unit test failed, I'm working on this :D

**Comment by IanMayo** [comment]
Nice work @lebaphi  But note: filters dont seem persistent between filters.
https://gyazo.com/758925f6b3d6efe630676740aa7e3d79

I'm pretty sure that `onSupportPanelLayoutChange` isn't being provided in `yarn develop`

**Comment by lebaphi** [comment]
> Nice work @lebaphi But note: filters dont seem persistent between filters. https://gyazo.com/758925f6b3d6efe630676740aa7e3d79
> 
> I'm pretty sure that `onSupportPanelLayoutChange` isn't being provided in `yarn develop`

Yep it was my fault, I just pushed the fixes 😄

**Comment by IanMayo** [comment]
@phi - is this ready to go?

**Comment by IanMayo** [comment]
Oops, sorry @lebaphi - I've broken this, while trying to fix a merge commit.

I've had to comment out the custom filter row, just to get filtering to work. But, obviously we're not now storing the filters :-(

I know we had the `custom-filter-row` that did some custom (sub-type) filtering, but I've fixed that with the new code that runs in the `visibleRows` state-change handler.   

But, you'll need to take some steps to store the current filters, please.

BTW - I played with it before I broke it, and the persistent filters were working perfectly :-)

**Comment by lebaphi** [comment]
> @phi - is this ready to go?

Yep @IanMayo 👍🏻

**Comment by lebaphi** [comment]
> Oops, sorry @lebaphi - I've broken this, while trying to fix a merge commit.
> 
> 
> 
> I've had to comment out the custom filter row, just to get filtering to work. But, obviously we're not now storing the filters :-(
> 
> 
> 
> I know we had the `custom-filter-row` that did some custom (sub-type) filtering, but I've fixed that with the new code that runs in the `visibleRows` state-change handler.   
> 
> 
> 
> But, you'll need to take some steps to store the current filters, please.
> 
> 
> 
> BTW - I played with it before I broke it, and the persistent filters were working perfectly :-)

no worries, let me check 😄

**Comment by IanMayo** [comment]
Hello @philb89 - the "dependent drop-downs" solution I implemented isn't perfect.  Sometimes it gets stuck.  In order to for users to get un-stuck we need them to be able to clear/reset the filters.  That mean we need to be sure the "remove filters - then - add filters" capability works, even with persistent filters. To be sure of that, when we to a UI update on `filters` being switched off, we should probably clear the `filters` object from the persistent storage - just to be sure.

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
