### PR TITLE
fixed filters

### LINKED ISSUE #1167: Filters can get broken on un-claim
A senior player (with "un-claim" permissions) need to un-claim an RFI.

Since there were lots of RFIs, he applied a filter for that role.  But, once the document was un-claimed, the filter was disabled - so he was unable to de-select the filter for that role.

Steps to reproduce:
* Login as Red http://serge-review.herokuapp.com/?wargame=wargame-kskl1i3t&access=pkskl17thb
* Submit an RFI into Red RFI
* Now submit another RFI to Red RFI
* Login as white player: http://serge-review.herokuapp.com/?wargame=wargame-kskl1i3t&access=pkskl17ti
* Go to Red RFI channel 
* Claim an RFI
* Login as J2A: http://serge-review.herokuapp.com/?wargame=wargame-kskl1i3t&access=rkskl61c3
* Go to Red RFI channel 
* Claim an RFI
* There will now be two RFIs visible, owned by two different players
* Filter for RFIs owned by `EXCON  J2b`
* Expand the single RFI
* Click on `un-claim`
* The RFI will disappear, and show an empty list. 

* This is because we're still filtering by "owner is J2B2 - but there are no "J2B" RFISs. We aren't offered the filter for that list because there aren't enough visible RFIs.  Serge decides whether to display a filter based on the number of visible rows.  That test needs to be "number of rows > 1" or "filter has been applied".

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
## 🧰 Issue

supports #1167 

## 🤔 Reason: 

Fixed cells field for a right filter

## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks @lilitkarapetyan - have you been able to check that the [steps to reproduce](https://github.com/serge-web/serge/issues/1167#issue-1009653498) now work?

**Comment by lilitkarapetyan** [comment]
> 
> 
> Thanks @lilitkarapetyan - have you been able to check that the [steps to reproduce](https://github.com/serge-web/serge/issues/1167#issue-1009653498) now work?

Yep, tested

**Comment by IanMayo** [comment]
This still seems broken to me @lilitkarapetyan .

image


There are two RFIs in the Red RFIs channel above.  I can't see either, and I can't get into `Owner` filter to clear it.

**Comment by IanMayo** [comment]
Aah, I see you change fixes on issue -where filters just didn't work.  The problem in the linked issue is still there though.

**Review by IanMayo — APPROVED** [review]
Label was necessary for filters. This fixes that.

**Pull request merged**
