### PR TITLE
Feature/374 tie up logic

### PR DESCRIPTION
**Pull request by foxleigh81**
## 🧰 Issue
#374 

## 🚀 Overview: 
Clicking on a marker now displays the correct form string in the map bar.

## 🔗 Link to preview
https://www.reddit.com/r/memes/comments/g6ofcq/i_aint_clucking_around/

## 🤔 Reason: 
This sets up our ability to populate the map bar with the correct components.

## 🔨Work carried out:
- [x] Tied up the logic
- [x] Updates the state
- [x] Output example string in storybook
- [x] Tests pass

## 🖥️ Screenshot

Screenshot 2020-04-23 at 15 31 39

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have assigned myself to this PR.
- [x] I have chosen an appropriate label for the PR.
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.
- [x] I confirm that I have checked for required README updates and acted accordingly.

## 📝 Developer Notes:
- This is foundational work for later work.

### CODE REVIEW

**Comment by IanMayo** [comment]
I _think_ there's an outstanding change.

If we do a click that results in no form being available (such as White clicking on Blue in Planning phase),  I think we should clear the form area - rather than leave the previous form there.

**Comment by foxleigh81** [comment]
> I _think_ there's an outstanding change.
> 
> If we do a click that results in no form being available (such as White clicking on Blue in Planning phase), I think we should clear the form area - rather than leave the previous form there.

What should go in its place? Looking at Celines designs, the map bar part is actually transparent so we could just say that there is no form there and the map is visible underneath?

**Comment by IanMayo** [comment]
Yes, that's fine.
In this part-way version, just the original empty panel would seem ok.

**Comment by foxleigh81** [comment]
> Yes, that's fine.
> In this part-way version, just the original empty panel would seem ok.

On it.

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
