### PR TITLE
Initial types to support commodities

### LINKED ISSUE #1325: Data changes for variable tracking
This issue describes the data structure(s) to support variable tracking.

### Strategy
1. Handle different types of commodity. Initially we will have a SimpleNumber commodity that takes any floating point value.  But, in the future that could extend to support a ranged commodity (with max/min), or an integer commodity, or free-text, or something that takes one of a number of fixed text values.
2. Separate into `commodity-type` and `commodity-value`. The first has the descriptive stuff & constraints.  The latter just stores the value.  In that way - we can confidently change the type details without it impacting on instances that have already been created.  The `type` and `value ` are linked by a unique `commID` reference value in the type data.

```
import {
  COMMODITY_TYPE_NUMBER,
  COMMODITY_VALUE_NUMBER
} from '@serge/config'


/** the basic type details common to all commodities */
export interface BaseCommodityType {
  commType: string
  // human-readable name for this commodity type
  name: string
  // unique id for this commodity type
  commId: string
  // description of this type of commodity
  description?: string
}

export interface NumberCommodityType extends BaseCommodityType {
  commType: typeof COMMODITY_TYPE_NUMBER
  /** name of units to use for this type */
  units?: string
  /** default value to use for this commodity */
  defaultValue?: number
  /** how to display values for this commodity (.e.g `0.00`) */
  format?: string
}

/** the basic type details common to all commodities */
export interface BaseCommodityValue {
  commType: string
  // id of this commodity (allows details to be looked up from type data)
  commId: string
}

export interface NumberCommodityValue extends BaseCommodityValue {
  commType: typeof COMMODITY_VALUE_NUMBER
  // value of this commodity
  value: number
}

/** union of all types of commodity type */
export type CommodityType = NumberCommodityType

/** union of tall types of commodity value */
export type CommodityValue = NumberCommodityValue

/** collection of instances of types of commodity */
export type CommodityTypes = CommodityType[]

/** collection of instances of values of commodity */
export type CommodityValues = CommodityValue[]


```

### PR DESCRIPTION
**Pull request by IanMayo**
Fixes #1325

### CODE REVIEW

**Comment by IanMayo** [comment]
Hello @lebaphi - I think I'll be handing this branch over to you, soon.

I've got the `basics` for editing commodities working in the `setting-platform-types` admin page. If you click on `fishing-vessel` you'll see the `Commodities` editor section.  It's working in the storybook.  But, I've only seen how to support a single toggle button.  As the `commodities-UI` issue describes, I now realise we need more columns in the editor: https://github.com/serge-web/serge/issues/1291#issuecomment-1029230097

We've got to wait for Shend to finish the UX for these extra columns, but it would be useful if you could modify the `Commodities` sorted-table by adding a column/text-box for `Units`. I presume this is done in `renderCommoditiesSection`.

**Comment by IanMayo** [comment]
Thanks @lebaphi .   A step forward, but we still need column headers - to understand the data.
Screenshot 2022-02-05 at 10 22 42

**Comment by lebaphi** [comment]
Hi @IanMayo @ShendMikullovci , I just added the header, how do you think?

Screen Shot 2022-02-07 at 10 55 03 AM

**Comment by IanMayo** [comment]
> Hi @IanMayo @ShendMikullovci , I just added the header, how do you think?
> 
> Screen Shot 2022-02-07 at 10 55 03 AM

Are you able to use a row of icons, like @ShendMikullovci design [here](https://github.com/serge-web/serge/issues/1291#issuecomment-1030903575)?

**Comment by IanMayo** [comment]
Great progress @lebaphi 

1. We need a column for default value
2. We don't need both "bin" and "cross" buttons. _Think_ I prefer the `x` on the right-hand side
3. The row becomes unstable if the name of the new commodity gets deleted.  It goes to `undefined` and can't be edited.  I guess we need to prevent the whole name being deleted
4. @ShendMikullovci has come up with a set of icons for the columns.  If you create tooltips for them - I can fill in the tooltip text.
5. The columns for `units` and `format` can be restricted to 5 chars.  That will allow more room for the wider fields (name and description).

**Comment by ShendMikullovci** [comment]
> 2. We don't need both "bin" and "cross" buttons. _Think_ I prefer the `x` on the right-hand side

I do too. It's much neater, though I've kept using the bin for icon uniformity. 

Do we need a description of the commodities?

**Comment by IanMayo** [comment]
> Do we need a description of the commodities?

"Need" is a bit strong. No, we don't _need_ the description. Let me check with game-designer.

**Pull request merged**
