### PR TITLE
make unit tests workable

### LINKED ISSUE #1731: Re-introduce unit tests for `package/client`
I was going to fix an issue in a message handler - to ensure an unnecessary (but bulky) data object gets skipped.

So, I started by extending the existing unit test, to fail when the bulky object was present.

I tried to run the test, but running the test failed.

So, the build needs to be fixed so that we have a working `yarn unit:test` in `packages/client`.

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
Fixes #1731

### CODE REVIEW

**Comment by lilitkarapetyan** [comment]
I keep working on unit test.

**Comment by IanMayo** [comment]
Hello @lilitkarapetyan - I can see how challenging this is.  I'm happy for you to comment out the tests, get the build working, and then we can steadily un-comment the tests.

**Comment by lilitkarapetyan** [comment]
I will continue on Monday.

**Comment by lilitkarapetyan** [comment]
I have finished to fix bugs and refactor code for tests.

**Comment by IanMayo** [comment]
Closing this PR.  It's no longer relevant after our switch to monolith.

**Pull request closed without merging**
