### PR TITLE
Fix message read and mark as read

### LINKED ISSUE #879: "Mark as read" / "Mark all as read" not working
In formatted messages, once a player has expanded a message, it is marked as read.

At the top of a channel, the player is able to mark all messages as read.

Here is a recording of an old (2019) instance of Serge:
screencast

The UI is still present to trigger these actions, but the messages don't get marked as read.

### PR DESCRIPTION
**Pull request by sanjayradadiya**
## 🧰 Issue

Fixes #879 

## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Comment by IanMayo** [comment]
Hello @sanjayradadiya - thanks for this, you've done a good job.

The desired behaviour is for the message-read status to be persistent between sessions. 

See this old branch: https://serge-dev.herokuapp.com/

If you log in as Blue CO, and send the long message, you'll see that if you mark it as read, then refresh the page & log in again, the message is already read.

**Comment by sanjayradadiya** [comment]
> Hello @sanjayradadiya - thanks for this, you've done a good job.
> 
> 
> 
> The desired behaviour is for the message-read status to be persistent between sessions. 
> 
> 
> 
> See this old branch: https://serge-dev.herokuapp.com/
> 
> 
> 
> If you log in as Blue CO, and send the long message, you'll see that if you mark it as read, then refresh the page & log in again, the message is already read.

Thanks for reminding me , i will again look and fix it

**Comment by IanMayo** [comment]
@sanjayradadiya - I could do with a fix on this, please.

**Comment by IanMayo** [comment]
I'm going to merge this version. We'll have to do the `persistent` fix in another branch.

**Pull request merged**
