### PR TITLE
Assets_disappear_after_15_seconds_heartbeat

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Comment by IanMayo** [comment]
Can you help me out with the `react` here please @lilitkarapetyan  ?

Neither `allForces` or `currentForce` have actually changed state.  Do you know why the `useState` is firing?

**Comment by lilitkarapetyan** [comment]
`useEffect` was seeing a change in its dependencies, but there was actually no change.

**Comment by IanMayo** [comment]
> JSON.stringify(prevProps) === JSON.stringify(nextProps)

Will this take long?  They are huge documents.

**Comment by IanMayo** [comment]
> > JSON.stringify(prevProps) === JSON.stringify(nextProps)
> 
> Will this take long? They are huge documents.

Only 6 millis for large wargame - that's not bad.  
image

**Pull request merged**
