### PR TITLE
Feature/450 task group data

### LINKED ISSUE #446: Introduce buttons for "View as"
When logged in as Umpire, we need a "View As" toolbar, to allow the umpire to double-check information is being displayed correctly for the player forces:
image

Ian is happy to implement the processing logic, but doesn't know how to add the buttons.

It would be satisfactory for the buttons to fire a callback in the `mapping` component, like this:
```
const viewAsCallback = (force: string) => {
    console.log("view as clicked, force:", force)
}
```
 
So this issue is just to create the buttons, and to call the callback. One button will be created for each force that either has assets, or is listed in `Controlled By` for another force (white can control green in the current mock document).  Ian will implement the other logic.

### PR DESCRIPTION
**Pull request by IanMayo**
## 🧰 Issue

Supports #450 
Fixes #446 

## 🚀 Overview: 

Prepare the data necessary to "drive" task group support

## 🔗 Link to preview

https://serge-review-feature-45-55s1ht.herokuapp.com/storybook/?path=/story/local-worldstate--with-phases

## 🔨Work carried out:

* [x] Add hosting and comprising elements to mock force data & wargame database
* [x] Generate details of child elements in route-building process
* [x] Introduce new platform type, for Task Groups
* [x] Collate data necessary for child elements
* [x] Modify renderer so it shows icons for child elements

- [x] Tests pass

## 🖥️ Screenshot

image

image

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have assigned myself to this PR.
- [x] I have chosen an appropriate label for the PR.
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.
- [x] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Comment by IanMayo** [comment]
@lilitkarapetyan - are you able to help me finish off this PR please?

I've updated the mock data model(s) to create child elements, and have created icons for them:
image


I have created the child icons, but I don't know how to "embed" them within the collapsible top level entry, like in this image:

image

There is one other bit I've got stuck on. I can't stop the click event for a child asset from propagating back up through the parents.  The handler is in `WorldState\index.tsx`, in the `assetClick` method at line 124.

**Comment by lilitkarapetyan** [comment]
изображение

**Comment by IanMayo** [comment]
Ooh, good start :-)

I don't think we need the "Hosting" or "Comprising" titles.  Hopefully we can have a `+` or `-` markers instead of `1` and `2`.

**Comment by lilitkarapetyan** [comment]
изображение

**Comment by lilitkarapetyan** [comment]
изображение

**Comment by IanMayo** [comment]
**BRILLIANT** - thanks Lilit.

There is a problem with the data in game-mode (nothing showing in World State), but that is my problem, and I will fix it on Monday.

image

**Comment by IanMayo** [comment]
Hello @lilitkarapetyan - I've investigated the above issue.  I did think I must have been collating the information in the wrong way.

But, I am collecting the correct routes.  The `isType()` tests are failing, but I'm not sure how they're working:
image

To make things easier to test, I've created a new wargame, and have initialised it.  This URL should work on your machine:
http://localhost:3000/?wargame=wargame-kc0hnnmp&access=p5543

It will take you in as the Blue Player.

Hopefully you can debug this. I tried commenting out the `isType` check. It introduced the correct elements into the DOM, but they weren't visible - I don't think they had space allocated.

Note: I see the icons were set to `display:none` for type `.main` in the `styles.module.scss` for `collapsible/content`.

Note: by changing `display:none` to `display:block`, and then commenting out the two `isType()` calls, the data shows, but it's missing the expand/collapse icons, as below:

image

**Comment by lilitkarapetyan** [comment]
изображение

**Review by lilitkarapetyan — APPROVED** [review]

**Pull request merged**
