### PR TITLE
Add React Geoman controls

### LINKED ISSUE #2693: React - Geoman
Add the [React-GeoMan](https://github.com/TurtIeSocks/react-leaflet-geoman) to the new Core Mapping component.

Provide the full set of tools as provided in the [demo](https://geoman.io/demo)

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes https://github.com/serge-web/serge/issues/2693

image

### CODE REVIEW

**Review by IanMayo — APPROVED** [review]
nice work @lebaphi

**Review by IanMayo — CHANGES_REQUESTED** [review]
Oops, there is a build issue @lebaphi

**Comment by IanMayo** [comment]
Thanks for this @lebaphi 

As a next step, could you try to add new element(s) to the `features` object and re-render?

A point will have type `milSymRenderer` (using the same SIDC as our existing sample object), and other shapes will have `coreRenderer` type data.

I'm not fully sure how to do the above, but am happy to help out if you put in some of the infrastructure for me.

**Comment by lebaphi** [comment]
I think it's quite simple @IanMayo , here is what I did with new code changes :D

image

**Comment by IanMayo** [comment]
Yes, that was easy.

I meant to say - can you modify the app so that if we add a point/shape using GeoMan that it gets added to the list of features and re-rendered.

**Comment by IanMayo** [comment]
Remaining items moved to separate issues

**Review by IanMayo — APPROVED** [review]

**Comment by lebaphi** [comment]
> Remaining items moved to separate issues

Can you add the link of that item here? @IanMayo

**Comment by IanMayo** [comment]
> > Remaining items moved to separate issues
> 
> Can you add the link of that item here? @IanMayo

Sure: https://github.com/serge-web/serge/issues/2694

**Pull request merged**
