### PR TITLE
Update storybook from v6 to v8

### LINKED ISSUE #2935: Update storybook
We're on Storybook 6.5. 

Storybook is now on 8.x - which I believe brings performance upgrades.

We should upgrade our Storybook version.

If it's not easy to upgrade any stories, then it's ok to remove the `-inc` element from the filename, which should prevent them from being processed.

If Storybook 8.x has a new model for stories, then we should _try_ to update the current `-inc` stories.  It's ok to remove the `-inc` if they are not easy to fix, but we should convert at least one of them (hopefully core-mapping)

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #2935 

image

### CODE REVIEW

**Comment by Tristina1788** [comment]
@lebaphi  @IanMayo  I get this error when running 'yarn build' but seem system still works as normal 

image

I also see it from the github running for building project. So we can ignore the error?

image

Checking version of story book and now it's updated to 8.x

image

- I can see some news data on this storybook and also found  errors on some pages

image

image

image

image

image

....

@IanMayo  Should I put all error on this PR or I can create another issue for these error?

**Comment by lebaphi** [comment]
I think these errors happened in v6 @Tristina1788 @IanMayo , so we can rule them out like we did before.

Screen Shot 2024-05-12 at 5 04 36 PM
Screen Shot 2024-05-12 at 5 03 49 PM

**Comment by Tristina1788** [comment]
> I think these errors happened in v6 @Tristina1788 @IanMayo
> 
> Screen Shot 2024-05-12 at 5 04 36 PM Screen Shot 2024-05-12 at 5 03 49 PM

They're new parts from storybook 8.x. I don't see it on 6.x

image

**Comment by lebaphi** [comment]
> > I think these errors happened in v6 @Tristina1788 @IanMayo
> > Screen Shot 2024-05-12 at 5 04 36 PM Screen Shot 2024-05-12 at 5 03 49 PM
> 
> They're new parts from storybook 8.x. I don't see it on 6.x
> 
> image

We excluded them in version 6 so that's why you can't see it

**Comment by Tristina1788** [comment]
> > > I think these errors happened in v6 @Tristina1788 @IanMayo
> > > Screen Shot 2024-05-12 at 5 04 36 PM Screen Shot 2024-05-12 at 5 03 49 PM
> > 
> > 
> > They're new parts from storybook 8.x. I don't see it on 6.x
> > image
> 
> We excluded them in version 6 so that's why you can't see it

Thanks. So I will create

**Comment by Tristina1788** [comment]
Sorry, seems I click wrong button make the PR close. So I reopen it.

**Comment by IanMayo** [comment]
Hello @philb89 - I've pulled this branch, done `yarn install` then `yarn storybook`.   When storybook opened, I saw this error:
image

I then scrolled back up the terminal, and found this:
image

These are in the `devDependencies` section of the root `package.json`. The lines are new for this PR.

It _looks-like_ I should delete them.  Any suggestions?

**Comment by IanMayo** [comment]
Hello @philb89 

(earlier issue hidden, I hadn't pulled all changes)


Current issue is that the Heroku build is failing. It works fine locally, but can't find `storybook` on Heroku hosting:
image

I _think_ I see possible related changes in `package.json`:
image

**Comment by Tristina1788** [comment]
Checked on the latest code on this branch, I can deploy local without issue. And Storybook is on version 8.x as expected.

image

**Comment by IanMayo** [comment]
Thanks @Tristina1788 - the current issue is that Storybook isn't provided in Heroku.  Being able to review a new feature vai Storybook on Heroku (without having to do a local build) is a really convenient project capability for me.

**Comment by lilitkarapetyan** [comment]
Now Storybook is up and running on Heroku. - https://serge-2935-update-story-2tde1i.herokuapp.com/storybook/

**Comment by IanMayo** [comment]
> Now Storybook is up and running on Heroku. - https://serge-2935-update-story-2tde1i.herokuapp.com/storybook/

Perfect, thanks @lilitkarapetyan .

I'm sure @lebaphi  wants to thank you, too ;-)

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
