### PR TITLE
Edit_orders_form_lost_on_table_update

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Comment by IanMayo** [comment]
@lilitkarapetyan - I don't know about the most recent commit, but this PR doesn't fix the issue for me.  Pulling new commit, and trying again.

**Comment by IanMayo** [comment]
@lilitkarapetyan - this PR doesn't fix it for me:
screencast

**Comment by lilitkarapetyan** [comment]
> 

I reproduced the mentioned steps, got this error and solved it - https://www.loom.com/share/44584a0806fc422da7529144d5dafe4c

**Comment by lilitkarapetyan** [comment]
I will work on it

**Comment by IanMayo** [comment]
Ok.  I think you were ok since you were using two new sets of orders.  The issue is when one user is editing an existing set of orders - since existing orders are a `detail` panel in the `material table`.

**Comment by albertazroyan** [comment]
I think the problem occurred after making changes to the `jsonEditor` , I don't know what the problem is yet, I need to look into it

**Comment by lilitkarapetyan** [comment]
I think the problem occurred after making changes to the `jsonEditor `, I don't know what the problem is yet, I need to look into it

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
