### PR TITLE
2352 can not change template in a custom channel

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Comment by IanMayo** [comment]
the fix works, well done @lilit :-)

There is another issue - but I don't know if it's related or not.  After we have sent a message, when I click on `New message` to send another, the previous message is still in there. I guess we need to clear the cache after the message is sent, or after it is cancelled.

https://i.gyazo.com/49f702deaa6a0bce7c3c70222c06d874.mp4

**Comment by lilitkarapetyan** [comment]
me too I think it's a cache issue, I will work on it

**Comment by lilitkarapetyan** [comment]
Okay, I will work on it.

**Review by IanMayo — APPROVED** [review]

**Comment by IanMayo** [comment]
@lilitkarapetyan - we weren't clearing the form on cancel. I think I've fixed it, and tried to explain the new clearForm prop here: https://github.com/serge-web/serge/commit/9c9c285b7348accda92a9402aef0f84e5a9c0735

Does it look ok to you?

**Pull request merged**
