### PR TITLE
update_stack_heroku_and_node

### LINKED ISSUE #2652: Update stack (Heroku & node)
We're currently running on Node-16

We should update to a more recent version.

Heroku is also complaining. (I've fixed Heroku)

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
Fixes #2652

### CODE REVIEW

**Comment by lilitkarapetyan** [comment]
Hello,I'm currently using a Windows operating system on my computer, I have successfully downloaded the` node_sqlite3.node` file for the `Windows 64-bit (win64) `platform. Now, I need assistance in downloading the corresponding file for `Linux` and `macOS ` using `Node version 18.15.0`. Can you please guide me through the process ?

**Comment by lilitkarapetyan** [comment]
https://gyazo.com/206743600a52ea0bdf371c3e5b6187f1  - The warning message you're seeing is indicating that the source map file (DoubleScrollbar.js.map) for the react-double-scrollbar module cannot be found in the specified path. This warning is related to the source-map-loader module, which is responsible for parsing source maps.  I believe that the 'react-double-scrollbar' library is not supported in Node 18 when using the '@material-table/core' library 
Screenshot (226)

I use this fork until the fix is merged -  "resolutions": {
   ` "react-double-scrollbar": "IniterWorker/react-double-scrollbar",`
    "@types/react": "^16.14.5",
    "node-sass": "^9.0.0"
  },

**Review by IanMayo — DISMISSED** [review]

**Comment by IanMayo** [comment]
(doing close/re-open to try to wake up Build/test validation)

**Comment by IanMayo** [comment]
Hmm, @lilitkarapetyan - do you know why the second `Build/Test validation` has `16.x`?

**Comment by IanMayo** [comment]
Thanks for this @lilitkarapetyan .  One thing just jumped into my head.  Have you tried to build and run an executable on the updated version of node?   (`yarn pkg-build`).

**Comment by lilitkarapetyan** [comment]
> Thanks for this @lilitkarapetyan . One thing just jumped into my head. Have you tried to build and run an executable on the updated version of node? (`yarn pkg-build`).

Yes, are you experience any problems while running `the yarn pkg-build` cimmand?

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
