### PR TITLE
1700: Can't change visibility toggles

### LINKED ISSUE #1700: Can't change visibility toggles
In the Adjudicate Turn and Visibility forms, the Game Manager is able to indicate which forces can see the selected platform.

Currently, these checkboxes don't have labels - they should have the Force Name above them.

They're also not responding - they don't change when clicked.

The adjudicate turn form is here:
https://serge-review.herokuapp.com/storybook/?path=/story/local-organisms-adjudicateturnform--default

Feel free to `unblock any other stories that you need for testing/verification (just remove the `-inc` suffix from the story).

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1700 

develop:
Screen Shot 2022-07-29 at 3 35 08 PM

storybook:
Screen Shot 2022-07-29 at 3 34 56 PM

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks for this @lebaphi 

Do you know why `develop` and `storybook` use different styles of control?

**Comment by IanMayo** [comment]
Hello @lebaphi - you missed the "Condition and visibility" form. But, I was able to copy your fix.

We had the problem with the update handler since the RCB component is poorly typed.

I've created a separate issue to handle that.

**Comment by IanMayo** [comment]
One other change @lebaphi: the checkbox wasn't color-coded in the `visibility and condition` form:
image

I fixed it by removing the scss instruction to shade the `svg` control white (see below), using this [commit](https://github.com/serge-web/serge/pull/1702/commits/3fd0816262904915fa52a5a6525c533d28267937)

Do you think that change will break anything?

image

**Comment by lebaphi** [comment]
> One other change @lebaphi: the checkbox wasn't color-coded in the `visibility and condition` form: image
> 
> I fixed it by removing the scss instruction to shade the `svg` control white (see below), using this [commit](https://github.com/serge-web/serge/pull/1702/commits/3fd0816262904915fa52a5a6525c533d28267937)
> 
> Do you think that change will break anything?
> 
> image

I think it's fine @IanMayo

**Review by IanMayo — APPROVED** [review]
Working fine

**Pull request merged**
