### PR TITLE
Core mapping - Admin Page

### LINKED ISSUE #2971: Game Designer - create/edit Core Mapping channel
The Core Mapping channel has quite a complex data model.

We need to allow the Game Designer to use the Admin Pages to create and edit these channels, according to the designs contained here: 
https://docs.google.com/presentation/d/1SUUJMWkmii_C1y-rRrHbtTxaIXQeWpTDCy_6hF6Fj2g/edit?usp=sharing

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #2971

### CODE REVIEW

**Comment by IanMayo** [comment]
Hello @lebaphi - the PlayWright testing is currently failing for this.  That's quite understandable, since so much as changed.

So, I suggest we (well, you ;-) ) change the CI workflow to comment out the PlayWright testing until this branch is mature, then we will reinstate it.

**Comment by Tristina1788** [comment]
I can see 'Core Mapping' from admin page of game 'P10-Test' . But we still in implementing, so I don't check more on this.

image

**Comment by IanMayo** [comment]
Nice work so far @lebaphi 😀

**Comment by Tristina1788** [comment]
@IanMayo Do you think we should change the 'Delete' icon to '...' icon. And we can have 2 actions (Delete / Duplicate) for each renderer . So that, we can create duplicated renderer and edit properties which we want to change. So it save time for creating.

image

**Comment by IanMayo** [comment]
> @IanMayo Do you think we should change the 'Delete' icon to '...' icon. And we can have 2 actions (Delete / Duplicate) for each renderer . So that, we can create duplicated renderer and edit properties which we want to change. So it save time for creating.

Thanks @Tristina1788 - that's a good idea, but we currently only have the two renderers and don't expect them to be duplicated. Let's defer the suggestion for the future.

**Comment by Tristina1788** [comment]
@IanMayo @lebaphi  
- We need 'Core Mapping' on this dropdown list on 'Add Channel' dropdown list.

image

- The confirm popup should show when user click on 'Delete' property of renderer.

image

- We should not limit Max Native Zoom/ Max Zoom/ Min Zoom from 1 -> 20. These values should have value > 0 and don't have max number. **Ian here: Actually, can we allow 0 to 20 (inc) - that's the reasonable max range of zoom levels for a Leaflet Map**

image

- We don't have 'Others' on 'Edit Property' and 'Icon' property doesn't have upload button to change icon

image

- Should we have input name of renderer? Currently we have 2 types 'Core', 'MilSym' . If we have same name for renderers. It make admin don't know which renderer he want to update. 

image

- In 'Participants' , roles don't shows any value in dropdown list to select

image

- I can't update 'Edit props' to 'True'


https://github.com/serge-web/serge/assets/107697044/dd7344c0-e553-44b1-8635-cee836cc9828

**Comment by Tristina1788** [comment]
@lebaphi @IanMayo 
- Now I can update 'Edit props' to 'True'

image

- Confirm popup show when user click on 'Delete' property of renderer as expected

image

**Comment by Tristina1788** [comment]
@lebaphi  @IanMayo We should remove column 'Icon'. And we still don't have the way to update 'Others' because it's not in edit form

image

image

- Create new Core Mapping channel make the default core mapping channel lose data

https://github.com/serge-web/serge/assets/107697044/e5421b40-06f5-47e2-ac08-61134d9f14b2

- We should have the way to add 'Participants' . 

image

**Comment by IanMayo** [comment]
I've just done some testing @lebaphi - it's looking good.   Note: for the `EnumProperty` the game designer needs to provide a list of values (`choices`), and for `NumberProperty` there should be an optional `Format` attribute that controls how the numbers are shown.

Oh, and there should be a `lines` attribute for a `StringProperty`.

For string and enum properties there should be a string `default` attribute, and a numeric one for number properties.

**Comment by Tristina1788** [comment]
@lebaphi User role with 'View Props' = false, 'Edit/Remove Feature' = false, 'Move/Resize Feature' = false, user still can see props and edit/remove , move/resize feature 


https://github.com/serge-web/serge/assets/107697044/a87874e6-2db5-4a00-95f7-e028da710e31

**Comment by IanMayo** [comment]
> @lebaphi User role with 'View Props' = false, 'Edit/Remove Feature' = false, 'Move/Resize Feature' = false, user still can see props and edit/remove , move/resize feature

Thanks for the @Tristina1788 .  I'll start off on the failure to use the props permission.  The mapping permissions may require some trickery we haven't done before (allowing a user to move features from one force but not the other).

**Comment by Tristina1788** [comment]
@lebaphi  @IanMayo The list roles in force is not correct

image

- The name of collumns are not correct 
 
image

**Comment by IanMayo** [comment]
> @lebaphi @IanMayo The list roles in force is not correct

Yes, we should show the role `name`, rather than `id`

**Comment by IanMayo** [comment]
Hello @lebaphi - for the mapping channel editor in the admin pages, the text inside the badges/lozenges is really small.  I know you had to do that to fit them in the UI.  But, it is possible to trim down the whitespace padding in the badge, so the text can be a little larger?
image

**Comment by Tristina1788** [comment]
@lebaphi @IanMayo  I get white screen after updating properties of renderer.

Steps :
1. Update a property of a renderer
2. Logout and login gameplay 
3. Click on renderer which has updated for renderer
4. Notice the white screen


https://github.com/serge-web/serge/assets/107697044/4b4253c9-840a-4321-ba53-852d7dde756d

- Zoom numbers are reverted after changing another field

Stesp: 
1. Update Max Native Zoom = 1
2. Update Max Zoom = 2
3. Notice Max Native Zoom is reverted to original value (12)


https://github.com/serge-web/serge/assets/107697044/466a1301-d30e-46c2-b250-bac906801a11

**Comment by Tristina1788** [comment]
@lebaphi @IanMayo 

-  Now 'Zoom numbers are reverted after changing another field' is fixed. I can update these values as expected.

- Role get correct names

image

- Create new renderer and I get white screen in gameplay : 

https://github.com/serge-web/serge/assets/107697044/6f566818-56b2-4a1c-acf2-b797461652fd

**Comment by IanMayo** [comment]
Ok, the white-screen is one for you please @lebaphi .  I'm getting ready for my vacation :-)

I don't think we need complex logic, just handle the case where we are lacking details for a renderer.

**Comment by IanMayo** [comment]
@Tristina1788 - the `new renderer` issue should be fixed in my last commit.

**Comment by Tristina1788** [comment]
> @Tristina1788 - the `new renderer` issue should be fixed in my last commit.

@IanMayo  Yes, the issue on new renderer is fixed now : https://app.screencast.com/NwfECxUDvz7v6

**Comment by IanMayo** [comment]
So is this ready to go @Tristina1788 ?

**Comment by Tristina1788** [comment]
@IanMayo  @lebaphi  We still have some issues here : 

- We should not limit zoom value from 1->20 , it should be the number > 0  and don't have limit for max

image

- Participants is not shows all Force of game. I think we should have button 'Add' , so that we can add more force and  if we delele participants then want to add again.

image

- Subject participants should be Force /Role instead of Force

image

- We should have space from shape of text 

image


- Should we have tool-tip or any way for user understand the short word for type permissions?

image

**Comment by lebaphi** [comment]
> We should not limit zoom value from 1->20 , it should be the number > 0 and don't have limit for max

if so, i think we shouldn't use dropdown list, it should be input text. What do you think @IanMayo @Tristina1788 ?

**Comment by Tristina1788** [comment]
@lebaphi @IanMayo

- Create new 'Core Mapping' channel , seem it gets same data with 'Core Mapping' default channel. But after click another channel, the new 'Core Mapping' channel return empty data.

https://github.com/serge-web/serge/assets/107697044/cf82f01c-9605-4b47-96ea-e3323a183cdf

- Update permissions from admin page and the tools is lost some functions from gameplay

https://github.com/serge-web/serge/assets/107697044/db62f6be-3f33-421c-96a8-320c0a709130

- The color on core shape is darker after add new renderer 'Core'

https://github.com/serge-web/serge/assets/107697044/0c1f9e38-da68-4678-8a03-03692fdd813e

**Comment by lebaphi** [comment]
image

=> the channel data does not have the green force, so we don't display it here

image

=> some participants does not have role, so what do you think @IanMayo ?

image

=> We can add tooltip and @IanMayo can design details for each permission, but only admins can access this page and I think admin are the one who understand what these permissions mean, do we need more tooltip?

image

=> this is because you are adding 2 core renderers => it renders 2 times. Should we allow to add 2 renderers which has the same kind @IanMayo ?

**Comment by Tristina1788** [comment]
> image
> 
> => the channel data does not have the green force, so we don't display it here

@lebaphi @IanMayo I think 'Force' should get from 'Force' tab . So it should has all force or enable to add all force. How do you think?

image

**Comment by Tristina1788** [comment]
@lebaphi @IanMayo 

- Zoom should only able to input number

image

- 'Update permissions from admin page and the tools is lost some functions from gameplay' : it 's fixed

- Label of property 's render is show wrong

image


image

**Comment by lebaphi** [comment]
> > image
> > => the channel data does not have the green force, so we don't display it here
> 
> @lebaphi @IanMayo I think 'Force' should get from 'Force' tab . So it should has all force or enable to add all force. How do you think?
> 
> image

it should be the force in channel participant I think

**Comment by Tristina1788** [comment]
@lebaphi  @IanMayo 

- Now Zoom only able to input number

image

- We have 'Add' for adding participant. But in 'Adding' form, new force don't show its role (Notice : update form can show its role)

image

image

- Subject and permission don't show name of Force 

image

- Label of property 's renderer show correctly . But coremapping doesn't show property 'Enum'

image

image

- Property with 'Editable' = false, still can edit from mapping

https://github.com/serge-web/serge/assets/107697044/8e463175-3722-42d9-8e29-91f4c25e265f


-  Create new 'Core Mapping' when user in 'Properties' tab, it still keeps same value with exist coreMapping channel until click 
to another tab


https://github.com/serge-web/serge/assets/107697044/97e78b61-58d0-4125-89d2-c1f6a0723fbb

**Comment by Tristina1788** [comment]
@IanMayo @lebaphi 

- Now issue `We have 'Add' for adding participant. But in 'Adding' form, new force don't show its role (Notice : update form can show its role)` is fixed
- Created new participant and login game play with this user and draw a shape. It will make the exist shape / core are dissapeared.

https://github.com/serge-web/serge/assets/107697044/b167d202-7dd3-4da7-8af8-70cc7eca41c2

- Property enum can be showed as expected. But we should guide them how to create option by Note or tool tip (exapmle :  input option and enter to create a new option )

image

image

- Participant can show name of force

image

- The renderer shows on gameplay is not correct with config for exist properties (force, important, phase) of renderer ( Example : properties 'Force' of 'Core' has 'editable' = false. But from UI it shows as 'Editable' =true. After update another infors on this properties (ex : Descritpion), gameplay can show correct with properties (Editable from game play is false)

https://github.com/serge-web/serge/assets/107697044/46fee2fd-e094-4702-b003-00e2ed6869a7

- Update property 'Editable' of 'Turn' to false but gameplay always show as 'Editable' = true

**Comment by Tristina1788** [comment]
@IanMayo @lebaphi
- The exist properties of Core/ MilSym don't get from its properties. (Notice description to know where it gets properties)
Example : 
- Category, size : gets properties from MilSym
- Force, Important, Phase, Turn : gets properties from Core


https://github.com/serge-web/serge/assets/107697044/54297dd8-d7a9-4a46-8eb5-eab78b583f36



- Force dropdown list for Force properties should gets from 'Force' tab instead of input as enum values. @IanMayo @lebaphi How do you think? Because we can input incorrect name of Force and it will get invalid force to select.

image

**Comment by lebaphi** [comment]
>Force dropdown list for Force properties should gets from 'Force' tab instead of input as enum values. @IanMayo @lebaphi How do you think? Because we can input incorrect name of Force and it will get invalid force to select.

This dropdown list is used for admin users to add or remove options for enum properties (we don't have this feature in the design), so we should not add constraints to it I think. What do you think? @IanMayo

**Comment by IanMayo** [comment]
> > Force dropdown list for Force properties should gets from 'Force' tab instead of input as enum values. @IanMayo @lebaphi How do you think? Because we can input incorrect name of Force and it will get invalid force to select.
> 
> This dropdown list is used for admin users to add or remove options for enum properties (we don't have this feature in the design), so we should not add constraints to it I think. What do you think? @IanMayo

Yes - this is a free-form control.  In this case it is being used for force, but for now I'm ok with forcing the game-designer to enter the correct force id values.

Maybe we'll add a dedicated `force` control type in the future, but not now.

Any other issues on this PR @Tristina1788 ?

**Comment by Tristina1788** [comment]
> > > Force dropdown list for Force properties should gets from 'Force' tab instead of input as enum values. @IanMayo @lebaphi How do you think? Because we can input incorrect name of Force and it will get invalid force to select.
> > 
> > 
> > This dropdown list is used for admin users to add or remove options for enum properties (we don't have this feature in the design), so we should not add constraints to it I think. What do you think? @IanMayo
> 
> Yes - this is a free-form control. In this case it is being used for force, but for now I'm ok with forcing the game-designer to enter the correct force id values.
> 
> Maybe we'll add a dedicated `force` control type in the future, but not now.
> 
> Any other issues on this PR @Tristina1788 ?

@IanMayo  We still has issues on 2 comments : 
- https://github.com/serge-web/serge/pull/2970#issuecomment-2198481938
- https://github.com/serge-web/serge/pull/2970#issuecomment-2199920827

**Comment by IanMayo** [comment]
> @IanMayo We still has issues on 2 comments :

Thanks @Tristina1788 - please help @lebaphi in getting them sorted.

**Comment by Tristina1788** [comment]
> > @IanMayo We still has issues on 2 comments :
> 
> Thanks @Tristina1788 - please help @lebaphi in getting them sorted.

@lebaphi , @IanMayo  Here are the remaining issues : 

- Created new participant and login game play with this user and draw a shape. It will make the exist shape / core are dissapeared.

https://github.com/serge-web/serge/assets/107697044/7ee502d2-420a-44ee-a275-b146f333c711

- We should guide them how to create option by Note or tool tip (example : input option and enter to create a new option )

image

- The renderer shows on gameplay is not correct with config for exist properties (force, important, phase) of renderer ( Example : properties 'Force' of 'Core' has 'editable' = false. But from UI it shows as 'Editable' =true. After update another infors on this properties (ex : Descritpion), gameplay can show correct with properties (Editable from game play is false) . But Update property 'Editable' of 'Turn' to false but gameplay always show as 'Editable' = true


https://github.com/serge-web/serge/assets/107697044/eda5172c-302a-4ec0-8dc6-d1e9b477aa4d

- The exist properties of Core/ MilSym don't get from its properties. (Notice description to know where it gets properties)
Example :
Category, size : gets properties from MilSym
Force, Important, Phase, Turn : gets properties from Core


https://github.com/serge-web/serge/assets/107697044/b2e9e7a0-80c5-4cb6-8bc8-9c5ddcb2da7a

**Comment by IanMayo** [comment]
Thanks @Tristina1788 .  Would you mind re-writing the paragraph that starts with `The renderer shows on gameplay`?  I'm afraid I don't understand the issue.

**Comment by Tristina1788** [comment]
> Thanks @Tristina1788 . Would you mind re-writing the paragraph that starts with `The renderer shows on gameplay`? I'm afraid I don't understand the issue.

@IanMayo  I mean the properties of 'Important' , 'Phase', 'Force', 'Turn' are only enable to get config from admin until user update anything on these properties. With 'Turn' it can get description, label from config after updating, but 'Editable' is always true and don't get value from config. (Example my screencast, notice  'Important' , 'Phase', 'Force', 'Turn' show as these properties are editable until I try to update description of these properties, then back to gameplay, now these properties show correctly with config (Editable = false)) . If you 're still confuse on this, I will give more details.

**Comment by lebaphi** [comment]
> Created new participant and login game play with this user and draw a shape. It will make the exist shape / core are disappeared.

Hi @IanMayo, I've just investigate and found the root cause is that the way we handle messages:
- When we create a new shape on **Green**, it creates a new "Green" message, then when we log in to **Umpire**, we get the latest message in the list to render and it is a "Green" message => it shows nothing because the **Umpire** does not have permission on **Green**, 
image

- In case **Umpire** have permission on **Green**, it only shows the shapes of Green because we get the latest message.
image

What do you think?

**Comment by IanMayo** [comment]
Aah, thanks for debugging that @lebaphi 

@Tristina1788 - could you edit the game (in admin pages) so that the umpire force can see green spatial data and props please?

**Comment by Tristina1788** [comment]
> Aah, thanks for debugging that @lebaphi
> 
> @Tristina1788 - could you edit the game (in admin pages) so that the umpire force can see green spatial data and props please?

@IanMayo @lebaphi Yes, if I added permission umpire force can see green, it will shows green items. But the issue is the exist item of red force, umpire force are lost.

**Comment by lebaphi** [comment]
> @IanMayo @lebaphi Yes, if I added permission umpire force can see green, it will shows green items. But the issue is the exist item of red force, umpire force are lost.

Yep, that is the issue that I said in the 2nd part, because we only get last message in the list to render @IanMayo, you can see it here https://github.com/serge-web/serge/blob/develop/client/src/Components/local/atoms/core-mapping/index.tsx#L141

But the last message does not includes item of red or umpire because this message was created in green force.
image

**Comment by Tristina1788** [comment]
> > @IanMayo @lebaphi Yes, if I added permission umpire force can see green, it will shows green items. But the issue is the exist item of red force, umpire force are lost.
> 
> Yep, that is the issue that I said in the 2nd part, because we only get last message in the list to render @IanMayo, you can see it here https://github.com/serge-web/serge/blob/develop/client/src/Components/local/atoms/core-mapping/index.tsx#L141
> 
> But the last message does not includes item of red or umpire because this message was created in green force. image

@lebaphi , @IanMayo  I think the exist items should be kept. (Example red force create some new items, login from Umpire force, the exist items and new items can be showed)

image

**Comment by lebaphi** [comment]
> > > @IanMayo @lebaphi Yes, if I added permission umpire force can see green, it will shows green items. But the issue is the exist item of red force, umpire force are lost.
> > 
> > 
> > Yep, that is the issue that I said in the 2nd part, because we only get last message in the list to render @IanMayo, you can see it here https://github.com/serge-web/serge/blob/develop/client/src/Components/local/atoms/core-mapping/index.tsx#L141
> > But the last message does not includes item of red or umpire because this message was created in green force. image
> 
> @lebaphi , @IanMayo I think the exist items should be kept. (Example red force create some new items, login from Umpire force, the exist items and new items can be showed)
> 
> image

I think so, I just want to discuss with @IanMayo about the solution.

**Comment by Tristina1788** [comment]
@lebaphi @IanMayo 
- Now the default properties on 'Core'/'Milsym'  are correct with properties from UI. But after updating 'Editable' of MilSym's properties gets from Core, not from 'Milsym'

image

- Enum property don't show the saved value option after saving (Except the option 'Yes'/ 'No')


https://github.com/user-attachments/assets/9e5756f3-90eb-44d3-a0b2-450f24907e22

**Comment by lebaphi** [comment]
> Now the default properties on 'Core'/'Milsym' are correct with properties from UI. But after updating 'Editable' of MilSym's properties gets from Core, not from 'Milsym'

Hi @Tristina1788, to make the field editable, in addition to updating user editable field in Renderer tab, you need to update Edit permission in Participant tab. The field will be disabled if the user does not have Edit permission
image

**Comment by Tristina1788** [comment]
@lebaphi @IanMayo 
- Now the exist items are not removed after login any participants to create new item


https://github.com/user-attachments/assets/53002aed-9ac8-4d20-ae87-9f9d31dc89da



- Properties get correct 'Editable' properties after updating



https://github.com/user-attachments/assets/2521e70b-034c-4980-9561-054cfd011ac7

- Enum property can show the saved value option after saving (Except the option 'Yes'/ 'No') as expected


https://github.com/user-attachments/assets/b3c29ee7-933a-4e57-bcd9-fb1bcfdc696b

- We still have some issue belows : 

+ New properties shows on filter as id of properties instead of label 

image

image

+ After remove properties, this property is still on the exist core/Milsym and show as ID. We should also remove the property on core/Milsym on gameplay.

image

+ User doens't have permission 'View pros', 'Edit/remove Feature',  'Move/resize Feature' still can view pros, edit/remove item, move/resize item 

https://github.com/user-attachments/assets/d6037f7f-39fb-4734-a17c-c95d41c9bb55

+ After updating force 2 times to force which this user don't have permission for 'view partial', the exist items are lost. (User should can't not able to change the force in the second time if it don't have permission 'view partial' or 'Edit Props'


https://github.com/user-attachments/assets/7d9210cb-74a8-4cbb-bcb9-aa8228b0bb25

**Comment by lebaphi** [comment]
> User doens't have permission 'View pros', 'Edit/remove Feature', 'Move/resize Feature' still can view pros, edit/remove item, move/resize item

I think this is an issue of @IanMayo 🤣

**Comment by IanMayo** [comment]
> > User doens't have permission 'View pros', 'Edit/remove Feature', 'Move/resize Feature' still can view pros, edit/remove item, move/resize item
> 
> I think this is an issue of @IanMayo 🤣

Sure @lebaphi - will look at it tomorrow morning

**Comment by lebaphi** [comment]
> > > User doens't have permission 'View pros', 'Edit/remove Feature', 'Move/resize Feature' still can view pros, edit/remove item, move/resize item
> > 
> > 
> > I think this is an issue of @IanMayo 🤣
> 
> Sure @lebaphi - will look at it tomorrow morning

No worries @IanMayo, I fixed it

**Comment by lebaphi** [comment]
> After remove properties, this property is still on the exist core/Milsym and show as ID. We should also remove the property on core/Milsym on gameplay.

When you create a new property and then create a new shape, it will be saved to the database (new shape with new property). Therefore, when you remove that property, "deleted" property still exists in the created shape, the new changes only applies to new shapes.
If you want to fix this behavior, when an admin deletes a property, I think we should look up this property of each feature in the feature collection and then delete it. What do you think @IanMayo

**Comment by IanMayo** [comment]
> > After remove properties, this property is still on the exist core/Milsym and show as ID. We should also remove the property on core/Milsym on gameplay.
> 
> When you create a new property and then create a new shape, it will be saved to the database (new shape with new property). Therefore, when you remove that property, it still exists in the shape as a property. If you want to fix this behavior, when an admin deletes a property, I think we should look up this property of each feature in the feature collection and then delete it. What do you think @IanMayo

Aah, thanks for taking the time to explain that @lebaphi .

There isn't an easy answer.  But, let's separate "game design" from "game play".  The properties are most likely to change during the game design phase before features are added.   Features will only really be created during game play.  I do not believe we have to update/fix existing features to reflect properties being added or removed. The current set of "valid" properties are only observed when creating a new feature.

**Comment by lebaphi** [comment]
> > > After remove properties, this property is still on the exist core/Milsym and show as ID. We should also remove the property on core/Milsym on gameplay.
> > 
> > 
> > When you create a new property and then create a new shape, it will be saved to the database (new shape with new property). Therefore, when you remove that property, it still exists in the shape as a property. If you want to fix this behavior, when an admin deletes a property, I think we should look up this property of each feature in the feature collection and then delete it. What do you think @IanMayo
> 
> Aah, thanks for taking the time to explain that @lebaphi .
> 
> There isn't an easy answer. But, let's separate "game design" from "game play". The properties are most likely to change during the game design phase before features are added. Features will only really be created during game play. I do not believe we have to update/fix existing features to reflect properties being added or removed. The current set of "valid" properties are only observed when creating a new feature.

Thanks @IanMayo, so I think this issue is invalid @Tristina1788

**Comment by Tristina1788** [comment]
@lebaphi @IanMayo Now the tool is missing although this role has all permission

image

image

This is screencast :  


https://github.com/user-attachments/assets/9cbaddc2-2f6a-4ec2-bff5-447528412fcf

**Comment by lebaphi** [comment]
> @lebaphi @IanMayo Now the tool is missing although this role has all permission
> 
> image
> 
> image
> 
> This is screencast :
> 
>  2024-07-16_15-24-20.mp4

I think you need to select an item and the toolbar will update the status @Tristina1788, each item has its own permissions but I think there are some minor issues with this. i.e.: select Red to make the Move button appear, then try moving Green (Green doesn't have Move permission).

**Comment by Tristina1788** [comment]
> > @lebaphi @IanMayo Now the tool is missing although this role has all permission
> > image
> > image
> > This is screencast :
> > 2024-07-16_15-24-20.mp4
> 
> I think you need to select an item and the toolbar will update the status @Tristina1788, each item has its own permissions but I think there are some minor issues with this. i.e.: select Red to make the Move button appear, then try moving Green (Green doesn't have Move permission).

Yes, and how happens if user role don't have any item to select. Example I add Green force has all permission for Green ( no permission with another forcce). So when login with green, no item show to select and I can't create new item for this role. 
And this way it's hard for user know that he can create new item. @IanMayo How do you think?

**Comment by IanMayo** [comment]
> Yes, and how happens if user role don't have any item to select. Example I add Green force has all permission for Green ( no permission with another forcce). So when login with green, no item show to select and I can't create new item for this role. And this way it's hard for user know that he can create new item. @IanMayo How do you think?

Thanks @Tristina1788 - having a go at reproducing it.

**Comment by IanMayo** [comment]
> > Yes, and how happens if user role don't have any item to select. Example I add Green force has all permission for Green ( no permission with another forcce). So when login with green, no item show to select and I can't create new item for this role. And this way it's hard for user know that he can create new item. @IanMayo How do you think?
> 
> Thanks @Tristina1788 - having a go at reproducing it.

Ok, I think I understand it. I've created a new issue to handle it #2996

**Comment by Tristina1788** [comment]
@lebaphi  Yes, we can 'Edit/Remove Feature', 'Move/Resize Feature' although user don't have this permission by this way ` i.e.: select Red to make the Move button appear, then try moving Green (Green doesn't have Move permission).`  . So we should fix it.

- And another issue is the item Core/MilSym always shows although I set config with one of them or none of them

image

image

**Comment by Tristina1788** [comment]
@lebaphi @IanMayo 
- Now the filter properties show correct label instead of ID

image

- User have permission on 'Core' / 'milSym' although I config with only one renderer.

https://github.com/user-attachments/assets/c6d44777-d22f-4aae-b2a3-d3fb96562d76

- Seem the config Url and zoom values are not used. I tried to set with invalid values, but the map in gameplay still shows as normal

image

image

**Comment by Tristina1788** [comment]
@lebaphi I see some conflicts. Please resolve them then I can check it.

**Comment by Tristina1788** [comment]
@lebaphi I got error when run `yarn build`. Please help me check again.

image

**Comment by Tristina1788** [comment]
@lebaphi @IanMayo 
- Now I can't input zoom values to number < 0 (as expected). But I still don't  see our system use URL and Max Native zoom. Can you explain how it work on our system?

image


- User don't have permission with renderer 'Core'  but this user still can update size, move, delete item core. With renderer 'MilSym' , user still can move/ delete without permission. 

https://github.com/user-attachments/assets/7674345b-9923-4a82-b774-87eed189b80d

- New properties of renderer still show ID when adding to 'Filter' although it shows name on properties 's item and 'Add New Item' popup

image

- Now we can't click 'Show Symbol label' icon to see label. We have to click on that icon and also click on item to see label. 

https://github.com/user-attachments/assets/4355d525-f99d-485e-b635-8b018063ca4d

**Comment by lebaphi** [comment]
> But I still don't see our system use URL and Max Native zoom. Can you explain how it work on our system?

Hi @Tristina1788 , URL is Url Template in this link https://leafletjs.com/reference.html#tilelayer, about Max Native Zoom, I think @IanMayo can help 😄

**Comment by IanMayo** [comment]
> > But I still don't see our system use URL and Max Native zoom. Can you explain how it work on our system?
> 
> Hi @Tristina1788 , URL is Url Template in this link https://leafletjs.com/reference.html#tilelayer, about Max Native Zoom, I think @IanMayo can help 😄

@lebaphi -  I'm pretty sure the URL (and maybe maximum zoom) values from the channel should replace these hard-coded values:
image

**Comment by lebaphi** [comment]
> > > But I still don't see our system use URL and Max Native zoom. Can you explain how it work on our system?
> > 
> > 
> > Hi @Tristina1788 , URL is Url Template in this link https://leafletjs.com/reference.html#tilelayer, about Max Native Zoom, I think @IanMayo can help 😄
> 
> @lebaphi - I'm pretty sure the URL (and maybe maximum zoom) values from the channel should replace these hard-coded values: image

Yep, that is what we have:
image

**Comment by IanMayo** [comment]
Great, @lebaphi  - could you take these values from the channel definition instead please?

**Comment by Tristina1788** [comment]
@lebaphi  @IanMayo  

- I can click 'Show Symbol label' icon to see label as expected.

- New property in filter shows label as expected

image

- User still can update properties of item Core / Milsym although the setting doesn't have permission on Core / Milsym


https://github.com/user-attachments/assets/b31f5d3c-64b6-4713-aff5-d8811f5798ad

**Comment by Tristina1788** [comment]
@lebaphi  @IanMayo 
- Try to change some values in Map config and now Core Mapping can get these value for use (I try to update with another url and core mapping can use it) => It works as expected

image

- Now I added 'Umpire' with full permission on 'Umpire', but I can't update properties of Umpire item


https://github.com/user-attachments/assets/2a62318e-d887-48de-b9ec-5cd998a12cf8

**Comment by lebaphi** [comment]
> Now I added 'Umpire' with full permission on 'Umpire', but I can't update properties of Umpire item

Hi @Tristina1788, can you check it again on your side, maybe incognito browser? It seems to work on my side

https://github.com/user-attachments/assets/e2012593-7d97-4a77-9690-387f03e81ebd

**Comment by Tristina1788** [comment]
> > Now I added 'Umpire' with full permission on 'Umpire', but I can't update properties of Umpire item
> 
> Hi @Tristina1788, can you check it again on your side, maybe incognito browser? It seems to work on my side
> 
>  Screen.Recording.2024-07-26.at.8.36.17.PM.mov

@lebaphi I checked on incognitor and the issue still happens. Please uncheck permission for 'Red Force' with 'Move/Resize Feature' = False, 'Edit Pros' = false and check again for Umpire user.

image

**Comment by Tristina1788** [comment]
@lebaphi  @IanMayo I can't update force property 


https://github.com/user-attachments/assets/c0d115a7-7a0d-4e66-a924-f64160a3a33d


Steps:
1. set setting for participants of 'Umpire' role like below

image

2. set setting for enable to update force for 'Core' renderer

image

3. Login user 'Umpire' - Game designer, notice user can't update Force propery of a 'umpire' core shape to 'Red' / 'Blue'

**Comment by Tristina1788** [comment]
@lebaphi  @IanMayo 
-  After updating force 2 times to force which this user don't have permission for 'view partial', the exist items are lost. (User should can't not able to change the force in the second time if it don't have permission 'view partial' or 'Edit Props'` This issue is happened again.
 - Steps: 
 1. Create new participant 'Green' with all permission with green items
 2. Update participant 'Umpire' with all permission with 'Red' and 'Blue'
 3. Login to 'Green' user to create many items
 4. Login to 'Umpire' user to update force of an item (example : Red item)
 5. Update Force property to 'Blue' in first time
 6. Update Force property to 'Umpire' ( Or Green which user don't have permission view item) in second time
 7. Login to 'Green' user, notice all items of this user before are dissapeared

https://github.com/user-attachments/assets/cf057ad6-b9dd-4f78-a654-f804ae7a9ab5

- User can't view properties although he has permission 'View Spartial'

Steps:
1. Update permission for user only has permission  'View Spartial'

image
 
2. Login to the user, try to click item on map or items list on the left to view properties. But user can't see properties of that item.

image

More details on video : 

https://github.com/user-attachments/assets/0667540f-031f-4659-afb3-e2b214092e9f

**Comment by lebaphi** [comment]
> User can't view properties although he has permission 'View Spartial'

HI @Tristina1788, user need to have 'View Props' permission to view the item's properties. Items are only visible on the mapping table when 'View Spatial' permission is set to true

**Comment by Tristina1788** [comment]
> ser need to have 'View Props' permission to view the item's properties. Items are only visible on the mapping table when 'View Spatial' permission is set to true

@lebaphi  @IanMayo  yes, I mean that. But at that time, I 'm wrong the case . Here is the video for that issue. 

https://github.com/user-attachments/assets/54b2c3b1-89d4-48ab-9126-acc09d3cd2fe


Anyway, it's fixed now.

- `After updating force 2 times to force which this user don't have permission for 'view partial', the exist items are lost. (User should can't not able to change the force in the second time if it don't have permission 'view partial' or 'Edit Props'`` => It's also fixed

https://github.com/user-attachments/assets/5f2b6f96-b5be-48c1-99c4-50261b4d39a7

**Review by Tristina1788 — APPROVED** [review]
It works as expected now.

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
