### PR TITLE
Can not sort at 'Last Msg' column on 'Player Logs' table

### LINKED ISSUE #2855: Can not sort at 'Last Msg' column on 'Player Logs' table
## 🐞 Bug description
Can not sort at 'Last Msg' column on 'Player Logs' table

## 🔢 Steps to Reproduce
1. Play game with data wargame-l6nngxlk
2. Click on icon 'Player log'
3. Click 'Sort' icon at 'Last Msg' column 
4.  Notice it direct to white screen

View below screencast for more detail

Note : Issue is also happened with 'Sent at' column
image

## ⚙️ Expected behavior
Enable to sort for 'Last Msg' column and will not direct to white screen

## 🖥️ Screencasts

https://github.com/serge-web/serge/assets/107697044/f8fde8d8-54a9-4a62-b2a6-97e6f227983a

## 💻 System information
- Browser : Chrome
- Browser Version : Version 120.0.6099.111

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #2855

### CODE REVIEW

**Comment by Tristina1788** [comment]
Checking on '2855-sort-player-logs' branch, issue sorting on 'Last Msg' is still happened


https://github.com/serge-web/serge/assets/107697044/06006634-60ce-4800-b6d2-47305839b549

@lebaphi Could you check again?

**Comment by IanMayo** [comment]
Yes, @lebaphi - this is still breaking.  It is breaking because the `sort()` method is receiving a react fragment, which doesn't not support the `toLowerCase()` method.

Here I output the value of `str1` before the `.toLowercase()` method gets called:
image

**Review by IanMayo — APPROVED** [review]

**Comment by Tristina1788** [comment]
> Checking on '2855-sort-player-logs' branch, issue sorting on 'Last Msg' is still happened
> 
>  Can.not.sort.at.Last.Msg.mp4 
> @lebaphi Could you check again?

@IanMayo The issue still happens on my testing.

**Review by IanMayo — CHANGES_REQUESTED** [review]
Ok @lebaphi - it seems this issue is still present:
https://github.com/serge-web/serge/pull/2861#issuecomment-1952179298

**Comment by lebaphi** [comment]
> Ok @lebaphi - it seems this issue is still present: [#2861 (comment)](https://github.com/serge-web/serge/pull/2861#issuecomment-1952179298)

okay, I'm looking on this @IanMayo

**Comment by Tristina1788** [comment]
@lebaphi @IanMayo Now I can sort column  on 'Player Logs' without issue

https://github.com/serge-web/serge/assets/107697044/839c022d-32e5-497b-8d5b-daa44327df81

**Comment by Tristina1788** [comment]
@IanMayo I think it was done. Should we merge to develop and close it?

**Pull request merged**
