### PR TITLE
1109: When reading a Collaborative Working document I would like to see all text

### LINKED ISSUE #1109: When reading a Collaborative Working document I would like to see all text
The JSON-Editor control shows text-area blocks with a scroll-bar.

This means people viewing the document have to use scroll-bars to view large blocks of text.

It would be better if the whole paragraph was displayed

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1109

### CODE REVIEW

**Comment by IanMayo** [comment]
We have an empty/unused area at the bottom of large text blocks:
image

**Comment by lebaphi** [comment]
> We have an empty/unused area at the bottom of large text blocks:
> image



> We have an empty/unused area at the bottom of large text blocks:
> image

Yep I see it @IanMayo, I can get all the texterea elements then set height for each one but I found the json editor provides an option to do that thing at https://github.com/json-editor/json-editor#editor-options, `expand_height`. So I decide to use the built-in options instead of handling it manual.

**Comment by IanMayo** [comment]
Sorry @lebaphi  - were you suggesting another strategy, or explaining what you did?

Are you able to remove that extra vertical space?

**Comment by lebaphi** [comment]
> Sorry @lebaphi - were you suggesting another strategy, or explaining what you did?
> 
> Are you able to remove that extra vertical space?

Hi @IanMayo, I just explain we have 2 ways to do this, first one is handle it by javascript, and he second one is using the built-in option. So I choose the second one but we got an issue of the space. So let me try with the first one, it may not "official" but the result will be the same to what we did when adding the prop `fitContent` to the TextArea component.

**Comment by IanMayo** [comment]
Good strategy - thanks :-)

I wonder if we're doing some styling that is _breaking_ the `expand height` in json-editor.

**Comment by lebaphi** [comment]
> Good strategy - thanks :-)
> 
> I wonder if we're doing some styling that is _breaking_ the `expand height` in json-editor.

I think nope, because we just try to set the height of only the textarea element like the built-in option does. But we will test it careful before release, so no worries :)

**Comment by lebaphi** [comment]
Hi @IanMayo, I updated with the first approach, handle by javascript
image

**Review by IanMayo — CHANGES_REQUESTED** [review]
I don't see them in your screenshots, but on the `deployment` version scroll-bars still appears to the right of tall text-areas.
I _guess_ we can remove them with CSS when we're in `read-only` mode.

**Comment by lebaphi** [comment]
> I don't see them in your screenshots, but on the `deployment` version scroll-bars still appears to the right of tall text-areas.
> I _guess_ we can remove them with CSS when we're in `read-only` mode.

weird, did you try to clear cache?

**Comment by IanMayo** [comment]
I get the below screenshot on this branch:
https://serge-1109-whole-paragr-3yzivh.herokuapp.com/?wargame=wargame-kskl1i3t&access=pkskl17tha

image

**Comment by lebaphi** [comment]
> I get the below screenshot on this branch:
> https://serge-1109-whole-paragr-3yzivh.herokuapp.com/?wargame=wargame-kskl1i3t&access=pkskl17tha
> 
> image

ah I know why lol, the height fit the content but need more a bit to get the scrollbar gone.

**Comment by lebaphi** [comment]
scrollbar disappears @IanMayo 👍

**Review by IanMayo — APPROVED** [review]
Working fine.

**Pull request merged**
