### PR TITLE
Update git actions for pkg-build

### LINKED ISSUE #730: Generate executables in build process
It would make it easier for third parties to test/review Serge if they were able to download an executable from PRs.

We have a workflow for Pull Requests:
https://github.com/serge-web/serge/blob/develop/.github/workflows/pull-request.yml

We have a build command to produce executables for 3 operating systems `yarn pkg-build`.

We should extend the workflow to build the executables, and to attach them to the PR.

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #730

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks @lebaphi - what does this file do? 
`packages/server/img/.gitkeep`

**Comment by lebaphi** [comment]
> Thanks @lebaphi - what does this file do?
> `packages/server/img/.gitkeep`

Hi @IanMayo , I see in `server.js` has this line `app.use('/img', express.static(path.join(__dirname, './img')))` but there is no folder `img` -> show an error when running `yarn pkg-build`. I create an `img` folder and add `.gitkeep` file to allow to upload an empty folder to this repo :D

**Review by IanMayo — DISMISSED** [review]
Looks good - we'll have to merge it to see it working :-)

**Comment by IanMayo** [comment]
Aah, @lebaphi  - it looks like it is putting all of the builds into a single `zip-file`:
image

Yes, here is the contents of the zip:
image

**Comment by lebaphi** [comment]
> Aah, @lebaphi - it looks like it is putting all of the builds into a single `zip-file`:
> image
> 
> Yes, here is the contents of the zip:
> image

Yep @IanMayo, do you want it put 3 files separate?

**Comment by IanMayo** [comment]
yes please, so a reviewer can download the zip for their system.

**Comment by lebaphi** [comment]
> yes please, so a reviewer can download the zip for their system.

okay, I will update soon 👍🏻

**Comment by lebaphi** [comment]
> yes please, so a reviewer can download the zip for their system.

Hi @IanMayo , updated.

**Pull request merged**
