### PR TITLE
Feature/mapping test forces list

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
## 🧰 Issue

In Process #355 

## 🔗 Link to preview

https://serge-review-feature-ma-brfio1.herokuapp.com/storybook/?path=/story/local-mapping--with-assets

## 🔨Work carried out:

- [x] Tests pass

## 🖥️ Screenshot

изображение
изображение

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Comment by lilitkarapetyan** [comment]
изображение

**Comment by lilitkarapetyan** [comment]
Left to do small corrections and finish color radio buttons section, and all sections will be ready to use

**Comment by IanMayo** [comment]
Nearly there @lilitkarapetyan 

There is some formatting that I can't fix, some of the text goes black:
screen cast

**Review by IanMayo — APPROVED** [review]
Nicely done.

**Comment by IanMayo** [comment]
There is a subtle change in Celine's UX for the forces list.  The color of the "own platforms" vertical tab is now the blue shade we use for the Plan Turn form, and the color of the "other forces" vertical is the dark-grey shade used for Perceived Asset form.

**Pull request merged**
