### PR TITLE
2837 show id field

### LINKED ISSUE #2837: Should not shows 'Filter' for properties which not shows on 'Properties' of item
## 🐞 Bug description
Should not shows 'Filter' for properties which not shows on 'Properties' of item

## 🔢 Steps to Reproduce
1. Play game with data wargame-l6nngxlk
2. Click on channel 'Core Mapping'
3. Filter with 'ID' 
4. Notice no properties ID on item, but it still gets result for filter 'ID'

image

## ⚙️ Expected behavior
Filter should only show properties which shows on 'Properties' panel

## 💻 System information
 - Browser : Chrome
 - Browser Version : Version 120.0.6099.111

### PR DESCRIPTION
**Pull request by IanMayo**
## 🧰 Issue

Fixes #2837 

## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Comment by Tristina1788** [comment]
@IanMayo  Checking on this branch . ID field in 'Properties' pannel is showed as disabled now (It's good for that) but filter 'ID' should not disable. So that user can filter with 'ID'.

image

**Comment by IanMayo** [comment]
> @IanMayo Checking on this branch . ID field in 'Properties' pannel is showed as disabled now (It's good for that) but filter 'ID' should not disable. So that user can filter with 'ID'.
> 

well spotted @Tristina1788

**Comment by IanMayo** [comment]
I've messed up merging this branch @Tristina1788  - but could you give it a check anyway?  (on `develop`).

**Comment by Tristina1788** [comment]
> I've messed up merging this branch @Tristina1788 - but could you give it a check anyway? (on `develop`).

I've checked on branch 'develop'. And it works as expected now.

**Pull request merged**
