### PR TITLE
Allow_tiles_to_be_pulled_from_data_folde

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Review by IanMayo — COMMENTED** [review]
Good, neat piece of code, thanks @lilitkarapetyan 

Will test tomorrow.

**Comment by IanMayo** [comment]
Hello @lilitkarapetyan - I'm going to test this.

Can you tell me where I put the folder of tiles?

The unpacked executable has these folders:
```
- root
-- executable-xx
-- node_sqlite3.node
-- serge
--- data
--- db
--- img
```

When I look at the server handler, it looks like it is going up a folder `../` then down into `data`.  That would mean the tiles should go into a folder call `data` that sits in the `root` folder in the above tree.

**Comment by lilitkarapetyan** [comment]
> 



> Hello @lilitkarapetyan - I'm going to test this.
> 
> Can you tell me where I put the folder of tiles?
> 
> The unpacked executable has these folders:
> 
> ```
> - root
> -- executable-xx
> -- node_sqlite3.node
> -- serge
> --- data
> --- db
> --- img
> ```
> 
> When I look at the server handler, it looks like it is going up a folder `../` then down into `data`. That would mean the tiles should go into a folder call `data` that sits in the `root` folder in the above tree.

I am working on it now

**Comment by IanMayo** [comment]
> 
> I am working on it now

Aaah, I think I've found out, by experimentation.  The tile-folder just goes in the current `data` folder.  That's neat :-)

**Comment by lilitkarapetyan** [comment]
> > I am working on it now
> 
> Aaah, I think I've found out, by experimentation. The tile-folder just goes in the current `data` folder. That's neat :-)

place the `tiles `folder in the `data ` folder if you want to test

**Review by IanMayo — APPROVED** [review]
Tested & working

**Pull request merged**
