### PR TITLE
2805 Items are created after delete by 'Cut Layers'

### LINKED ISSUE #2805: Items are created after delete by 'Cut Layers'
## 🐞 Bug description
Items are created after delete by 'Cut Layers' 

## 🔢 Steps to Reproduce
1. Play game with data wargame-l6nngxlk
2. Click on channel 'Core Mapping'
3. Click on action 'Cut Layers'
4. Draw the cut line to cut some layers
5. Notice these items are deleted on map
6. Draw layer to create new one item
7. Notice the items (from step 5) are showed on map

More details from below screencast

## ⚙️ Expected behavior
Items are not recreated after delete by 'Cut Layers' 

## 🖥️ Screencasts

https://github.com/serge-web/serge/assets/107697044/acb0dd81-d7a0-48c1-b391-fa11b010dcee

## 💻 System information
 - Browser : Chrome
 - Browser Version : Version 120.0.6099.111

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #2805

### CODE REVIEW

**Comment by IanMayo** [comment]
Hmmm, @lebaphi .  I hadn't used this way of deleting items before.  But, I note that while shapes get deleted mil-symbols don't.  Could you look in to that please?

**Comment by Tristina1788** [comment]
Checked on branch '2805-cut-layer-issue', now 'Cut Layers' can't cut multi layers as before. @lebaphi  Could you check again?


https://github.com/serge-web/serge/assets/107697044/d411c56b-84e8-4c4f-af1c-9792516b50c3

Sorry for wrong screencast before. I've updated it.

**Comment by Tristina1788** [comment]
Checked on branch '2805-cut-layer-issue'.  'Cut Layers' can cut multi items but it can't cut circle layers. @lebaphi Please help me check the screencast.

https://github.com/serge-web/serge/assets/107697044/46f5f06d-5f25-40d2-a940-5a2df42aa6e9

**Comment by lebaphi** [comment]
> Hmmm, @lebaphi . I hadn't used this way of deleting items before. But, I note that while shapes get deleted mil-symbols don't. Could you look in to that please?

Hi @IanMayo, I've checked in this url https://www.geoman.io/demo and it has the same behavior. So I think this is the behavior of Geoman.

**Comment by lebaphi** [comment]
Hi @Tristina1788, I pushed the fixes, can you help to verify it again 😄

**Comment by IanMayo** [comment]
Hello @lebaphi - I've just had a play, and the issue is still present.  

Sometimes after an item has been deleted, it re-appears when a new item has been added.  Or, I'm unable to add new items.

Can you try to recognise the pattern @Tristina1788 , and provide a recording of what you see?

**Comment by IanMayo** [comment]
> Hi @IanMayo, I've checked in this url https://www.geoman.io/demo and it has the same behavior. So I think this is the behavior of Geoman.

Yes, you are completely right @lebaphi 

I have captured the issue here: https://github.com/geoman-io/leaflet-geoman/issues/1452

**Comment by Tristina1788** [comment]
> a new item has been added. Or, I'm unable to add new items.

@lebaphi  @IanMayo , now 'Cut Layers' can cut circle items. But after that, some layers (from second layers which are cut) are blinked. Here 's the screencast 

https://github.com/serge-web/serge/assets/107697044/09c69f39-a29f-44b8-8921-f1972de22d38

@IanMayo I tried more than 5 times but I can add new items after 'Cut Layers' / 'Remove Layers' 

https://github.com/serge-web/serge/assets/107697044/741c1cbb-3291-4bd1-8a2a-7bb7a0b96bf3

**Comment by lebaphi** [comment]
Hi @Tristina1788, when you cut, Geoman will remove many items at once, which will cause the data to be saved to the database asynchronously. To solve this problem, I put all the pending deleted items into the queue and deleted them one by one, that's why you see it blinked

**Comment by IanMayo** [comment]
Well, @lebaphi  and @Tristina1788 - the GeoMan didn't see it as a bug report, but as a feature request.  I wasn't expecting that:
https://github.com/geoman-io/leaflet-geoman/issues/1452#issuecomment-1936225607

_Sometime_ I'll have a look at the GeoMan code, and see if I can produce a PR.

Aah, @lebaphi - the _tidy_ way to handle this is to remove the `cutLayers` button, please.  We can reinstate it if/when GeoMan either fix the issue, or we implement it ourselves.

**Comment by Tristina1788** [comment]
Now the 'Cut layers' button is removed as expected.

image

**Comment by Tristina1788** [comment]
@IanMayo  In this PR, we remove 'Cut Layer' button in Core mapping tool. So now it works as expected. I think we can close the ticket. 

image

**Review by IanMayo — APPROVED** [review]
Tested and working

**Pull request merged**
