### PR TITLE
1216: Do not show a popup when deleting node

### PR DESCRIPTION
**Pull request by lebaphi**
Fixws #1216

### CODE REVIEW

**Review by IanMayo — DISMISSED** [review]
Seems fine.

**Review by ShendMikullovci — CHANGES_REQUESTED** [review]
The pop-up is still there in the deployment. I tried it with Senior Blue and it appeared same as the first time.

**Comment by lebaphi** [comment]
> The pop-up is still there in the deployment. I tried it with Senior Blue and it appeared same as the first time.

Can you tried https://serge-1216-popup-replac-ze9c0a.herokuapp.com/?wargame=wargame-kskl1i3t&access=pkskl17tha, Blue 5, `Add Europe` and `Delete Europe`, the popup does not appear in my side.

**Comment by IanMayo** [comment]
Hello @lebaphi - I don't see the popup.

Could you also modify the options so we don't have the "Delete Last ..." button please? It doesn't make sense in this context.

image

**Comment by ShendMikullovci** [comment]
> > The pop-up is still there in the deployment. I tried it with Senior Blue and it appeared same as the first time.
> 
> Can you tried https://serge-1216-popup-replac-ze9c0a.herokuapp.com/?wargame=wargame-kskl1i3t&access=pkskl17tha, Blue 5, `Add Europe` and `Delete Europe`, the popup does not appear in my side.

It still appeared. And the "Delete Last Europe" remains on the tab after Europe is deleted.

**Comment by IanMayo** [comment]
Hmm, I'm not getting it popup:
screencast

Could you do a "hard-reset" (probably something like ctrl-f5) and try again please @ShendMikullovci ?

Aah, the `last row` button is still there because @lebaphi hasn't made any changes since I made that request.

**Comment by ShendMikullovci** [comment]
Yes, this one is fine (except the small Delete Last Europe bug). However, the pop-up shows up in the New Message tab for COAs (before they are sent out).

**Comment by lebaphi** [comment]
I've updated for both issues (remove last delete button and disable popup in new mail form). But I see in `New Message` form, there is only `Delete Last...' button. What do you think? @IanMayo @ShendMikullovci

**Comment by IanMayo** [comment]
Aah, yes - is that json-editor in a different component?

**Comment by lebaphi** [comment]
> Aah, yes - is that json-editor in a different component?

yep, so I decide to keep the button `Delete last...` because this form does not have the `Delete...` button :D

**Comment by ShendMikullovci** [comment]
The pop-up doesn't appear anymore on the New COAs nor on released ones. Thanks, @lebaphi !

The "Delete Last" button still appears on the screen after deleting last Europe/Asia:
Delete Last Europe - Asia

**Comment by lebaphi** [comment]
> The pop-up doesn't appear anymore on the New COAs nor on released ones. Thanks, @lebaphi !
> 
> The "Delete Last" button still appears on the screen after deleting last Europe/Asia: Delete Last Europe - Asia

Hi @ShendMikullovci, I have seen this but the button is handled by json editor library. we can't re implement its instead using the options they provide

**Review by IanMayo — APPROVED** [review]
Approving, since the important aspects of the issue have been resolved.

Will solve remaining problem(s) in fresh issues & PRs

**Pull request merged**
