### PR TITLE
Add SpellCheck for the TextArea element

### LINKED ISSUE #904: Spell-check
## 💬 Brief description of feature
Spell-check in text widgets.

## 📖 User Story
As a **Player** I want my **content to be spell-checked** in order to **avoid misinterpretation and not look a fool**.

## ☑️ Acceptance criteria

* mis-spellings shown in free text boxes (single-line and multi-line `textarea` widgets)
* player can ignore some mis-spellings
* user can add new words to dictionary
* has to be able to run without Internet connection, so word-list needs to be stored in app

Nice to have:
* Game Designer can provide additional extra dictionary of words

## 📐 Designs / Wireframes

Spell-checking in free text seems quite mature in browsers now.  I don't know if it's native in browsers, or via 3rd party libs.  It's unfortunate that we need a version that runs without an Internet connection, but that's an unavoidable constraint.

## 📝 Notes

I'd quite like to be involved in any decisions about which 3rd party Open Source lib we use for this, if it can't happen natively in the browser.

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #904 

- Add this attribute to the `textarea` element to handle spell check
- JSONEditor handle it automatically

### CODE REVIEW

**Comment by IanMayo** [comment]
Hey, @lebaphi - I can't believe how easy that was 🤣 

But, for it to work in our formatted (template-based) editors we'll have to inject it into the form produced by `json-editor`. Could you also attempt to do that too, please?

Note: @sanjayradadiya manipulated the `json-editor` form to introduce date-time editors in #940. Your code _could_ fit in with his code to _walk_ the DOM.

**Comment by lebaphi** [comment]
> But, for it to work in our formatted (template-based) editors we'll have to inject it into the form produced by `json-editor`. Could you also attempt to do that too, please?

Hi @IanMayo , I tested in the form produced by `json-editor`, it seems the JSON Editor handled it already 🤔 
Screen Shot 2021-08-16 at 10 15 20 PM
Screen Shot 2021-08-16 at 10 15 26 PM

**Comment by IanMayo** [comment]
Great. In that case could produce a list of the components that use `text-area` - and we can decide which ones should get spell-checking?

(off the top of my head we have Game Admin, Feedback, Chat, Private-Message add-ons.  Oh, plus the `Overview` sections of the Game Admin pages)

**Comment by lebaphi** [comment]
> Great. In that case could produce a list of the components that use `text-area` - and we can decide which ones should get spell-checking?
> 
> (off the top of my head we have Game Admin, Feedback, Chat, Private-Message add-ons. Oh, plus the `Overview` sections of the Game Admin pages)

let me check 😉

**Comment by IanMayo** [comment]
Hmm, this is strange. I've opened this old branch, and we have spell-check in all 4 text boxes I typed into:
https://serge-854-fix-deprecate-xj2ts4.herokuapp.com/?wargame=wargame-kqgy546g&access=pkoiqu5ev

image

**Comment by lebaphi** [comment]
> Hmm, this is strange. I've opened this old branch, and we have spell-check in all 4 text boxes I typed into:
> https://serge-854-fix-deprecate-xj2ts4.herokuapp.com/?wargame=wargame-kqgy546g&access=pkoiqu5ev
> 
> image

yep, I think only the Private message is `textarea`, the rest is div and it was manipulated by JSON Editor with the spell-chck enabled

**Comment by lebaphi** [comment]
I just do some search and found that components that using the `textarea`:
- MessageCreator: line 217 (Private messages)
- Textarea: line 25

**Comment by IanMayo** [comment]
This is a deployment from `develop`.  I can't find a text area that _doesn't_ have spell-check working:
https://serge-review.herokuapp.com/

I'm not sure what made the clients come up with the requirement.

**Comment by IanMayo** [comment]
Ok, closing this issue.  The underlying issue is the Chrome is using an Internet service for spell-check.

Our Serge players don't have an Internet connection - that's why spell-check isn't provided.  We need a different strategy than using the browser-default strategy.

**Pull request closed without merging**
