### PR TITLE
2871 prep for long comments

### LINKED ISSUE #2871: Allow longer properties to be defined (textarea)
We could allow more descriptive content associated with map symbols if the Game Designer was able to specify that a property would require a text area.

We already have `StringProperty`

We could extend it to include a `lines?: number` attribute. This would indicate how many vertical lines to assign to the text box.

### PR DESCRIPTION
**Pull request by IanMayo**
Fixes #2871 

Note: this PR includes modified data in Serge app and `Storybook` to show an `Orders` property for Military-Symbol features on the map.

### CODE REVIEW

**Comment by IanMayo** [comment]
i'd appreciate you having a look at the code in this PR, please @lebaphi

**Comment by Tristina1788** [comment]
@lebaphi , @IanMayo  Tested on '2871_prep_for_long_comments , now I can see the property 'Orders' as text Area field. We can extend this field by drag bottom right corner.

image

image


- But I don't see this property on new map symbol item.


https://github.com/serge-web/serge/assets/107697044/87d7c150-1e00-4b90-b17a-475f62377112

**Review by Tristina1788 — DISMISSED** [review]
@IanMayo Tested on '2871_prep_for_long_comments', now new  map symbol item can has new property 'Orders' . And this field works as expected

image

**Comment by IanMayo** [comment]
Hmm, I'm not sure about that sentence being there 3 times @Tristina1788 ('today's orders for this unit`) .  Did you just copy/paste that?

**Comment by Tristina1788** [comment]
> Hmm, I'm not sure about that sentence being there 3 times @Tristina1788 ('today's orders for this unit`) . Did you just copy/paste that?

@IanMayo   I copy/paste and only show that to says it can shows the text with many lines :) . It works as expected.

**Comment by IanMayo** [comment]
@Tristina1788 - I had to fix a few merge conflicts on this, it could do with re-testing, please.

**Comment by Tristina1788** [comment]
> @Tristina1788 - I had to fix a few merge conflicts on this, it could do with re-testing, please.

@IanMayo  It works as expected as before.


https://github.com/serge-web/serge/assets/107697044/3017a4d7-526d-4609-ae51-7815f4a90759

**Review by Tristina1788 — APPROVED** [review]
It works fine.

**Pull request merged**
