### PR TITLE
[serge-155] Add login bypass

### LINKED ISSUE #155: Infrastructure - easily switch off hard-coded Game & Player at login
As a < developer >, I want < to optionally skip the login process > so that < login is shorter in dev, but not in test >.

The e2e acceptance tests are failing because of the steps we took to do a quick login (skip welcome page, hard-code wargame & user).

That means we aren't getting the 'reassurance' from the e2e tests. Note: we're not getting complete value from them anyway - since this phase is focussed on mapping, and they don't test the mapping control. But, they do give us assurance that the build/compile/deploy steps are working properly.

So, at a developer level (prob in code, _maybe_ in a consts file, _maybe_ in the `.env` file, _maybe_ specify them in the URL) we should be able to quickly switch on and off short-circuiting the login process.

Note: in the `develop` branch, the `PlayerUiLobby.js` class currently contains hard-coded wargame and pass-code details.  In that branch, the `PlayerUI.jsx` page also comments out the `PlayerUiLandingScreen` page.

Note 2: also, in the above develop branch, we still have to click on `wargame` to activate the roles, before the `Enter` button is activated.  Ideally, if the constants are set (or the URL params present) the user will travel directly into the wargame.

Note 3: actually, specifying the params in the URL would bring other benefits - it would allow us to give a stakeholder a URL that gets them straight into a game without having to think about the login process, or for when the Login Roles are hidden.  _If_ we go down the URL params route, I suggest the params are titled `wargame` and `access`.

# Acceptance criteria

- [x] A developer can control the wargame and pass-code used in the login page. When these are present, the welcome screen is skipps
- [x] When above settings not assigned, the game does the usual login/startup process

# UX
Nil - this is a source-code level change.
# Notes

### PR DESCRIPTION
**Pull request by zukilover**
## 🧰 Ticket
Closes #155 

## 🚀 Overview: 
Add login bypass using URL parameters

## 🤔 Reason: 
As a < developer >, I want < to optionally skip the login process > so that < login is shorter in dev, but not in test >.

## 🔨Work carried out:
- [x] Tests pass
- [x] Add login byPass method on playerUi.jsx

## 📝 Developer Notes:
Bypass works by adding `wargame` and `access` parameters, i.e.: `?wargame=<wargame_code>&access=<access_code>`
[Infrastructure - easily switch off hard-coded Game & Player at login](https://app.gitkraken.com/glo/board/XZIuhoko5QAPaF0f/card/Xh8IfujfHAAQlvrg)

### CODE REVIEW

**Comment by IanMayo** [comment]
@foxleigh81 - I'd like you to have a look at this, please. It certainly works for me.  I see the e2e is now failing. It _looks like_ this is because I've renamed 'white' force to 'White'. I'll research it further.

**Review by IanMayo — DISMISSED** [review]
A great piece of work. I wish we'd done this weeks ago :-D

**Comment by IanMayo** [comment]
Another one to look at, please @foxleigh81 .

**Comment by foxleigh81** [comment]
> Another one to look at, please @foxleigh81 .

All good. Could use more comments but otherwise it looks great!

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
