### PR TITLE
Feature/150 unit test example

### LINKED ISSUE #150: Infrastructure - example of unit test for Helper classes
As a < developer >, I want < to practice TDD > so that < I can progress without compile/debug loop, and leave tests behind >.

For some of the logic I'm working on, it's a pain to select the game, login as the role, and configure the data - particularly if the function under development has no UI elements.

I would be able to work more quickly if TDD unit tests covered the function under development.

Some modules contain a single function, such as `colorFor` in `colorFor.js`.  Other modules contain multiple functions that I'd like to be able to test, such as `plannedModePopupFor` in `MapPlanningPlayerListener.js`

# Acceptance criteria

- [x] New test class present, that can drive the unit-test of a method in a helper class
- [ ] Working practice (steps) for how to call just that class from the command line

Ideally, the test would auto-run on code change.

### PR DESCRIPTION
**Pull request by foxleigh81**
## 🧰 Ticket
Closes #150 

## 🚀 Overview: 
Created a few tests to show examples of how to write unit tests for the current infrastructure

## 🔨Work carried out:

- [x] Wrote a unit test for the `colorFor` method
- [x] Split `plannedModePopupFor` from its class and wrote a test for that too
- [x] Created a fake example class called `ExampleHelperClass`
- [x] Wrote a set of tests for `ExampleHelperClass`

## 📝 Developer Notes:
- To run all unit tests, run `yarn test:unit` from the root of the project
- To run a specific test, specify the path to that test: e.g. `yarn test:unit packages/client/src/Tests/helpers/ExampleHelperClass.test.js`

By default, `yarn test:unit` will automatically watch for changes to files, this means if you write your tests first, you will immediately see when the code you have written has passed or failed the requirements by looking at the console output

### CODE REVIEW

**Comment by IanMayo** [comment]
Yes, brilliant - just what I was hoping for :-)

**Comment by IanMayo** [comment]
Aah, but @foxleigh81  - I'd like to merge it, to pull in the new testing libs.  But we don't want to pull in the unrelated example code, do we?

**Comment by IanMayo** [comment]
Hmm, on reflection I'm ok with keeping the examples in, they're useful examples of how to mock and to interact with the console.  Ok?

**Comment by foxleigh81** [comment]
> Hmm, on reflection I'm ok with keeping the examples in, they're useful examples of how to mock and to interact with the console. Ok?

Yup, they don't touch any other part of the codebase, however, we'll want to delete them eventually as it's an extra test which doesn't need to run.

**Review by IanMayo — APPROVED** [review]
Great - just what I was hoping for

**Pull request merged**
