### PR TITLE
Fix Serge failing to open on port 3000

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Review by IanMayo — DISMISSED** [review]

**Comment by IanMayo** [comment]
Hello @lilitkarapetyan - I've pulled the branch, done `yarn install`, `yarn build`,  `rm -rf packages/components/build`, and `yarn dev`, but I still get runtime errors:
image

**Comment by lilitkarapetyan** [comment]
> 

If you pulled from my branch, there's no need to delete the build folder. Simply run `yarn(install)`, `yarn build` followed by `yarn dev` and you shouldn't encounter any errors - https://gyazo.com/9a2b8ae48b1fe382241b48d0b2c8ac2d

**Comment by IanMayo** [comment]
> > 
> 
> If you pulled from my branch, there's no need to delete the build folder. Simply run `yarn(install)`, `yarn build` followed by `yarn dev` and you shouldn't encounter any errors - https://gyazo.com/9a2b8ae48b1fe382241b48d0b2c8ac2d

I still get build errors: https://i.gyazo.com/8fc2fcefc7fb2e7e99938b265cbc8cfc.mp4

**Comment by lilitkarapetyan** [comment]
> > > 
> > 
> > 
> > If you pulled from my branch, there's no need to delete the build folder. Simply run `yarn(install)`, `yarn build` followed by `yarn dev` and you shouldn't encounter any errors - https://gyazo.com/9a2b8ae48b1fe382241b48d0b2c8ac2d
> 
> I still get build errors: https://i.gyazo.com/8fc2fcefc7fb2e7e99938b265cbc8cfc.mp4

Have you tried running the commands 'yarn cache clean' or 'rm -r node_modules ?

**Comment by lilitkarapetyan** [comment]
Okay, I performed some tests and encountered the issue again.

**Comment by IanMayo** [comment]
Still have the runtime failure, I'm afraid:
image

**Comment by IanMayo** [comment]
Close. Overtaken by move to monolith.

**Pull request closed without merging**
