### PR TITLE
1246 Delete Platform Type

### LINKED ISSUE #1246: Can't delete Platform from the Admin Page
There's no delete button once a user creates a platform on the admin page.
Can't delete platform

I would assume it's important to be able to delete a platform from the game if necessary.

I suggest we stick to feature we use the channel delete feature (next to the channel title there's a delete button next to the duplicate button): 
Channel Delete Feature

Let me know what you all think.

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1246 

Hi @IanMayo @ShendMikullovci , please have a look on the demo below:

https://user-images.githubusercontent.com/26705621/151181607-0b3e975c-b69b-43d8-8d48-b0ef2788ce14.mov

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks @lebaphi - but I'm afraid we need confirmation on delete. The Game Designer may have put a lot of effort into a designing a platform-type, so we don't want to lose that investment of time by accident.

**Comment by ShendMikullovci** [comment]
Looks excellent @lebaphi. As for the confirmation, I suppose a simple pop-up asking "Are you sure you want to permanently delete this asset?" would do.

**Comment by lebaphi** [comment]
Hi @IanMayo @ShendMikullovci plz take a 👀 

Screen Shot 2022-01-27 at 9 45 53 AM

**Review by IanMayo — APPROVED** [review]

**Comment by ShendMikullovci** [comment]
> Hi @IanMayo @ShendMikullovci plz take a eyes
> 
> Screen Shot 2022-01-27 at 9 45 53 AM

Excellent! Thanks @lebaphi! Can you just put the delete button on the right, and the cancel button on the left please?

**Comment by ShendMikullovci** [comment]
Update: The button doesn't seem to be working for me.

https://user-images.githubusercontent.com/85491794/151559298-439d7bb3-9b0c-418e-8126-fdd1f6d1746a.mp4

**Comment by lebaphi** [comment]
Hi @ShendMikullovci, I think you should `Save` the platform first then you can `Delete` it 😄

**Comment by ShendMikullovci** [comment]
> Hi @ShendMikullovci, I think you should `Save` the platform first then you can `Delete` it smile

My bad. All good.

**Comment by IanMayo** [comment]
It does seem a problem that a newly created platform-type can't be deleted.

It's not intuitive that a player must save the item before deleting it.  I guess the newly created platform-type is inconsistent in some way.  @lebaphi - could you investigate the issue please?

 If a Game Designer accidentally creates two rather than one, he can't delete either of them until they have been saved.  Actually -  if multiple ones are created, i _think_ that deleting one deletes all of them.  
 
 screencast

**Comment by ShendMikullovci** [comment]
> It does seem a problem that a newly created platform-type can't be deleted.
> 
> It's not intuitive that a player must save the item before deleting it. I guess the newly created platform-type is inconsistent in some way. @lebaphi - could you investigate the issue please?
> 
> If a Game Designer accidentally creates two rather than one, he can't delete either of them until they have been saved. Actually - if multiple ones are created, i _think_ that deleting one deletes all of them.
> 
> screencast

While I agree it would be easier to have the platform saved automatically, we could also have a pop-up asking whether the user is sure they want to delete, similar to other features we introduced it to.

**Pull request merged**
