### PR TITLE
Fixed an issue where changing the SCSS file did not recompile the project

### PR DESCRIPTION
**Pull request by lebaphi**

### CODE REVIEW

**Comment by IanMayo** [comment]
thanks @lebaphi 

Can you explain why the import path has changed?

**Comment by IanMayo** [comment]
> thanks @lebaphi
> 
> Can you explain why the import path has changed?

Aah, @lebaphi - the path change seems to have broken the build:
image

**Comment by lebaphi** [comment]
> > thanks @lebaphi
> > Can you explain why the import path has changed?
> 
> Aah, @lebaphi - the path change seems to have broken the build:
> image
no worries Ian, Im working on this 😁

**Comment by lebaphi** [comment]
> thanks @lebaphi
> 
> Can you explain why the import path has changed?

Hi Ian, when running the `yarn develop`, it starts the client package and references all files in the `components/build` location. So I run the `tsc --watch` in the component package to recompile once all the ts/tsx files changed -> reload the client. But it does not watch the SCSS file, so I add the node-sass-chokidar to do the same thing as `tsc --watch` but for style files. The issue is the node-sass-chokidar does not support a path like `@import "~@serge/...."` in the style.module.scss, that is why I change the import path. It will work for build, test-unit, and recompile. Since the project structure is a bit different, this is the only solution I can find now.

**Comment by IanMayo** [comment]
Hi, I have `forces-in-channel\styles.module.scss`.

I have `yarn develop` running in a terminal window.

I've changed `border-radius` of `role-icon` to 10%, which should make it almost square.

But, when I save, nothing happens in the terminal window.

Hmm, if I change code in `forces-in-channel\index.jsx` it doesn't recompile either.

Ok, I've switched back & forward between this branch and `develop` a couple of times.  Changes to `.jsx` but not `.scss` triggers recompile in `develop`.  Neither file type triggers rebuild on `yarn develop` on this branch.

**Comment by lebaphi** [comment]
> Hi, I have `forces-in-channel\styles.module.scss`.
> 
> I have `yarn develop` running in a terminal window.
> 
> I've changed `border-radius` of `role-icon` to 10%, which should make it almost square.
> 
> But, when I save, nothing happens in the terminal window.
> 
> Hmm, if I change code in `forces-in-channel\index.jsx` it doesn't recompile either.
> 
> Ok, I've switched back & forward between this branch and `develop` a couple of times. Changes to `.jsx` but not `.scss` triggers recompile in `develop`. Neither file type triggers rebuild on `yarn develop` on this branch.

you need to run yarn install and yarn build again I think :D

**Comment by IanMayo** [comment]
Aah great - thanks @lebaphi

**Review by IanMayo — APPROVED** [review]
Working fine.

**Pull request merged**
