### PR TITLE
Add_pouchdb_server

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Comment by lilitkarapetyan** [comment]
1. Installation - `npm install -g pouchdb-server`

**Comment by lilitkarapetyan** [comment]
2. Usage:
After installing PouchDB Server, you can start the server and access your PouchDB database through a web interface. Follow the steps below to run PouchDB Server and access your database.

Open a terminal or command prompt.

Navigate to the directory where PouchDB Server project is located. For example:

`cd @serge/server:`

**Comment by lilitkarapetyan** [comment]
3. Run the following command to start the server:

`yarn run pouchdb-sqllite`

**Comment by lilitkarapetyan** [comment]
This command will start the PouchDB Server and enable you to access your database through a web interface at `http://localhost:5984/_utils/`.

**Comment by lilitkarapetyan** [comment]
You can now create and manage `PouchDB ` databases using the web interface.

**Comment by IanMayo** [comment]
Thanks for that @lilitkarapetyan . Do you think it's feasible for us to switch to using `pouchdb-server` as our whole backend for Serge?

**Comment by lilitkarapetyan** [comment]
Hello @IanMayo, I think is feasible Switching to `PouchDB Server` as our whole backend for Serge. 

The `PouchDB server` provides a RESTful API that allows you to interact with `PouchDB` databases, including those stored in `SQLite`. It also provides a web interface for managing databases and supports various storage systems, including` LevelDB`, `SQLite`, and `CouchDB`.

**Comment by lilitkarapetyan** [comment]
here are some limitation of `pouchdb server`

1. No support for sharding: PouchDB-server is designed to be a single-server solution, which means it cannot handle large datasets that require sharding across multiple servers.

2. Limited scalability: While PouchDB-server can handle a moderate amount of data, it may struggle to scale beyond a certain point, making it less suitable for large-scale applications.

3. No built-in security features: PouchDB-server does not come with built-in security features, such as authentication and authorization, which can leave your data vulnerable to attacks.

4. No automatic backup and recovery: PouchDB-server does not have a built-in mechanism for automatic backup and recovery, which means you'll need to set up your own backup and recovery strategy.

5. Limited query capabilities: While PouchDB-server does support basic query functionality, it is not as powerful as other databases, which may make it less suitable for applications that require complex querying.

Limited query support: PouchDB Server uses MapReduce indexing, which may be limiting compared to traditional relational databases in terms of querying capabilities. Complex queries may be difficult to implement and may require add

**Review by IanMayo — CHANGES_REQUESTED** [review]
Thanks @lilitkarapetyan - but it's this string that should be a const, please:
```
js/bundle-34997e32896293a1fa5d71f79eb1b4f7.js
```

So, if/when the bundle gets updated, we just change it in one place.

**Comment by IanMayo** [comment]
@lilitkarapetyan - codacy is complaining about an escape in the Regex.  But, I think we should stick with the original code, and include a comment to suppress `no-useless-escape` for that block of code.

image

**Comment by IanMayo** [comment]
Thanks for this Lilit. 

Could we have a Button in the Admin page to open the Fauxton UI?  We would get a new `Database` link on the left-hand menu here:
image

**Comment by lilitkarapetyan** [comment]
> Thanks for this Lilit.
> 
> Could we have a Button in the Admin page to open the Fauxton UI? We would get a new `Database` link on the left-hand menu here: image

Hello @IanMayo , yes I will work on it.

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
