### PR TITLE
1635: General chat redesign

### LINKED ISSUE #1635: General Chat Redesign
I thought of redesigning the general chat, since we've encountered multiple issues in implementing new features (main menu button #1609), bugs (#1619), or improving UI for current features (#1580). 

Came up with this: 

New General Chat Opened

The title of the wargame at the top on the right hand side, accompanied by user's role and force. On the left of the label, the force icon. 
Objectives would appear by clicking on the Force icon, similarly to our current layout. The difference here would be:

1. Bottom of the screen is reserved for messaging (both on the left hand side for channels, and for the right hand side for chatting), as we are used to in most messaging apps.
2. It reinforces the Z pattern that our layouts try to encourage: 

Z Pattern Example

Here, the user would naturally encounter information following the usual Left-Right, Top-Bottom route.

Home button, would be added next to the Insights, Player Log and Intro buttons. 
The Turn and Phase information also gain importance and centrality here, considering they are crucial info for GC. The action button in light blue against a white background for clarity and presence. 

Furthermore, the chat would become collapsible to give GC the ability to reduce information load: In a busy game, it would be harmful for GC to be distracted by messages from the right hand side, especially if they are redundant. 
The tabs remain similar, with the exception of their appearance: they look like Google Chrome tabs. My girlfriend accidentally stumbled upon an open SERGE Screen and asked me what she was looking at. She then let me know that Insights/Game Admin didn't look like tabs at all. I realized she might be right...
The "Mark All Read" button gets replaced by our usual envelope to maintain uniformity and consistency. All of this gives the chat a much more "chat"-y feel. 

When collapsed, it would look like this: 

Reducing information load dramatically and giving a clean look. GC would still have a marker on the chat to remind them of accumulating messages on the chat bar at the bottom right.

Expanded, it would look like this: 

General Chat Expanded

Here, GC can view older messages without having to scroll upwards. If messaging is important or task-specific, the user can expand the chat to increase focus. Bold text and message chip for new, unseen messages, that remains bold for a specific time.

I think this would improve game flow, all the while solving some issues we've encountered concerning our current UI.
Let me know what you think.

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1635 

image

### CODE REVIEW

**Comment by IanMayo** [comment]
Nicely done @lebaphi 

1. The icon next to the `wargame title` is an `exit` button - which should take the player back to the `select game` / `select role` view, please.
2. I think we can get rid of the horizontal line beneath the wargame title.  The block below is in a different colour, so we already know they're different elements.

**Comment by lebaphi** [comment]
I've updated @IanMayo

**Comment by IanMayo** [comment]
Thanks @lebaphi 

One more item. There's an extra "Planning" in the turn panel:
image

Aaah, hold on, that's not the issue.  I realise what @ShendMikullovci intended.  The box should contain the two words "Planning" and "Adjudication".   The "current" one will be shown in highlight, and the other darker.  So, if you play as "White - Game Control", you can click on "Start next phase" and the panel will cycle between the two states.

**Comment by ShendMikullovci** [comment]
Hi guys! Looks much smoother already. Couple of things: 

1. The screen seems to be outlined now: 

Outline

I'm not sure if this effect was intended. Kind of gave me the feeling that I was sharing the screen on Zoom or like my screen was being recorded. 

2. The features on the right hand side seem to be very tightly joined together: 

Space

The area in red is quite squeezed in while the area in orange occupies too much unnecessary space. We could gain quite a bit of space by shrinking the chat length and redistributing the features, spacing them out and giving them some more leg room.

3. Start New Phase button could do in light blue, to attract attention as key button for this screen.
4. The tabs could do a better job depicting their function if they were squared onto the chat itself. Nothing too fancy, simply making them the same size as the chat box. It could look something like this: 

Chat Tabs

5. The Read/Unread button seems to only be marking messages as read, but not unread.

**Comment by IanMayo** [comment]
1. Well spotted @ShendMikullovci - I hadn't seen that.   @lebaphi - there is a thin grey line around the edge of the app (left side in following screenshot):
new border
2. You are on a tall screen.  In the past 2 wargames, players have sat in a meeting room, all looking at a projector version on a screen.  The projectors available are quite low resolution - so Serge really fills the screen. That is partly why the "out-of-game" component is so narrow.  The only way for Serge to work on a low resolution is to squash the controls together, but let other controls expand to fill the remaining space.
3. `Start new phase`.  Only the Game Control sees this button.  If it was lighter, it would lose contrast, since the letters are white, and the background is white.  Is there a precedent for a light-blue button anywhere else in the app?  Another option is to use a larger text.
4. Yes, I see your point. I guess they don't have to exactly fill the space, but the left-hand of "Insights" should certainly align with the left of the panel.  So, IMHO the right-hand of the tabs doesn't have to align - since we don't do that in the "in-game" messages:
image
5. Yes, well spotted. Could you record this as a separate issue please, it's something that was already broken, and doesn't relate to these UI updates.

**Comment by lebaphi** [comment]
@IanMayo @ShendMikullovci , for the issue 5, I only see the button `Mark All As Read`, that's why we only have one icon to mark all message as read.

image

**Comment by IanMayo** [comment]
Hello @lebaphi - one more item:
https://github.com/serge-web/serge/pull/1674#issuecomment-1185625824

**Comment by ShendMikullovci** [comment]
> 3. `Start new phase`.  Only the Game Control sees this button.  If it was lighter, it would lose contrast, since the letters are white, and the background is white.  Is there a precedent for a light-blue button anywhere else in the app?  Another option is to use a larger text.

Oh, my bad. The blue I'm referring to is the one I used in the latest designs of #991 ("Save Overview" button), #1400 ("Start New Phase" button), etc. It's HEX is 1A65D7. It doesn't lose contrast in white (actually ends up popping out more) and it doesn't blend in with our dark blue backgrounds. 

> 4. Yes, I see your point. I guess they don't have to exactly fill the space, but the left-hand of "Insights" should certainly align with the left of the panel.  So, IMHO the right-hand of the tabs doesn't have to align - since we don't do that in the "in-game" messages:
>    image

I understand. However, the general chat tabs and in-game channel tabs are two different features that serve very different purposes. They've also been clearly presented as different (through the intro steps), which is why a different display logic would apply to each. That's why I think it's important to treat the chat as such.

**Comment by ShendMikullovci** [comment]
> @IanMayo @ShendMikullovci , for the issue 5, I only see the button `Mark All As Read`, that's why we only have one icon to mark all message as read.
> 
> image

I'll include animations for buttons that have double-use from now on.

**Comment by ShendMikullovci** [comment]
> > @IanMayo @ShendMikullovci , for the issue 5, I only see the button `Mark All As Read`, that's why we only have one icon to mark all message as read.
> > image
> 
> I'll include animations for buttons that have double-use from now on.

Here's the animation for that @lebaphi :
https://user-images.githubusercontent.com/85491794/179865778-2c033009-4ba4-4692-889e-5ee54eeb02cb.mp4

As you can see, hitting on the "Mark Read" button removes the notification counter and the bold effect on the messages. Hitting on "Mark Unread" brings back the counter and the bold effect.

**Comment by IanMayo** [comment]
Nice work, thanks @lebaphi 

I _think_ we should de-highlight the "not current phase" label.  The current one is larger, but I the non-current one is the same size & color as the "Phase" label.  IMHO it should be 50% transparent, or something like that...

What do you think @ShendMikullovci ?
screencase

**Comment by lebaphi** [comment]
I've updated @IanMayo 
Screen Shot 2022-07-20 at 8 19 53 PM
Screen Shot 2022-07-20 at 8 22 26 PM

**Comment by IanMayo** [comment]
Hi @lebaphi - I'm just testing new phase presentation.

It looks good. But, I have a minor vertical alignment issue with this wargame:
image


I _guess_ the `h3` and the `fontawesomeicon` need to be vertically aligned in the middle of the parent box.

**Comment by IanMayo** [comment]
Oh dear @ShendMikullovci - I think I've just come up with a scary issue.

`START NEW PHASE` is below 3 buttons and above 2 tab buttons.  A bad mouse click for any of them could accidentally trigger a step to a new phase - throwing away routes currently being planned.

But, if we move the button to above the "turn marker" box, it's only near to the "return to welcome page" button - which isn't expected to be used very often at all.  Aah, or we could put it back inside the "turn marker" box. If it was above the "Current time" label, there is a "buffer" between the 3 action buttons and the next step button.

image

Note: if we do put "next phase" button inside "turn marker" box, we'll need a different shade.  @ShendMikullovci has already suggested shade to use:
image

**Comment by IanMayo** [comment]
After endless linter fixes, I've pushed a version with "Start Next Phase" back inside the Turn Progression box:

image

So, @lebaphi - I think the only remaining issue is the "Welcome page" icon alignment: https://github.com/serge-web/serge/pull/1674#issuecomment-1190347468

**Comment by ShendMikullovci** [comment]
Thanks guys! 

Love the dimming of the inactive phase. The button inside the box works as well, helps us avoid that accident hopefully. 

Couple of things I wanted to address: 

1. Could we have rounder corners for the action buttons please? It smoothes out the entire look and makes them look more like actual buttons. 
2. I also noticed the button reacts by changing colors upon hover. I don't think that's necessary. A simple dropshadow could do the trick as well:

https://user-images.githubusercontent.com/85491794/180098662-5cdb98ef-d224-4273-bbb6-2d04db25007c.mp4

3. The turn box could do with some rounder corners as well and the same color as the "Game Admin" chat tab. Now that I think of it, why did we settle on the turn box not covering the width of the chat? @lebaphi could be right by putting an outline between the chat and the screen and we might have rushed our hand telling him to remove it...

Essentially, the right hand side has had two main issues regarding visibility: It blends in with the screen (unless we use bright colors) and it blends with itself (chat blends in with upper features/buttons). This latter issue is even more important because the chat and the features that happen to be above it are actually completely unrelated. By placing an outline, we make that dichotomy: 

New Screen

Here, the time box (+ features) and the chat are visibly separate from the channels (which maintains our conscious intent on separating them). But more importantly, the time box (+ features) and the chat are _visibly separate from each other_. Our current display doesn't really emphasize that. In this design, every element takes up its adequate spot and is equally visible (I feel like?). The reason why I left the 3 buttons outside of the box (namely, Feedback, Player Log and Intro) is because we want to avoid the user accidentally clicking Start New Phase. This visual separation reduces that risk. What do you guys think?

**Comment by IanMayo** [comment]
> Rounder corners

Yes please @lebaphi - let's have rounder corners for the whole "turn progression" box, and the "Start new phase" button.

> I also noticed the button reacts by changing colors upon hover. I don't think that's necessary. A simple dropshadow could do the trick as well:

I've just done some investigating.  I didn't think we had hover action on any other buttons, but it seems most of the `Submit` buttons do change color on hover (I think it's a standard shading that comes with our Material UI toolkit).  The hover shadow is probably too subtle for many Serge users.  So, I think it's right to stick with the hover - we've just got to find the right color.

@ShendMikullovci - there is a gap between the bottom of `Game Admin` and the `New admin message` box.  I don't think this is right, since the `new admin message` box is a part of `Game Admin` - and it's not present for the `Insights` tab.

**Review by IanMayo — APPROVED** [review]
Couple of outstanding items, but will handle these as separate issues.

**Comment by ShendMikullovci** [comment]
> @ShendMikullovci - there is a gap between the bottom of `Game Admin` and the `New admin message` box. I don't think this is right, since the `new admin message` box is a part of `Game Admin` - and it's not present for the `Insights` tab.

Hi Ian! You're right. That's because the tabs lack the curvature to make them visually connected to the chat. My bad, lost focus on that. Here we go: 

Rounded + Connected tabs

**Comment by ShendMikullovci** [comment]
This got me thinking about the design for the player end. They don't have access to an insights tab, so how would the chat look for them? 

Couple of ideas: 

Chat Looks for Players

Tab look: The tab is expanded to fit accross the chat window, with the side curvature included. One problem with this is that you can argue that essentially, it's not a tab, since there's no other tabs next to it. Instead, it's more of a header. 

Header 1: Same size without curvature on the bottom placed in the same spot on the X/Y axis. 

Header 2: Larger size (to touch the top of the chat) placed in the same spot on the X/Y axis. For Header 1 and 2 you can argue that the color is inappropriate, since for GC we use the navy blue to indicate the opened tab (which has been clicked on). Players' side doesn't present the option to click (since there's no Insights or other tab to click on).

Header 3: Same as Header 2, except white. Problem here is that it would be laying on top of a white background. Tried a grey one and it's just plain ugly.

We could also go with a no-tab look: 

No Tab Chat

1st one only has a long underline, similar to the title of a wargame in the admin pages. The 2nd one only underlines the title of the chat. 

Let me know what you guys think!

**Comment by IanMayo** [comment]
Hello @ShendMikullovci - thanks for considering this.

Right now, the single-tab issue isn't a great worry.  There _may_ be games where the player is only a member of one channel - so there will only be one tab on the left-hand side.  That's not an issue.

My issue with your designs above remains.  The "new message" box has to be a _child_ of the `Game Admin` component. That's because it isn't present when viewing `Game Insights`.  So, there should not be a space between the list of messages Game Admin messages and the new message box.  The box will not be present for "Insights".

The current layout suggests the new message box isn't directly related to "Game Admin" messages.

**Comment by ShendMikullovci** [comment]
Oh! Something like this you mean?: 

Chat Message Without Box

**Comment by IanMayo** [comment]
Yes - that solves the issue.

**Pull request merged**
