### PR TITLE
1306: Icon Uniformity Mapping

### LINKED ISSUE #1306: Icon Uniformity Mapping
We present square icons in the asset menu on the mapping page: 

Stick to Circles Instead of Squares for Logo Uniformity

It's the only page to my knowledge where we present square icons. 
We should stick to circular icons to maintain force icon uniformity.

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1306 

Hi @ShendMikullovci @IanMayo 

image

### CODE REVIEW

**Comment by ShendMikullovci** [comment]
Hi guys! The screenshot looks good but the deployment link sends me to Papafoxtrot.

**Comment by IanMayo** [comment]
> Hi guys! The screenshot looks good but the deployment link sends me to Papafoxtrot.

Sure. The issue is there there is only one game visible - so Serge takes us directly into that game.

So, here's how you can get around the issue:
- log into admin
- change `CmdWk-High data` to be visible ("Show wargame" in context menu)
- delete last bit of URL, to go back to Serge home page
- click on "Play"
- Select `CmdWk - High data` game
- log in as Game Control
- click on a platform, to view visibility panel

**Review by IanMayo — APPROVED** [review]

**Comment by IanMayo** [comment]
Merging, it's a minor fix.

**Comment by ShendMikullovci** [comment]
> > Hi guys! The screenshot looks good but the deployment link sends me to Papafoxtrot.
> 
> Sure. The issue is there there is only one game visible - so Serge takes us directly into that game.
> 
> So, here's how you can get around the issue:
> 
> * log into admin
> * change `CmdWk-High data` to be visible ("Show wargame" in context menu)
> * delete last bit of URL, to go back to Serge home page
> * click on "Play"
> * Select `CmdWk - High data` game
> * log in as Game Control
> * click on a platform, to view visibility panel

It worked. The icons are still squares though:

Mapping Screenshot

**Comment by IanMayo** [comment]
Ok, in this branch I see circular icons.  
image

I'll merge it, and hopefully @ShendMikullovci  will find the circular icons in the main serge-review branch.

**Pull request merged**
