### PR TITLE
1428: Update toggle color issue

### LINKED ISSUE #1428: Off VS Disabled Toggles
We should be able to distinguish between toggles that have been turned OFF versus toggles that are DISABLED.

For example: 

https://user-images.githubusercontent.com/85491794/158644620-3f4b5156-b8ba-4baa-b606-e253ad12b2a7.mp4

The toggles before clicking on the edit pen, should be dimmed grey and unresponsive to mouse hovers to emphasize their disabled quality, irrespective of their OFF/ON status. Once the edit pen has been clicked on, they regain their color.

Here's some examples: 

TOGGLE OFF/ON ENABLED:

Toggle Off
Toggle On

TOGGLE OFF/ON DISABLED: 

Disabled Toggle Off
Disabled Toggle On

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1428 

https://user-images.githubusercontent.com/26705621/159475513-73744286-027f-41b0-bb70-a7c1b856ef64.mov

### CODE REVIEW

**Comment by IanMayo** [comment]
@lebaphi - it looks like the video didn't upload properly. Could you try again please?

**Comment by lebaphi** [comment]
> @lebaphi - do you understand what the warning meant?
> 
> image

Hi @IanMayo, the `wargameApi.clearWargames()` return a void, not a promise so we don't need to use `await` 😄

**Comment by IanMayo** [comment]
> Hi @IanMayo, the `wargameApi.clearWargames()` return a void, not a promise so we don't need to use `await` 😄

Aah, thanks for the lesson :-)

**Review by IanMayo — APPROVED** [review]
Tested on Heroku

**Comment by ShendMikullovci** [comment]
Looks great @lebaphi!

**Pull request merged**
