### PR TITLE
Feature/#507

### LINKED ISSUE #507: Update adjudicate form - Phase 1
We have a working Adjudicate Form, using Components:
image

It should be updated to the new UX:
image

More screenshots [here](https://www.figma.com/file/2qiEitO08s8jXamHWI3VpP/SERGE-mapping-tool?node-id=710%3A2547)

### PR DESCRIPTION
**Pull request by foxleigh81**
## 🧰 Issue
Closes #507 

## 🚀 Overview: 
Updated Adjudicate Turn Form to conform with Figma designs

## 🤔 Reason: 
Placeholder design is not appropriate for the production site

## 🔨Work carried out:

- [x] Updated AdjudicateTurnForm component
- [x] Updated Storybook
- [x] Tests pass

## 🖥️ Screenshot

Screenshot 2020-10-06 at 18 07 45

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have assigned myself to this PR.
- [x] I have chosen an appropriate label for the PR.
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.
- [x] I confirm that I have checked for required README updates and acted accordingly.

## 📝 Developer Notes:
- I've not updated the force selector to look exactly like the design. The reason being that this is a significant change and I seem to recall a discussion a long time ago about leaving it the way it is. If this isn't the case then I recommend a new ticket to update that component (it isn't only used here so make sure you want it changing everywhere)
- There was already a fancy new `speed` component so I have used that instead of creating a new one, I notice that the style doesn't quite match the Figma designs but I presume that is intentional.

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks for this @foxleigh81 .   That was quick!

There's an issue with Rejecting a planned route.  After clicking "Reject" it's possible to change the speed, but not the state:
screenshot

You can get to a playable instance of this via this URL: 
https://serge-review-feature-50-z9vzpp.herokuapp.com/?wargame=wargame-k5xxsr4b&access=p2311

You can add that suffix to your local dev server if you need to.

The problem also occurs in the `StoryBook`, but a rendering issue that's local to StoryBook means the radio buttons aren't very legible.

**Comment by IanMayo** [comment]
Aah, it's also not possible to edit the Visibility:
screenshot

Nor the condition checkbox.

**Comment by foxleigh81** [comment]
> Aah, it's also not possible to edit the Visibility:
> screenshot
> 
> Nor the condition checkbox.

That's odd. I didn't change those sections. I must have missed something when I was porting over the `FormGroup` component (which is excellent, btw so kudos to whoever introduced that). I'll take a look today.

**Comment by IanMayo** [comment]
Sorry @foxleigh81 , if it was broken in the previous UI, then it's unfair to hold back this issue because of that issue. I'll investigate tomorrow morning.

**Comment by clenoble** [comment]
@foxleigh81 @IanMayo I recommend using white for selected buttons rather than red. Red color usually indicates an issue which is not the case here. 
I would recommend updating the design of the speed selector to match Figma.

**Comment by IanMayo** [comment]
Thanks for that @clenoble 

I'll move the speed-graph to a separate issue: https://github.com/serge-web/serge/issues/522

But, @foxleigh81 - I'd appreciate you switching the selected item to **White** from **Red**.

**Comment by foxleigh81** [comment]
> Thanks for that @clenoble
> 
> I'll move the speed-graph to a separate issue: #522
> 
> But, @foxleigh81 - I'd appreciate you switching the selected item to **White** from **Red**.

Those radio buttons and checkboxes come straight from Material UI. Which means that they will appear like that all over the place. I'd advise creating a task for someone to go through and create a Material UI override stylesheet so all MUI default styles can be brought in-line with @clenoble's designs.

**Comment by IanMayo** [comment]
Aah, @foxleigh81 - I hadn't appreciated that.  

@clenoble - here's a screenshot of the `standard` look & feel:
image

More examples here:
https://material-ui.com/components/checkboxes/

The material UI theme includes lots of red - including for URLs. 

Yes, I'll create an issue to cover investigating over-riding the default primary highight color (I _guess_ that's what it is).  But, if it's too painful I'm afraid we'll have to live with it in the short term).

**Review by IanMayo — APPROVED** [review]
Happy to accept PR. Will handle frozen controls in another PR.  Keen to merge since I need to make some further changes to Adjudicating Form.

**Comment by clenoble** [comment]
@IanMayo The guidance given in this Material UI page does not concern the specific colors. They just use red as their primary color and blue as their secondary color, but these need to be adjusted according to the specific theme used.

**Comment by IanMayo** [comment]
Hello @clenoble - yes, we need to override the default Material UI theme.

Issue captured here: https://github.com/serge-web/serge/issues/527

**Pull request merged**
