### PR TITLE
1521: Add SVGInjection

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1521

Details here https://github.com/iconfu/svg-inject

### CODE REVIEW

**Comment by IanMayo** [comment]
Hello, @lebaphi  - did you consider this modification?
https://github.com/serge-web/serge/pull/1521#issuecomment-1105140570

**Comment by lebaphi** [comment]
> Hello, @lebaphi - did you consider this modification? [#1521 (comment)](https://github.com/serge-web/serge/pull/1521#issuecomment-1105140570)

Hi @IanMayo, yep I found another solution, using sprite file, details https://fontawesome.com/v5/docs/web/advanced/svg-sprites.
So for this one, we need to combine all SVG files to 1 sprite file -> place this file into the public folder.
I'm trying this :D

**Comment by IanMayo** [comment]
> > Hello, @lebaphi - did you consider this modification? [#1521 (comment)](https://github.com/serge-web/serge/pull/1521#issuecomment-1105140570)
> 
> Hi @IanMayo, yep I found another solution, using sprite file, details https://fontawesome.com/v5/docs/web/advanced/svg-sprites. So for this one, we need to combine all SVG files to 1 sprite file -> place this file into the public folder. I'm trying this :D

Sorry, I don't think this will work. The Game Designer has to be able to provide new icons at runtime.

**Comment by lebaphi** [comment]
> > > Hello, @lebaphi - did you consider this modification? [#1521 (comment)](https://github.com/serge-web/serge/pull/1521#issuecomment-1105140570)
> > 
> > 
> > Hi @IanMayo, yep I found another solution, using sprite file, details https://fontawesome.com/v5/docs/web/advanced/svg-sprites. So for this one, we need to combine all SVG files to 1 sprite file -> place this file into the public folder. I'm trying this :D
> 
> Sorry, I don't think this will work. The Game Designer has to be able to provide new icons at runtime.

ok so we need to load these icons at runtime -> as far as i know we can just load SVG file via its url in `` or `<object...>` tag but we can't create style it except using DOM manipulation
Use the SVG Inject library to transform the `` element with an inline SVG, then we can style it via SCSS.

**Comment by IanMayo** [comment]
> > > > Hello, @lebaphi - did you consider this modification? [#1521 (comment)](https://github.com/serge-web/serge/pull/1521#issuecomment-1105140570)
> > > 
> > > 
> > > Hi @IanMayo, yep I found another solution, using sprite file, details https://fontawesome.com/v5/docs/web/advanced/svg-sprites. So for this one, we need to combine all SVG files to 1 sprite file -> place this file into the public folder. I'm trying this :D
> > 
> > 
> > Sorry, I don't think this will work. The Game Designer has to be able to provide new icons at runtime.
> 
> ok so we need to load these icons at runtime -> as far as i know we can just load SVG file via its url in `` or `<object...>` tag but we can't create style it except using DOM manipulation Use the SVG Inject library to transform the `` element with an inline SVG, then we can style it via SCSS.

I'm just double-checking here. If the SVG doesn't have a color, won't it take the `fore-color` from CSS?  It's easy to remove the color from the SVG.

**Comment by IanMayo** [comment]
Hello @lebaphi  - [this](https://onestepcode.com/leaflet-markers-svg-icons/) article appears to cover how to perform CSS styling of SVG icons.

**Comment by lebaphi** [comment]
> Hello @lebaphi  - [this](https://onestepcode.com/leaflet-markers-svg-icons/) article appears to cover how to perform CSS styling of SVG icons.

well, this article is using the svg code:
image

We only have the svg url, Im not sure that we can fetch and retrieve the content of the svg file 🤔 let me try this.

**Comment by lebaphi** [comment]
Hi @IanMayo, I updated with new solution 👍

**Comment by IanMayo** [comment]
Sorry @lebaphi - I see that in the tutorial they are using named styles for the colors. We can't use that. We have to specify the color at run-time (since the Game Designer may come up with their own set of shades)

**Comment by IanMayo** [comment]
Closing. @lebaphi came up with another solution in another PR.

**Pull request closed without merging**
