### PR TITLE
1345: Add Info Card Component

### LINKED ISSUE #1345: Component for "More info available" text span
There are lots of occasions when we need to provide supporting/background information to a player (or even Game Designer in the admin pages).

We currently support this via tooltips, but it's cumbersome for a player to hover over all screen elements in the hope of finding tooltips.

I don't know if this is possible, but it would be great if we could have a modified span control that includes a small info marker (fa-circle-info) at the top-right.   Clicking on the question mark pops up the explanatory guidance.  I guess we should allow for up to 30 words.

I'm thinking of a span control since the text is currently just displayed as plain text - so switching to a `span` shouldn't cause any layout problems.

I guess the control would also have these props:
- icon color (so it can stand out from background)
- description text

We should develop this a StoryBook component that has a range of values for the above, including short and long descriptions.

Aah, hold on. There are also occasions when we wish to indicate that an icon has "more info" available.  So, I guess we also need an extended font-awesome icon that can have its own more-info icon at the top-right.

So, we'd be able to provide `more-info` for the `Password` and `Game control` column headers.

image

An early use of this would be the

### PR DESCRIPTION
**Pull request by lebaphi**
Fixed #1345

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks @lebaphi - could you provide stories that show how the more-info is added to a block of text or an icon.

I'm _hoping_ our implementation means we can have something like this:
```
<MoreInfo description="The percentage fuel remaining">Fuel</MoreInfo>

<MoreInfo description="Whether this player can edit this commodity">
  <FontAwesomeIcon icon='fa-user-cog'/>
</MoreInfo>
```

I think the _current_ implementation means the the icon is declared immediately after the text/icon it relates to.  But, I want it to "steal" some of the area from the text/icon it relates to - to "tie" them together.    If that's possible by declaring it afterwards, then that's ok.

One last thing. Could the cursor please change to a question mark (or info marker) as it goes over the icon please?

**Comment by IanMayo** [comment]
Great progress.  But,  the "i" icon is missing in StoryBook: 
image

It;s the "i" icon that is indicates to the user that further help is availalble.

Note: I don't need the dialog to switch between text and long text.  In the issue, I was just suggesting that you provide multiple storybook examples - so we could see one example with short text, and another with long text.

I'd also like to see an example of an icon that has its own "more info" icon.

**Comment by IanMayo** [comment]
Sorry @lebaphi  - the `i` in the info icon is too small for me to see:
image

**Comment by lebaphi** [comment]
> <MoreInfo description="Whether this player can edit this commodity">
>   <FontAwesomeIcon icon='fa-user-cog'/>
> </MoreInfo>

no worries, I will make it bigger 🤣

**Comment by lebaphi** [comment]
Hi @IanMayo , I just push the code to increase the size of the icon info, you can change its value accordingly as your view 😄 

image

**Comment by IanMayo** [comment]
Thanks @lebaphi 

Can you teach me why you wrap the component in `React.memo()`?

image

**Comment by lebaphi** [comment]
> Thanks @lebaphi
> 
> Can you teach me why you wrap the component in `React.memo()`?
> 
> image

Hi @IanMayo, using `React.memo(...)` to memoize functional components, it prevents useless re-renderings when the next props equal to previous ones to improve the performance.

**Comment by IanMayo** [comment]
> Hi @IanMayo, using `React.memo(...)` to memoize functional components, it prevents useless re-renderings when the next props equal to previous ones to improve the performance.

Aah, ok - I've done some googling, and found an [article](https://dmitripavlutin.com/use-react-memo-wisely/). The MoreInfo component doesn't occur very often, and doesn't take long to render.  The channels full of formatted messages take _ages_ to re-render.  I _get_ the use of memo there - I can't say I'm _fully convinced_ here ;-)

**Review by IanMayo — DISMISSED** [review]

**Comment by IanMayo** [comment]
Hello @ShendMikullovci - could you have a look at this please.  Just select a platform-type to see the `more-info` markers: 
https://serge-1345-info-card-co-uya9qi.herokuapp.com/storybook/?path=/story/local-organisms-settingplatformtypes--default

I've temporarily made the markers a more red color. Is there a more subdued color that you would prefer?

**Comment by lebaphi** [comment]
> > Hi @IanMayo, using `React.memo(...)` to memoize functional components, it prevents useless re-renderings when the next props equal to previous ones to improve the performance.
> 
> Aah, ok - I've done some googling, and found an [article](https://dmitripavlutin.com/use-react-memo-wisely/). The MoreInfo component doesn't occur very often, and doesn't take long to render. The channels full of formatted messages take _ages_ to re-render. I _get_ the use of memo there - I can't say I'm _fully convinced_ here ;-)

yes, you're are right. One component is insignificant but if many components are like that then I think in the long run it will not be good. So I think this is a good habit.

**Comment by ShendMikullovci** [comment]
> Hello @ShendMikullovci - could you have a look at this please. Just select a platform-type to see the `more-info` markers: https://serge-1345-info-card-co-uya9qi.herokuapp.com/storybook/?path=/story/local-organisms-settingplatformtypes--default
> 
> I've temporarily made the markers a more red color. Is there a more subdued color that you would prefer?

Like we discussed over in Slack, we could try having them outlined rather than filled in. I'd say we could do with the icons being a little smaller too, so they don't attract as much attention as they do. Otherwise, it's a great addition!

**Comment by IanMayo** [comment]
Hello @lebaphi - could you have a go at changing the style of the info icon please?

@ShendMikullovci has asked that it be outlined.  So, we would see the outline of the circle, with the solid `i` in the middle.  I ***guess*** this is just about switching the foreground and background colors.

**Comment by lebaphi** [comment]
> Hello @lebaphi - could you have a go at changing the style of the info icon please?
> 
> @ShendMikullovci has asked that it be outlined. So, we would see the outline of the circle, with the solid `i` in the middle. I _**guess**_ this is just about switching the foreground and background colors.

Sure @IanMayo , I will fix it now.

**Comment by lebaphi** [comment]
outlined icon @IanMayo @ShendMikullovci:

Screen Shot 2022-02-17 at 6 31 45 PM

**Comment by IanMayo** [comment]
> outlined icon @IanMayo @ShendMikullovci:
> 
> Screen Shot 2022-02-17 at 6 31 45 PM

Well that was easy :-)

Could you also provide an optional color field please?  I'm pretty sure we'll need that to ensure it's visible on light and dark backgrounds.

**Comment by lebaphi** [comment]
> > outlined icon @IanMayo @ShendMikullovci:
> > Screen Shot 2022-02-17 at 6 31 45 PM
> 
> Well that was easy :-)
> 
> Could you also provide an optional color field please? I'm pretty sure we'll need that to ensure it's visible on light and dark backgrounds.

@IanMayo Do you think we should provide only `color` field or provide a `style` field then we can customize more property?

**Comment by IanMayo** [comment]
Can we start off with just color please?

**Comment by ShendMikullovci** [comment]
> outlined icon @IanMayo @ShendMikullovci:
> 
> Screen Shot 2022-02-17 at 6 31 45 PM

Hi @lebaphi. It looks great from the screenshot. If you could make it slightly smaller so it doesn't attract immediate attention then it'd be perfect.

**Comment by lebaphi** [comment]
okay @IanMayo, I will update soon

**Comment by IanMayo** [comment]
> okay @IanMayo, I will update soon

I've got it, @lebaphi  :-D

**Review by IanMayo — DISMISSED** [review]

**Comment by lebaphi** [comment]
> > okay @IanMayo, I will update soon
> 
> I've got it, @lebaphi :-D

Your change looks good 👍

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
