### PR TITLE
2705_Editor_for_SIDC_codes

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Review by IanMayo — COMMENTED** [review]
Thanks @lilitkarapetyan - that's just the kind of thing I was hoping for.
1. I presume you still have to generate the drop-downs for the other fields.  I _think_ the next levels start to introduce some dependencies.
2. Instead of the wide `Open SIDC generator` button, could it just be an square button with an `Edit` icon to the right of the text field please?

**Comment by IanMayo** [comment]
Thanks for this @lilitkarapetyan   Does it have a working `storybook`?

If not, could you configure it please? It would be useful way of getting feedback.

Thanks :-D

**Comment by lilitkarapetyan** [comment]
> Thanks for this @lilitkarapetyan Does it have a working `storybook`?
> 
> If not, could you configure it please? It would be useful way of getting feedback.
> 
> Thanks :-D

Hello @IanMayo, yes it hes a storybook.

**Comment by IanMayo** [comment]
Thanks Lilit - are you aware that the `sea surface` / `sea subsurface` symbol-sets are missing?

**Comment by lilitkarapetyan** [comment]
> Thanks Lilit - are you aware that the `sea surface` / `sea subsurface` symbol-sets are missing?

Yes, I will add

**Comment by IanMayo** [comment]
Hello @lilitkarapetyan - steady improvement, thanks 😄  
Are you aware of the "conditional" lists in the data?  So, if the `Symbol Set` is `Air`, then only aircraft-type-things will be in the next drop-down.  Hopefully you can find existing data structures that you can use for that.

One other thing. When the new SIDC editor opens, I think it's expecting a number, but we're providing a string - so it doesn't load/show the current/existing symbol for that feature. Hopefully the MilSymbol library includes a converter.
screencase

**Comment by lilitkarapetyan** [comment]
> Hello @lilitkarapetyan - steady improvement, thanks 😄 Are you aware of the "conditional" lists in the data? So, if the `Symbol Set` is `Air`, then only aircraft-type-things will be in the next drop-down. Hopefully you can find existing data structures that you can use for that.
> 
> One other thing. When the new SIDC editor opens, I think it's expecting a number, but we're providing a string - so it doesn't load/show the current/existing symbol for that feature. Hopefully the MilSymbol library includes a converter. screencase [ screencase ](https://camo.githubusercontent.com/3a31b2ada06addeb02a7e6a5e78e8c519119f6c4c8ae084dbfc9ddd30aeec592/68747470733a2f2f692e6779617a6f2e636f6d2f61663365613733353138653935373735646135316665396164633731626166612e676966) [ ](https://camo.githubusercontent.com/3a31b2ada06addeb02a7e6a5e78e8c519119f6c4c8ae084dbfc9ddd30aeec592/68747470733a2f2f692e6779617a6f2e636f6d2f61663365613733353138653935373735646135316665396164633731626166612e676966)

Hello @ian, I will work on it.

**Comment by lilitkarapetyan** [comment]
Hello @IanMayo , we need all these symbols (icon) ?

**Comment by IanMayo** [comment]
> Hello @IanMayo , we need all these symbols (icon) ?

If you mean "do I need the full set of MilSymbol icons?" then the answer is "yes, please". But, not if you have to hand-code them.  I really hope you can find some existing code that defines them.

Update: here is a sample interface: https://www.spatialillusions.com/unitgenerator-legacy/

Here is the source code for the above: https://github.com/spatialillusions/milsymbol-generator

I can't see an obvious data-structure that defines the dependencies, but I guess it must be there somewhere.

**Comment by IanMayo** [comment]
That's great progress, thanks @lilitkarapetyan .  I can see it's a really complex task.

The `Modifier 1` setting here seems to give the wrong icon.  It is showing the icon for "Anti Submarine Warfare"

image

Plus, for this `sea subsurface` icon, the `Echelon/Mobility/Towed Array` should be showing towed-array settings:
image

There seems to be some strange behavior around the icons shown . I don't think we need to see the icon on every row.  How about we just show the icon at the top - which changes as more settings are assigned.

**Comment by lilitkarapetyan** [comment]
> There seems to be some strange behavior around the icons shown . I don't think we need to see the icon on every row. How about we just show the icon at the top - which changes as more settings are assigned.

Hello @IanMayo  Thanks, I will work on it.

**Comment by IanMayo** [comment]
Thanks @lilitkarapetyan 

I know this is a fantastically complex task, and you are doing really well on it. There is still some way to go:
image

**Comment by lilitkarapetyan** [comment]
> Thanks @lilitkarapetyan
> 
> I know this is a fantastically complex task, and you are doing really well on it. There is still some way to go: image

I am working on it.

**Comment by IanMayo** [comment]
Ooh. we're nearly there now.

I see one remaining issue. For "Sea surface" or "sub-surface" symbols, the `movement` block should include "Short towed array" and "Long towed array".  See this screenshot from `milsymbol generator`

image

**Comment by IanMayo** [comment]
Hello @lilitkarapetyan - it's strange that the Playwright tests have failed.  Has something related to the build been changed?

**Comment by lilitkarapetyan** [comment]
Hello @Ian, No, it failed in the develop brench as well.

**Comment by IanMayo** [comment]
> Hello @ian, No, it failed in the develop brench as well.

Aah, ok @lilitkarapetyan .  Luckily @Tristina1788 is on it :-D https://github.com/serge-web/serge/pull/2894

**Comment by Tristina1788** [comment]
@lilitkarapetyan , @IanMayo  Tested on '2705_Editor_for_SIDC_codes' , 
- Some 'Standard Indentify 2' is working incorrectly. 
 Steps: 
 
 1. Standard Indentify 2 is 'Suspect/Joker' or 'Hostile/Faker'
 2. select Standard Indentify 1 is 'Exercise', 
Notice the icon is not correct. It should be 'X' character in right side 

image

image

- Input field 'Sidc' should be disable for update. ( I try to update the text on input and save, nothing change. So we should disable it instead of show as editable field )

image

**Comment by IanMayo** [comment]
Thanks @Tristina1788 - those are valid observations.  I look forward to @lilitkarapetyan fixing them.

@lilitkarapetyan - I have another issue too, please.  In the game, the editor control shows the SIDC expressed as letters.  When I click on `Edit` - the popup does not show the right values for that symbol.   I can choose some values, then when I Save it, the numeric SIDC is shown.  If I switch to another feature, then back, it shows the numeric SIDC.  If I open the editor for that symbol, then it does show the correct attributes for that shape.

So, I _think_ the editor needs to check for a text SIDC.  If one is provided, it should convert it to numeric, and the popup should show the correct existing fields for the symbol.

**Comment by lilitkarapetyan** [comment]
> @lilitkarapetyan , @IanMayo Tested on '2705_Editor_for_SIDC_codes' ,
> 
>     * Some 'Standard Indentify 2' is working incorrectly.
>       Steps:
> 
> 
>     1. Standard Indentify 2 is 'Suspect/Joker' or 'Hostile/Faker'
> 
>     2. select Standard Indentify 1 is 'Exercise',
>        Notice the icon is not correct. It should be 'X' character in right side
> 
> 
> image
> 
> image
> 
>     * Input field 'Sidc' should be disable for update. ( I try to update the text on input and save, nothing change. So we should disable it instead of show as editable field )
> 
> 
> image

This is also how the symbol generator example functions. You can try it - https://www.spatialillusions.com/unitgenerator-legacy/ 
Screenshot (271)

**Comment by lilitkarapetyan** [comment]
> @lilitkarapetyan , @IanMayo Tested on '2705_Editor_for_SIDC_codes' ,
> 
>     * Some 'Standard Indentify 2' is working incorrectly.
>       Steps:
> 
> 
>     1. Standard Indentify 2 is 'Suspect/Joker' or 'Hostile/Faker'
> 
>     2. select Standard Indentify 1 is 'Exercise',
>        Notice the icon is not correct. It should be 'X' character in right side
> 
> 
> image
> 
> image
> 
>     * Input field 'Sidc' should be disable for update. ( I try to update the text on input and save, nothing change. So we should disable it instead of show as editable field )
> 
> 
> image

This is also how the symbol generator example functions. You can try it - https://www.spatialillusions.com/unitgenerator-legacy/ 
Screenshot (271)

**Comment by lilitkarapetyan** [comment]
> Thanks @Tristina1788 - those are valid observations. I look forward to @lilitkarapetyan fixing them.
> 
> @lilitkarapetyan - I have another issue too, please. In the game, the editor control shows the SIDC expressed as letters. When I click on `Edit` - the popup does not show the right values for that symbol. I can choose some values, then when I Save it, the numeric SIDC is shown. If I switch to another feature, then back, it shows the numeric SIDC. If I open the editor for that symbol, then it does show the correct attributes for that shape.
> 
> So, I _think_ the editor needs to check for a text SIDC. If one is provided, it should convert it to numeric, and the popup should show the correct existing fields for the symbol.



> Thanks @Tristina1788 - those are valid observations. I look forward to @lilitkarapetyan fixing them.
> 
> @lilitkarapetyan - I have another issue too, please. In the game, the editor control shows the SIDC expressed as letters. When I click on `Edit` - the popup does not show the right values for that symbol. I can choose some values, then when I Save it, the numeric SIDC is shown. If I switch to another feature, then back, it shows the numeric SIDC. If I open the editor for that symbol, then it does show the correct attributes for that shape.
> 
> So, I _think_ the editor needs to check for a text SIDC. If one is provided, it should convert it to numeric, and the popup should show the correct existing fields for the symbol.

Hello @ian, I will look into it now, if I find a way to convers the text to a number I will. but why we need it, I think we can create new symbols with number and use only number.

**Comment by IanMayo** [comment]
> Hello @ian, I will look into it now, if I find a way to convers the text to a number I will. but why we need it, I think we can create new symbols with number and use only number.

The value is that expert users recognise blocks in the text code.  They are _Slightly_ human-readable.

Here is a package to convert between the two types: https://github.com/orbat-mapper/convert-symbology

**Comment by lilitkarapetyan** [comment]
> > Hello @ian, I will look into it now, if I find a way to convers the text to a number I will. but why we need it, I think we can create new symbols with number and use only number.
> 
> The value is that expert users recognise blocks in the text code. They are _Slightly_ human-readable.
> 
> Here is a package to convert between the two types: https://github.com/orbat-mapper/convert-symbology

Okay I will do it.

**Comment by Tristina1788** [comment]
@lilitkarapetyan Now 'SIDC' get number for new symbol item. And I also can update it with the number 'SIDC' from another item symbol. It's good for that.  But we should not allow user update with the wrong 'SIDC'. @IanMayo How do you think?


https://github.com/serge-web/serge/assets/107697044/51c1c249-61e4-47dd-b61b-179525d018ae

**Comment by Tristina1788** [comment]
@lilitkarapetyan Now the new shape item get Sidc code is text. should we use number code as last changes? 


https://github.com/serge-web/serge/assets/107697044/4eed7cdd-4dc3-4ab8-b415-36e2a9d1917c

image

**Comment by lilitkarapetyan** [comment]
> @lilitkarapetyan Now the new shape item get Sidc code is text. should we use number code as last changes?
> new-shape-item-has-sidc-code-is-not-number-code.mp4
> 
> image

Yes, at first. the sidc will be a group of string, but when we change the symbol using the symbol generator, it will become a nuymber.

**Comment by lilitkarapetyan** [comment]
I can make the text in the unput filed show a number instaed of letters. what do you think it would be more correct ?

**Comment by IanMayo** [comment]
> @lilitkarapetyan Now 'SIDC' get number for new symbol item. And I also can update it with the number 'SIDC' from another item symbol. It's good for that. But we should not allow user update with the wrong 'SIDC'. @IanMayo How do you think?
Well spotted @Tristina1788 .  You are correct, we should not allow an invalid SIDC to be stored.

**Comment by Tristina1788** [comment]
@lilitkarapetyan , @IanMayo  I get white screen when click on Shape item. Please help me check it.


https://github.com/serge-web/serge/assets/107697044/ec8a447f-160e-43c0-9889-f7cb5a5cd017

And I can't save the new sidc




https://github.com/serge-web/serge/assets/107697044/aa9e5f00-cf51-43f9-8b72-ba8866c4c8e2

**Comment by lilitkarapetyan** [comment]
> @lilitkarapetyan , @IanMayo I get white screen when click on Shape item. Please help me check it.
> white_screen_when_click_Shape_items.mp4
> 
> And I can't save the new sidc
> can_not_save_new_sidc.mp4

I think your editor symbol sidc code is wrong so it wont let edit.

**Comment by Tristina1788** [comment]
@lilitkarapetyan Now I can save 'SIDC' but can't save the changes from another properties. Please help me check 

https://github.com/serge-web/serge/assets/107697044/0243eef6-82f2-41f1-8336-17e175134c0e

**Comment by lilitkarapetyan** [comment]
> @lilitkarapetyan Now I can save 'SIDC' but can't save the changes from another properties. Please help me check
> can_not_save_properties.mp4

I will investigate it

**Comment by Tristina1788** [comment]
Now I can save properties for items. Only enable to save  valid sidc and new sidc show as number code. => They're working as expected.


https://github.com/serge-web/serge/assets/107697044/43bb3464-72a6-4320-8f0f-d8960d156ccb

But we have this issue : The message 'The selected symbol in invalid' when changes 'Symbol set' and after some seconds, the message is dissapeared. @lilitkarapetyan Please help me check it.



https://github.com/serge-web/serge/assets/107697044/c2cdced0-b55e-4f07-acce-daa1c1115a34

**Comment by lilitkarapetyan** [comment]
> Now I can save properties for items. Only enable to save valid sidc and new sidc show as number code. => They're working as expected.
> sidc_works_correctly.mp4
> 
> But we have this issue : The message 'The selected symbol in invalid' when changes 'Symbol set' and after some seconds, the message is dissapeared. @lilitkarapetyan Please help me check it.
> message_show_and_dissapear_immediatly.mp4

I made it so that if you pick the wrong symbols, a warning appears, and it goes away after 2 seconds.

**Comment by lilitkarapetyan** [comment]
If the symbol code is not valid, you can't choose that option, and warning message pops up.

**Comment by Tristina1788** [comment]
> If the symbol code is not valid, you can't choose that option, and warning message pops up.

As my video, the warning message shows as invalid symbol code but It 's dissapeared after some seconds then I still can select and use it. The message should not show if the symbol code is valid.

**Comment by lilitkarapetyan** [comment]
It simply tells you that the last choice you made is incorrect, and the generator doesn't create that SIDC code, but keeps the pld one.

**Comment by lilitkarapetyan** [comment]
I will change the content of the warning.

**Comment by Tristina1788** [comment]
@lilitkarapetyan, @IanMayo  I can see the message now. But I think the font size of the message is quite big with another text. Should we update it with smaller.

image

**Comment by Tristina1788** [comment]
@lilitkarapetyan , @IanMayo Now the symbol sets is always disable all without 4 types (Land Unit, Land Installation, Sea Surface, Space) . Although Story board can have SIDC with many enable  for another symbol set when I select same  Standard Identity

image

image

image

I also try to copy SIDC from story board to one item game play, and no error show as invalid. So the disable symbol set from game play is not correct? 


https://github.com/serge-web/serge/assets/107697044/9a38c445-aad9-4b45-965a-128ea2b51b33

**Comment by lilitkarapetyan** [comment]
> @lilitkarapetyan , @IanMayo Now the symbol sets is always disable all without 4 types (Land Unit, Land Installation, Sea Surface, Space) . Although Story board can have SIDC with many enable for another symbol set when I select same Standard Identity
> 
> image
> 
> image
> 
> image
> 
> I also try to copy SIDC from story board to one item game play, and no error show as invalid. So the disable symbol set from game play is not correct?
> SIDC_disable_symbol_set.mp4

I have implemented a feature that restricts the selection to only vaild symbols.

**Comment by lilitkarapetyan** [comment]
When you change the main icon they will become valid - https://gyazo.com/38f11c8aa9427d36fceddb2d86df284f

**Comment by Tristina1788** [comment]
> When you change the main icon they will become valid - https://gyazo.com/38f11c8aa9427d36fceddb2d86df284f

If `main icon` will affect to enable `symbol sets`, should we move option `main icon` in above option `symbol sets` ?  @IanMayo How do you think?

**Comment by IanMayo** [comment]
> I have implemented a feature that restricts the selection to only vaild symbols.

Yes, @lilitkarapetyan - that works well.

**Comment by IanMayo** [comment]
Hello @lilitkarapetyan - can you remind me what the `SUCCESS` marker is for?  Is it only for use in development?
image

**Comment by lilitkarapetyan** [comment]
> Hello @lilitkarapetyan - can you remind me what the `SUCCESS` marker is for? Is it only for use in development? image

the success marker shiws that the SIDC code is correct (vaild).

**Comment by IanMayo** [comment]
> 
> the success marker shiws that the SIDC code is correct (vaild).

Sure.  I _don't-think_ that has a role in normal usage.  _Maybe_ an `Invalid` marker if there SIDC is invalid, but under _normal_ conditions the SIDC will aways be valid.

**Comment by Tristina1788** [comment]
@lilitkarapetyan We should follow https://www.spatialillusions.com/unitgenerator-legacy/ for our game.  All `symbol-set` is enable to select. And  when the `symbol-set` is changed, we should clear the other drop-downs and only show the match value  for selected `symbol-set` .

**Comment by IanMayo** [comment]
Thanks for that @Tristina1788 .  I used to think that we could change Symbol-Set while keeping the Main-Icon.  But, I see it keeps the main-icon id, but under a different symbol-set that now represents a different icon.

Currently, when there is a main-icon selected, the editor only allows change to a Symbol-Set that also has a main-icon with that id-number.  This isn't a valid user-flow though, since under the new symbol-set it represents a different icon.

So, at any-time we should allow the user to change to any new symbol-set. When this happens, all of the following drop-downs should be cleared.   Please @lilitkarapetyan  :-)

**Comment by lilitkarapetyan** [comment]
> Thanks for that @Tristina1788 . I used to think that we could change Symbol-Set while keeping the Main-Icon. But, I see it keeps the main-icon id, but under a different symbol-set that now represents a different icon.
> 
> Currently, when there is a main-icon selected, the editor only allows change to a Symbol-Set that also has a main-icon with that id-number. This isn't a valid user-flow though, since under the new symbol-set it represents a different icon.
> 
> So, at any-time we should allow the user to change to any new symbol-set. When this happens, all of the following drop-downs should be cleared. Please @lilitkarapetyan :-)

Hello @IanMayo , I will work on it.

**Comment by lilitkarapetyan** [comment]
Hello @Tristina1788,  could you please investigate this breaking playwriting test ? 
image

**Comment by IanMayo** [comment]
Thanks @lilitkarapetyan - clearing the other attributes looks to be working perfectly.  Ok @Tristina1788?

**Comment by Tristina1788** [comment]
> Hello @Tristina1788, could you please investigate this breaking playwriting test ? image

I try from my side and it's ok. I think maybe something about connection when it run tests on server so it can't load the game. I'm trying to run job again to see if it happens.

**Comment by Tristina1788** [comment]
> > Hello @Tristina1788, could you please investigate this breaking playwriting test ? image
> 
> I try from my side and it's ok. I think maybe something about connection when it run tests on server so it can't load the game. I'm trying to run job again to see if it happens.

And the job is running successful now 

image

**Comment by Tristina1788** [comment]
Now symbol set is enable all options. And with selected symbol set, another icon is clear and only show the match value with symbol set => It works as expected. 

image


https://github.com/serge-web/serge/assets/107697044/cdd8e31b-2e01-4e16-8255-28d6245f3380



I'm checking more.

**Comment by Tristina1788** [comment]
@lilitkarapetyan , @IanMayo icon 'Cyberspace' is different with https://www.spatialillusions.com/unitgenerator-legacy/ . Is this ok?

image

image

**Comment by IanMayo** [comment]
Yes, it looks like an error.  One for you, please @lilitkarapetyan 

@Tristina1788 - I think the upside-down question mark is an error indicator, for a code that can't be rendered.  Can you investigate further, please?

**Comment by Tristina1788** [comment]
> Yes, it looks like an error. One for you, please @lilitkarapetyan
> 
> @Tristina1788 - I think the upside-down question mark is an error indicator, for a code that can't be rendered. Can you investigate further, please?

'the upside-down question mark is an error indicator, for a code that can't be rendered' -> It seems correct. Because when I select another symbol set, server can generate list of icon for another option. But it can't not generate with 'Control Measure' symbol



https://github.com/serge-web/serge/assets/107697044/a594d21c-cde2-4dff-9415-0fd84aa3167c

**Comment by lilitkarapetyan** [comment]
Hello @IanMayo , can we combine the changes with the develop branch if evertyhing is fine ?

**Comment by IanMayo** [comment]
Yes @lilitkarapetyan - if you fix the conflicts, we'll get it merged.

**Comment by Tristina1788** [comment]
> @lilitkarapetyan , @IanMayo icon 'Cyberspace' is different with https://www.spatialillusions.com/unitgenerator-legacy/ . Is this ok?
> 
> image

@IanMayo @lilitkarapetyan  We still has one thing need to check for  icon 'Cyberspace'. Should we finish it before merge to develop?

**Comment by IanMayo** [comment]
Thanks for spotting that @Tristina1788 

Could you capture it as a new issue please (with a good description).

The we can get this branch fixed/merged.

**Comment by Tristina1788** [comment]
> Thanks for spotting that @Tristina1788
> 
> Could you capture it as a new issue please (with a good description).
> 
> The we can get this branch fixed/merged.

@IanMayo  This is the ticket #2912 for that.

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
