### PR TITLE
1459: Update message template chip style with More-Info component

### LINKED ISSUE #1459: Message Templates Chips Too Large For Text Box
Some of the longer text chips are too large for the text box: 

Request for Information Cut off

Request for Support Cut off

Weather Forecast tight chip

Lengthening the text box for just a couple of more pixels should do it. Also, the word "information" can be abbreviated to "info".

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1459

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks @lebaphi , but this solution actually makes the problem worse 🤣 

image

The information marker takes up space that actually leaves less space for the title.  

The requirement is for the Game Designer to be able to know which `Verbs` a channel is configured to use.
In my opinion, we can meet this requirement by providing the full verb in the standard HTML tooltip `title` attribute.

**Comment by ShendMikullovci** [comment]
Hi guys! Thanks for advancing with this. While I like the idea of the info marker, I agree with Ian in that it eats up a little bit of space. It'd be nice if the GC could see the terms without having to click on them. If we could achieve that, then the info marker could stay as long as we figure out a way to not have it eat up as much space.

**Comment by lebaphi** [comment]
I agree, but if the term is too long, we can't display it even without infor marker, so as @IanMayo said, we can provide the full verb in the standard HTML tooltip title attribute.

**Comment by lebaphi** [comment]
Small updated

https://user-images.githubusercontent.com/26705621/162360517-e53cad4d-b7a5-47cf-8160-719ced90c013.mp4

**Comment by IanMayo** [comment]
Thanks @lebaphi - but can we simplify it further please?  If you remove the 'i' marker, more of the verb is displayed, and the Game Designer is more likely to be able to read the whole verb.  As a fall-back the verb can be put in the existing [hover tooltip](https://www.w3schools.com/css/css_tooltip.asp) for the component `<span title='A long verb attribute'>A long ver...</span>`

**Comment by lebaphi** [comment]
I make some changes @IanMayo @ShendMikullovci 😄 

https://user-images.githubusercontent.com/26705621/162599058-5f09c333-ade8-4532-8b9f-3205553f66bb.mp4

**Review by IanMayo — APPROVED** [review]
Nicely done.

**Comment by ShendMikullovci** [comment]
Just checked. Looks excellent @lebaphi ! Thanks!

**Pull request merged**
