### PR TITLE
Capture detail expand/collapse in material-table

### LINKED ISSUE #2031: Capture detail expand/collapse in `material-table`
For the `Orders` and `Adjudication` tables, I wish to show the relevant orders when a detail panel is expanded, and hide it again when it is collapsed.

@lebaphi managed to extract the currently filtered rows, hopefully he can get into the code again and make the material-table call a callback when a row is expanded or collapsed.

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #2031 

https://user-images.githubusercontent.com/26705621/201453943-3d8a715d-e2b2-4819-8323-2ab15f382f11.mov

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks for that @lebaphi - good solution, that didn't involve messing with `material-table` :-)

One request:
- could the close event include the row too, please?

One question:
- can you explain how the `close` gets triggered?  I don't quite understand it.

Oh, and @lebaphi - I've extended issue #2035 to act on these new detail events.

**Comment by lebaphi** [comment]
> Thanks for that @lebaphi - good solution, that didn't involve messing with `material-table` :-)
> 
> 
> 
> One request:
> 
> - could the close event include the row too, please?
> 
> 
> 
> One question:
> 
> - can you explain how the `close` gets triggered?  I don't quite understand it.
> 
> 
> 
> Oh, and @lebaphi - I've extended issue #2035 to act on these new detail events.

Hi @IanMayo, it's useEffect with cleanup, more details https://dev.to/otamnitram/react-useeffect-cleanup-how-and-when-to-use-it-2hbm. I will update your request

**Comment by IanMayo** [comment]
> Hi @IanMayo, it's useEffect with cleanup, more details https://dev.to/otamnitram/react-useeffect-cleanup-how-and-when-to-use-it-2hbm. I will update your request

Let every day be a school day :-D

**Comment by lebaphi** [comment]
> > Hi @IanMayo, it's useEffect with cleanup, more details https://dev.to/otamnitram/react-useeffect-cleanup-how-and-when-to-use-it-2hbm. I will update your request
> 
> 
> 
> Let every day be a school day :-D
> 
> 

🤣🤣

**Review by IanMayo — APPROVED** [review]
Good solution, thanks

**Pull request merged**
