### PR TITLE
2967 adopt expected form renderer

### LINKED ISSUE #2967: Adopt expected form renderer
We have adopted a graphical form builder (RJSFB):
https://github.com/ginkgobioworks/react-json-schema-form-builder

It lets a user design a JSON Schema that will be used in the game to render a web-form.

We're rendering the form using `JSON-Editor`.  But, that expects the schema to be defined in a different way to RJFSB.  The core schema is the same, but it expect styling/layout aspects to be presented in a different way to RJFSB.

So, we should switch our forms to the component that RJFSB is expecting (RJSF):
https://github.com/rjsf-team/react-jsonschema-form

This will mean replacing the form in both the `New Message` panel and the `template design` page in `admin`.

This work should extend the work in branch: `2892_Edit_templates_in_admin_pages`

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
Fixes #2967 

## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks @lilitkarapetyan 

This new control is suffering from data-loss, I think it's when the heartbeat pings:
https://github.com/serge-web/serge/issues/2962

Could you make the contents persistent please?

**Comment by IanMayo** [comment]
@Tristina1788 - can you check that we don't lose messages after a few seconds?

Note: I've confirmed locally that we don't lose messages when admin updates the wargame, or when a new message is received in that channel.

**Comment by Tristina1788** [comment]
> @Tristina1788 - can you check that we don't lose messages after a few seconds?
> 
> Note: I've confirmed locally that we don't lose messages when admin updates the wargame, or when a new message is received in that channel.

@IanMayo  Yes, It's fixed. Now the message is not reset any more 

https://github.com/serge-web/serge/assets/107697044/15ae21a1-5151-4193-bd62-fb423f647b93

**Comment by Tristina1788** [comment]
@IanMayo @lilitkarapetyan The copy/page the text on form is not good. It will get the format of the element instead of only the value. 
Do you think it's the issue or we can accept it?

image


https://github.com/serge-web/serge/assets/107697044/cc71b3b6-187c-47c4-beb7-f3ba9f3b040c

**Comment by IanMayo** [comment]
> @IanMayo @lilitkarapetyan The copy/page the text on form is not good. It will get the format of the element instead of only the value. Do you think it's the issue or we can accept it?
> 
>  copy-paste-format-not-good.mp4

Yes it's a strange behaviour @Tristina1788  - and well done for spotting it. But, I'm not worried about it.  It is quite clear to users that the operation didn't work as expected.

**Comment by lilitkarapetyan** [comment]
> > @IanMayo @lilitkarapetyan The copy/page the text on form is not good. It will get the format of the element instead of only the value. Do you think it's the issue or we can accept it?
> > copy-paste-format-not-good.mp4
> 
> Yes it's a strange behaviour @Tristina1788 - and well done for spotting it. But, I'm not worried about it. It is quite clear to users that the operation didn't work as expected.

Hi @ia, should I fox this problem ?

**Comment by IanMayo** [comment]
Hello @lilitkarapetyan - for that copy/paste issue, can you remind me why we had the previous behaviour?

**Comment by lilitkarapetyan** [comment]
> Hello @lilitkarapetyan - for that copy/paste issue, can you remind me why we had the previous behaviour?

I wrote a custom function (copyToClipboard) to easily copy schemas and uiSchemas for Storybook mock data.

**Comment by Tristina1788** [comment]
@lilitkarapetyan @IanMayo  I can copy value as expected now 


https://github.com/serge-web/serge/assets/107697044/7d5df5db-77b9-4a11-8f65-1cfcb4b47926

**Comment by lilitkarapetyan** [comment]
@IanMayo , @Tristina1788 Note : I fixed the isues of #2972 in this PR.

**Comment by lilitkarapetyan** [comment]
> @IanMayo , @Tristina1788  Note : I fixed the isues of #2972 in this PR.

**Comment by Tristina1788** [comment]
@lilitkarapetyan  @IanMayo Now the 'Cancel' and 'Send Message' is removed from admin and user play as expected.

image

image

**Comment by IanMayo** [comment]
A couple of conflicts to resolve here, please @lilitkarapetyan

**Pull request merged**
