### PR TITLE
1860: Add cancel button for chat message

### LINKED ISSUE #1860: Need a cancel button for Chat Messages
We now temporarily store (cache) the contents of messages that are being edited.

image

Now, when we refresh the browser, the Chat Message will keep any draft content.  But, if I change my mind about creating the chat message, I have to manually select-all in the public/private text boxes, and delete them.  I _think_ we would benefit from a `Cancel` button.  One place for this would be beneath (or near) the `Send` right-arrow icon.

Any thoughts @ShendMikullovci ?

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1860 

https://user-images.githubusercontent.com/26705621/192002168-084010fe-24b5-45f7-b6e8-5dc7233c318f.mov

### CODE REVIEW

**Comment by IanMayo** [comment]
Hello @lebaphi  - it needs to _wipe_ the `private chat` box too, please.

**Review by IanMayo — CHANGES_REQUESTED** [review]
Hello @lebaphi - it needs to wipe the private chat box too, please.

**Comment by lebaphi** [comment]
> it needs to wipe the private chat box too, please.

sure @IanMayo

**Comment by IanMayo** [comment]
Functionality works, but not comitting right now.  I've fired a UI question back to Shend in #1860

**Comment by lebaphi** [comment]
no worries @IanMayo

**Comment by lebaphi** [comment]
Screen Shot 2022-09-28 at 10 20 03 PM

**Review by IanMayo — APPROVED** [review]
Great, thanks

**Pull request merged**
