### PR TITLE
1747: Add UI for Support Panel

### LINKED ISSUE #1747: A. Create Support Panel
Create child component that extends the mock `ChannelPlanning` developed in #1745 with following properties:
- Has tabs (similar to WorldState panel)
- Just have single "mock" tab to start with
- Occupies full height of page
- Drag bar to change width
- Clicking on tab collapses panel
- Has these props:
    - player role
    - player force
    - messages for this channel
    - current `forces` from wargame

Note: I've created a `PlanningChannel`, which itself contains a `PlanningMessagesList`.  This `PlanningChannel` will get extended with the above requirements, with `PlanningMessagesList` being the initial `My Orders` tab.

Hmm, I wonder if it's worth using `flexlayout-react` for the vertical tabs?  We're already using that component, after all.  The tabs won't need to be editable, but I think the implementation will be simpler than the way we did it with WorldState.

Here is a mockup:
image

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1747

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks @lebaphi  - looking good :-)

**Comment by lebaphi** [comment]
https://user-images.githubusercontent.com/26705621/184802367-95e05c68-7325-4f39-8c53-2826ba5d1d41.mp4

**Comment by IanMayo** [comment]
We're nearly there @lebaphi 

Just one thing: could we have a visual clue/indicator that the panel can be resized.  Maybe a pair of "grab-bars" (or handle-bars) to the left of the 3 tabs?

**Comment by lebaphi** [comment]
How about this @IanMayo 😄 

image

**Comment by IanMayo** [comment]
I think we need something a bit more visible, please.

**Comment by lebaphi** [comment]
How about this one @IanMayo ?

image

**Comment by IanMayo** [comment]
yes, great.

**Comment by IanMayo** [comment]
This is weird @lebaphi - I get some "artefacts" on the new tabs.  On initial renders there are a couple of light blue marks. When I expand the panel, the marks grow:
image

I guess it's not your code.  Is it the new component?

I'm on Chrome 104

**Comment by lebaphi** [comment]
It's weird, I don't see this issue. I use this lib to support drag and resize https://www.npmjs.com/package/react-rnd, can you try this on firefox or safari?

**Comment by IanMayo** [comment]
Sorry, only have ChromeOS, on my Chromebook. Let's skip it.

**Review by IanMayo — APPROVED** [review]
Some graphic artifacts on ChromeOS, but will solve those if they appear on other operating systems as separate issue.

**Pull request merged**
