### PR TITLE
Feature/459 task group interactions

### LINKED ISSUE #475: StoryBook failing for Collapsible elements
The StoryBook pages are failing for the three collapsible components. I've worked my way back through commits, and it looks like the StoryBook stories have never worked for these components.

image

Live link here: https://serge-review-feature-ma-t1rwsv.herokuapp.com/storybook/?path=/story/local-helper-elements-collapsiblecontent--default

### LINKED ISSUE #476: Group should expand on hover
I wish to add an item to an existing group.  But, I can't if it is collapsed.

Could we make a group expand after it has been hovered over for a second or so?

If it's difficult to only expand after a second of hovering, then it's ok to just expand the group on hover.

screencast

### LINKED ISSUE #477: New Group - needs icon
When we combine two items, we create a new group.

The new group should have a type of `task-group`, that will give it an icon.

screencast

### LINKED ISSUE #478: World State panel - "Other forces" not shown
We have a regression error.

In World State it used to show "Our Forces" and "Other Forces" in two separate tabs.

Now they both just show "Our Forces" in both tabs.

screencast

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
## 🧰 Issue

in process #459
closes #475 (Components have been changed in this branch, so the changes have been added here)
closes #477 
closes #476 
closes #478 

## 🔗 Link to preview

https://serge-review-feature-45-o7hn54.herokuapp.com/storybook/?path=/story/local-mapping--with-assets

## 🤔 Reason: 

Created a group component to modify multilevel data

## 🔨Work carried out:

- [x] Tests pass

## 🖥️ Screenshot

screencast

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have assigned myself to this PR.
- [x] I have chosen an appropriate label for the PR.
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.
- [x] I confirm that I have checked for required README updates and acted accordingly.

## 📝 Developer Notes:

TODO: fix firefox client position coords [done]
not sure why it was happen but for few proptypes  the "Storybook" showing error
изображение

### CODE REVIEW

**Comment by IanMayo** [comment]
Wow, a very impressive piece of work @lilitkarapetyan 

One issue: child elements are missing their icon:
image

**Comment by lilitkarapetyan** [comment]
v2
Thanks @IanMayo. I have fixed firefox issues and `undefined` turns planned issue. But icons for me works. PS in video we have animation on drag but it isn't works with multiple items, that i s why I am showing "move to group" only on group hover.

**Comment by lilitkarapetyan** [comment]
изображение
изображение
изображение
#475 Components have been changed in this branch, so the changes have been added here

**Comment by IanMayo** [comment]
Hello @lilitkarapetyan  - thanks for the update. 

Note: I'm trying to push a cosmetic change, to force a new Heroku build. But, when I try to push your changes the linter fails.  It doesn't like your SCSS:
image

I don't recognise the "&" operator - can I just delete it?

**Comment by IanMayo** [comment]
@lilitkarapetyan - there's a remaining issue.  The icon disappears when an item is moved to the top level.  This is a recording from the Heroku deployment: screencast

**Comment by IanMayo** [comment]
Merging this, so @lilitkarapetyan  can use the TypeScript types in the Platform Types editor

**Review by IanMayo — APPROVED** [review]
We're not done with this yet, but I'm happy with the direction so far.

**Pull request merged**
