### PR TITLE
1309: Intro Pop up or Tutorial for Mapping

### LINKED ISSUE #1309: Intro Pop up or Tutorial for Mapping
I noticed that the mapping channel has no introduction or any tutorial to show users how to use it, orientation and buttons. 
In the channel, we have two new tables that don't appear anywhere else in the game: 

Intro for Mapping Channel

I suggest we offer a short tutorial on how to use the highlighted tables above.

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1309 

https://user-images.githubusercontent.com/26705621/166965797-5d93c679-3a45-4040-b1bc-76d9c8d55c40.mov

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks @lebaphi - could you demonstrate just including the image for one step of the tour?

(in that step we'll introduce the asset markers - we can't link to "real" ones, since we won't know what's in the game)

**Comment by lebaphi** [comment]
> Thanks @lebaphi - could you demonstrate just including the image for one step of the tour?
> 
> (in that step we'll introduce the asset markers - we can't link to "real" ones, since we won't know what's in the game)

I already included the sample image in the tab tour, as you can see the big question mark 😄

**Comment by IanMayo** [comment]
Yes, I see it in all of the steps. Could you just include it for `one` step please?  That is what the `real` tour will look like.

**Comment by IanMayo** [comment]
There seems to be on remaining step @lebaphi 

If I have the `mapping` channel open, and I click on `Open Tour`, the walk-through doesn't appear.   When I switch to a non-mapping tab, the `normal` tour is open, waiting for me.

But, the _expected_ behaviour is for the `mapping` tour to open when clicking on `Open Tour` while in the `mapping` tab.

**Comment by lebaphi** [comment]
ahh, I miss that, I will update 😂

**Review by IanMayo — APPROVED** [review]
Tested & working. Some text still to be tidied up

**Pull request merged**
