### PR TITLE
Player ui tests

### PR DESCRIPTION
**Pull request by IanMayo**
Introduce testing for logic in PlayerUI

Refactor logic to make it more testable.

### CODE REVIEW

**Review by foxleigh81 — COMMENTED** [review]
I'm not too concerned about repeated code at this stage as this can be part of a larger refactor later, however we should be addressing the code complexity ones as these are a good indicator that the function can be written in a more efficient way and reusable manner.

**Comment by IanMayo** [comment]
@jcdiprose estimates 3-6 hours more to finish unit tests on this.  But, the refactored Serge code is stable.  

Merging this PR.  The remaining Unit Tests can fall into a future PR

**Comment by IanMayo** [comment]
Oops, spoke too soon. We currently have failing Unit Tests in the branch. I guess these are ones that @jcdiprose is currently working on.

**Comment by IanMayo** [comment]
Closing this PR, it has diverged too far from the current implementation.

**Pull request closed without merging**
