### PR TITLE
1309: Intro Pop up or Tutorial for Mapping

### LINKED ISSUE #1309: Intro Pop up or Tutorial for Mapping
I noticed that the mapping channel has no introduction or any tutorial to show users how to use it, orientation and buttons. 
In the channel, we have two new tables that don't appear anywhere else in the game: 

Intro for Mapping Channel

I suggest we offer a short tutorial on how to use the highlighted tables above.

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1309 

https://user-images.githubusercontent.com/26705621/165920287-6f7d540a-345c-401a-b4d5-3fb45191af95.mp4

### CODE REVIEW

**Comment by IanMayo** [comment]
Ooh yes, that's good @lebaphi :-)

I'm trying to sort out a way for @ShendMikullovci  to review it, since Heroku still isn't deploying PRs.

**Comment by IanMayo** [comment]
Aaah, there is a workaround.
1. Click on `Checks` at the top of the PR
2. Open the `PR` item on the left-hand side
3. Select the `Artifact` relevant to your operating system
4. The artifact will download. #
5. Unpack the zip-file into a folder. It's probably worth giving the folder the PR number, since you may end up with lots of versions
6. Run `xxx_executable`

Here are the early steps:
video

**Comment by IanMayo** [comment]
One short-coming @lebaphi .  If I'm logged in as `Blue` I'm not offered the `View as` controls.  Can the tutorial do some "switch-path" logic depending on the user?

**Comment by lebaphi** [comment]
sure @IanMayo, I will update

**Comment by IanMayo** [comment]
Thanks @lebaphi - well done.

Time for the next challenge ;-)

I'd like to be able to teach the player about the asset icons and planning forms. But, we won't know what game they are looking at - so we can't refer to an icon.  One solution to this is to include screenshots in the tour tab.  Could you have a go at putting a 400px by 300px screen image into a tour tab? @ShendMikullovci  and I can come up with the actual images/words.

**Comment by lebaphi** [comment]
> Thanks @lebaphi - well done.
> 
> Time for the next challenge ;-)
> 
> I'd like to be able to teach the player about the asset icons and planning forms. But, we won't know what game they are looking at - so we can't refer to an icon. One solution to this is to include screenshots in the tour tab. Could you have a go at putting a 400px by 300px screen image into a tour tab? @ShendMikullovci and I can come up with the actual images/words.

sure @IanMayo 👍

**Comment by IanMayo** [comment]
Did you mean to close this @lebaphi ?

**Comment by lebaphi** [comment]
yep, I have a new PR for this

**Pull request closed without merging**
