### PR TITLE
2963_Send_new_message_without_input

### LINKED ISSUE #2963: Send new message without input, it will get the same content which the last message
## 🐞 Bug description
Send new message without input, it will get the same content which the last message

## 🔢 Steps to Reproduce
1. Playgame with role Blue- Blue 3rd Party
2. Send the first message with some input content
3. Send the second new message without input infor message
4. Notice the second message has same content with the first message

## ⚙️ Expected behavior
Send new message without input should not get the same content which the last message

## 🖥️ Screenscast

https://github.com/serge-web/serge/assets/107697044/6bc21dc3-ed5b-4492-b539-b43c9a475b0c

## 💻 System information
 - Browser : Chrome

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
Fixes #2963 

## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Comment by Tristina1788** [comment]
@IanMayo @lilitkarapetyan Now I can't send message without input values from the second time. But it's enable to send on the first time (After login user role on play game). => It should the same for all times. 


https://github.com/serge-web/serge/assets/107697044/c42c99d1-da48-4658-b025-717cef982d4d

**Comment by Tristina1788** [comment]
> @IanMayo @lilitkarapetyan Now I can't send message without input values from the second time. But it's enable to send on the first time (After login user role on play game). => It should the same for all times.
> 
>  cannot-send-empty-message-on-second-time.mp4

@lilitkarapetyan  I still get same issue as before.

**Comment by lilitkarapetyan** [comment]
> > @IanMayo @lilitkarapetyan Now I can't send message without input values from the second time. But it's enable to send on the first time (After login user role on play game). => It should the same for all times.
> > cannot-send-empty-message-on-second-time.mp4
> 
> @lilitkarapetyan I still get same issue as before.

Should we be able to send a message without input values ?

**Comment by Tristina1788** [comment]
> > > @IanMayo @lilitkarapetyan Now I can't send message without input values from the second time. But it's enable to send on the first time (After login user role on play game). => It should the same for all times.
> > > cannot-send-empty-message-on-second-time.mp4
> > 
> > 
> > @lilitkarapetyan I still get same issue as before.
> 
> Should we be able to send a message without input values ?

Yes, I think so. It depends on the input field is optional or not. And if we can't send message without input, it should be the same for all time. Currently, after login to game play, I can send message without input, but the second, I can't ( As above video) .

**Comment by lilitkarapetyan** [comment]
> > > > @IanMayo @lilitkarapetyan Now I can't send message without input values from the second time. But it's enable to send on the first time (After login user role on play game). => It should the same for all times.
> > > > cannot-send-empty-message-on-second-time.mp4
> > > 
> > > 
> > > @lilitkarapetyan I still get same issue as before.
> > 
> > 
> > Should we be able to send a message without input values ?
> 
> Yes, I think so. It depends on the input field is optional or not. And if we can't send message without input, it should be the same for all time. Currently, after login to game play, I can send message without input, but the second, I can't ( As above video) .

I think after my last commit, it doesn;t let send a message without typing.

**Comment by IanMayo** [comment]
Ok. I don't have a strong feeling about whether we allow empty messages or not. I'm happy with the `easiest` solution.  But, we should have consistent behaviour across whether the user has just opened the channel, or if they have already sent messages.

**Comment by lilitkarapetyan** [comment]
> > > > @IanMayo @lilitkarapetyan Now I can't send message without input values from the second time. But it's enable to send on the first time (After login user role on play game). => It should the same for all times.
> > > > cannot-send-empty-message-on-second-time.mp4
> > > 
> > > 
> > > @lilitkarapetyan I still get same issue as before.
> > 
> > 
> > Should we be able to send a message without input values ?
> 
> Yes, I think so. It depends on the input field is optional or not. And if we can't send message without input, it should be the same for all time. Currently, after login to game play, I can send message without input, but the second, I can't ( As above video) .

I Think after my last commit, it doesn't let me send a message without typing. I will investigate it now.

**Comment by Tristina1788** [comment]
> > > > > @IanMayo @lilitkarapetyan Now I can't send message without input values from the second time. But it's enable to send on the first time (After login user role on play game). => It should the same for all times.
> > > > > cannot-send-empty-message-on-second-time.mp4
> > > > 
> > > > 
> > > > @lilitkarapetyan I still get same issue as before.
> > > 
> > > 
> > > Should we be able to send a message without input values ?
> > 
> > 
> > Yes, I think so. It depends on the input field is optional or not. And if we can't send message without input, it should be the same for all time. Currently, after login to game play, I can send message without input, but the second, I can't ( As above video) .
> 
> I Think after my last commit, it doesn't let me send a message without typing. I will investigate it now.

Yes, This is the screencast for latest code. I can send message at first time after login.

https://github.com/serge-web/serge/assets/107697044/e4c5699b-d1e7-4f24-8639-9ce956a2ee0d

**Comment by lilitkarapetyan** [comment]
@IanMayo I think To solve this problem, we need to retrieve the value of `jsonEditor ` every time it is accessed. but the ways to do this will be different depending on whether we are in the develop branch or `2892_Edit_templates_in_admin_pages`.


We should utilize the value of `jsonEditor `upon its initial call, ensuring that the `formMessage ` value is updated to match the content of our form.

in wich branch should I make the change ?

**Comment by IanMayo** [comment]
> @IanMayo I think To solve this problem, we need to retrieve the value of `jsonEditor ` every time it is accessed. but the ways to do this will be different depending on whether we are in the develop branch or `2892_Edit_templates_in_admin_pages`.
> 
> We should utilize the value of `jsonEditor `upon its initial call, ensuring that the `formMessage ` value is updated to match the content of our form.

Sure, ok. I don't think it's worth fixing this particular part of the issue in `develop`.  So, @lilitkarapetyan - how about merging `edit templates` branch into this, and fixing it relative to that branch?

**Comment by lilitkarapetyan** [comment]
> > @IanMayo I think To solve this problem, we need to retrieve the value of `jsonEditor ` every time it is accessed. but the ways to do this will be different depending on whether we are in the develop branch or `2892_Edit_templates_in_admin_pages`.
> > We should utilize the value of `jsonEditor `upon its initial call, ensuring that the `formMessage ` value is updated to match the content of our form.
> 
> Sure, ok. I don't think it's worth fixing this particular part of the issue in `develop`. So, @lilitkarapetyan - how about merging `edit templates` branch into this, and fixing it relative to that branch?

I think so. but I thnk we could also fix the issues in the `2892_Edit_templates_in_admin_pages branch `

**Comment by Tristina1788** [comment]
@lilitkarapetyan @IanMayo It shows as the error 'must match format "Time"' although the default value is correct format.

image


https://github.com/serge-web/serge/assets/107697044/28c1a754-97b8-4ff6-b87b-d8a400983f0b

**Comment by Tristina1788** [comment]
@lilitkarapetyan  @IanMayo 

Now I can send message without error about time format and send new message without input, it will not get the same content which the last message => It works as expected.


https://github.com/serge-web/serge/assets/107697044/b11bf4dc-9f07-4af0-8a02-c03670b8afa4

@IanMayo The fixing for ticket is works fine now. But we merge this fixing, it will merge all changes from `2892_Edit_templates_in_admin_pages` . And that branch is still not done. Just remind if you forget that.

**Review by IanMayo — APPROVED** [review]

**Comment by lilitkarapetyan** [comment]
fixes #2963

**Pull request merged**
