### PR TITLE
2913_Filter_SIDC_should_not_an_edit_field

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Comment by lilitkarapetyan** [comment]
Fixes #2913

**Comment by Tristina1788** [comment]
@lilitkarapetyan @IanMayo I still can see 'Edit' button on 'SIDC' filter

image

**Comment by lilitkarapetyan** [comment]
> @lilitkarapetyan @IanMayo I still can see 'Edit' button on 'SIDC' filter
> 
> image
We should not see the edit button when using the filter ?

**Comment by Tristina1788** [comment]
> > @lilitkarapetyan @IanMayo I still can see 'Edit' button on 'SIDC' filter
> > image
> > We should not see the edit button when using the filter ?

Yes, I think so. We just need to input sidc ID to filter. @IanMayo How do you think?

**Comment by IanMayo** [comment]
Hello @Tristina1788 - I'm playing in this branch, but there are no features on the `mapping` tab, and when I log in as `Game Designer` I can't add any new features.  I see the new message for the new feature being sent to the server, but they do not get displayed.
Does it work for you?

**Comment by lilitkarapetyan** [comment]
> Hello @Tristina1788 - I'm playing in this branch, but there are no features on the `mapping` tab, and when I log in as `Game Designer` I can't add any new features. I see the new message for the new feature being sent to the server, but they do not get displayed. Does it work for you?

I will look now

**Comment by lilitkarapetyan** [comment]
No, it doesn't work for me, but I think the branch is not the problem.

**Comment by Tristina1788** [comment]
> Hello @Tristina1788 - I'm playing in this branch, but there are no features on the `mapping` tab, and when I log in as `Game Designer` I can't add any new features. I see the new message for the new feature being sent to the server, but they do not get displayed. Does it work for you?

@IanMayo , @lilitkarapetyan  We need to login by user Red - Red2 to enable create new item( Umpire force doesn't have  permission for create item) 

image

**Comment by Tristina1788** [comment]
@lilitkarapetyan @IanMayo We also have the issue on filter SIDC, it's unable to filter with default SIDC. 

https://github.com/serge-web/serge/assets/107697044/9f0f9a57-e75c-44a9-8178-317d1b29ecbb

**Comment by IanMayo** [comment]
>  need to login by user Red - Red2 to enable create new item( Umpire force doesn't have permission for create item)

Yes, working correctly as red player @Tristina1788 :-)

Yes, I also saw that supplying a valid SIDC for the filter does not match with any features.  That's for you, please @lilitkarapetyan

**Comment by IanMayo** [comment]
> @lilitkarapetyan @IanMayo I still can see 'Edit' button on 'SIDC' filter
> 
Yes - it's valid to have the `Edit` button on the SIDC filter, to open the dialog used to generate the SIDC filter

**Comment by Tristina1788** [comment]
@lilitkarapetyan  @IanMayo I think we don't need to remove 'Edit' button as Ian 's comment above

Now when I filter for sidc which is not default, it also shows the core shape item . And filter with sidc which is default, it shows all items include another sidc.

=> We should show only the milsym which contains the filter sidc


https://github.com/serge-web/serge/assets/107697044/5b8720a6-69fb-474a-ab62-0d26632754aa

**Comment by Tristina1788** [comment]
@lilitkarapetyan @IanMayo Now the filter sidc still don't have 'Edit' button ( we should have this button as Ian's expected).
- Filter sidc with exact code => the result of filter is  the milsym has that code and core shape (Should only show milsym has that code). 
- Filter with contains some string sidc code can't work (the filter should show the milsym which contains string in sidc filter) 

https://github.com/serge-web/serge/assets/107697044/2d9d0578-7c87-4c37-baec-dbe6672b918b

**Comment by Tristina1788** [comment]
@lilitkarapetyan @IanMayo Now Sidc filter has 'Edit' button. But 'Id' filter is disabled

image


And these below issues are still happened.

> Filter sidc with exact code => the result of filter is the milsym has that code and core shape (Should only show milsym has that code).
> Filter with contains some string sidc code can't work (the filter should show the milsym which contains string in sidc filter)

**Comment by IanMayo** [comment]
Ok, I think it's ready for you to re-test, please @Tristina1788

**Comment by Tristina1788** [comment]
@lilitkarapetyan @IanMayo Now I can filter Sidc with contains code or equal code. But the 'Id' filter is still disabled. 

image

**Comment by lilitkarapetyan** [comment]
> @lilitkarapetyan @IanMayo Now I can filter Sidc with contains code or equal code. But the 'Id' filter is still disabled.
> 
> image

ahh it wasn't pushed ;) I added it

**Comment by Tristina1788** [comment]
@lilitkarapetyan  @IanMayo Now I can filter with contains / equal sidc and 'Edit' to filter custom sidc well. The 'Id' filter is enable to use.

https://app.screencast.com/5aNMCqa9fhRh1


 It works as expected. So we can close this PR.

**Review by IanMayo — APPROVED** [review]
Tested and working

**Pull request merged**
