### PR TITLE
1376: Attribute chip size

### LINKED ISSUE #1376: Attribute Chip Size
The larger attribute chips end up scooting the "Edit" button far off to the right, eating up half of its display: 

Attribute Chip Size Issue

A good solution would be to have the edit button under the attribute chips at all times: we would avoid this issue and maintain uniformity with the rest of the buttons.

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1376 

Screen Shot 2022-04-13 at 9 47 38 PM

### CODE REVIEW

**Review by IanMayo — APPROVED** [review]
Great, thanks @lebaphi

**Comment by IanMayo** [comment]
We can still lose the "edit" button if we make the screen more narrow.
screencast

**Comment by lebaphi** [comment]
It seems like you are in old version @IanMayo , I updated the attribute to use Chip component (with more border radius) and changed the flex layout to column, not sure why it's showing in row 🤔

**Comment by lebaphi** [comment]
Can you clear cache and try again @IanMayo ?

**Comment by IanMayo** [comment]
You're right. I was looking at an old `deployment`.

**Comment by ShendMikullovci** [comment]
Looks good on my end as well. Thanks guys!

**Pull request merged**
