### PR TITLE
Feature/414 data amends move form logic map bar as map tooltip

### LINKED ISSUE #386: Pin MapBar to side of map
## 💬 Brief description of feature

The MapBar is currently a single panel, that floats over the map.  When the user is making heavy, persistent use of the MapBar, they may instead choose to make it sit alongside the map, _stealing_ horizontal space from it.

We need to change the MapBar to being two independent panels.  The panels are fixed to the left-hand side of the browser page.

## 📖 User Story

As a player/umpire, on occasion I will wish to keep the MapBar permanently open, and steal the horizontal space from the map. When this happens, FitToWindow will ensure all of the map is visible (and not beneath the floating panel).

## ☑️ Acceptance criteria

**Update:** Ian has had a further conversation with Celine/UX, and now has a better understanding of the UX required, summarised below:
* **Two separate panels**:
* Both panels are locked to left-hand side of page
    * the State of the World/Forces panel will be the upper one, will take 50% of height
    * the SofW/Forces panel will have a `Collapse` button, that makes it shrink to zero width
    * the SofW/Forces panel will have a `Pin` button that makes it appear either over, or to the left of the map (like in the YouTube video below)
    * the plan turn/perception/adjudicate form will be shown on the bottom-half on the left. This form does not have a `Pin` button, and is only shown when an asset is selected
    * the pla-turn/perception/adjudicate form will not have ` Collapse` button, but it will have a `Close` (`X`) button at the top-right

Tests for form:
* [ ] Logged in as Blue player, in `Planning` phase
* [ ] Expand `Forces`, it floats over the map
* [ ] Click on "Persistent window" pin icon.  
* [ ] Icon changes to "pinned".  Map control resizes to only use remaining horizontal space
* [ ] `Fit to Window` now makes map content visible in remaining white space
* [ ] Clicking `pinned` icon, allows the map to take all horizontal space, and makes map-bar float over the map again
* [ ] Clicking on `Expand` button makes form expand/contract. When pinned, it steals space from map. When not pinned it expands/contracts over top of map.
* [ ] Click on a `Red` Asset. The perception form will appear.  Clicking on the `X` makes the panel close

## 📐 Designs / Wireframes

https://youtu.be/BcnsdJBHR4Y

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
## 🧰 Issue

closes #386

## 🔗 Link to preview

https://serge-review-feature-41-xjvdjb.herokuapp.com/storybook/?path=/story/local-mapping--with-assets

## 🤔 Reason: 

1. Moved mab bar section into <Map>
2. Created custom react-leaflet component to allow to control re rendering based on attributes
3. Added 3 positions for mabbar
* fixed - as leaflet MapControll
* floating - as leaflet popup with marker
* markerBased - as marker popup

## 🔨Work carried out:

- [x] Tests pass

## 🖥️ Screenshot

изображение
изображение
изображение
изображение

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Review by foxleigh81 — CHANGES_REQUESTED** [review]
Hi Lillit. 

Please can you add a screenshot of the work to the PR and tick the confirmation boxes.

Also, please can you refactor the popup helper into a component in its own right and replace the lifecycle methods with react hooks.

**Comment by IanMayo** [comment]
@lilitkarapetyan - could the bar start in the "docked" state please? 

I think this will be the most common method of using it.

**Review by IanMayo — CHANGES_REQUESTED** [review]
@lilitkarapetyan - could the bar start in the "docked" state please?

I think this will be the most common method of using it.

**Review by IanMayo — CHANGES_REQUESTED** [review]
@lilitkarapetyan - I introduced a "knob" so I could verify the behaviour of `native` boolean flag on selector.

Story [here](https://serge-review-feature-41-xjvdjb.herokuapp.com/storybook/?path=/story/local-form-elements-selector--default)

You'll see from the knob that it currently fails to set the current value when in not-native mode:
screencast

**Comment by lilitkarapetyan** [comment]
> 
> 
> Hi Lillit.
> 
> Please can you add a screenshot of the work to the PR and tick the confirmation boxes.
> 
> Also, please can you refactor the popup helper into a component in its own right and replace the lifecycle methods with react hooks.

Hi. I can't do that with react hooks. If you check it again you will see that was an extended from DivOverlay which one is a class, and I can't extend from DivOverlay if I will use the composition.

**Comment by IanMayo** [comment]
Closing this PR.  We didn't require floating panels in the end.

**Pull request closed without merging**
