### PR TITLE
1212: Read/Unread color button

### LINKED ISSUE #1212: Read/Unread colors and buttons
Currently, we display the status (read/unread) of a message in 2 ways:

- **UNREAD** badge  highlighted in yellow in the message tab
- Unopened envelope icon on the right hand side of the message tab

The "UNREAD" badge is redundant and should be removed. It would be nice to take the same yellow color used for the "UNREAD" badge and use it for the unopened envelope icon. 

Unread color

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1212

### CODE REVIEW

**Comment by IanMayo** [comment]
Can we have a screenshot please @lebaphi ?

**Review by IanMayo — APPROVED** [review]

**Review by IanMayo — COMMENTED** [review]
Have viewed deployed version, and checked the envelope toggles between the different states at the correct points.

**Comment by lebaphi** [comment]
Hi @IanMayo , the screenshots below: :D
Screen Shot 2021-12-09 at 9 14 08 PM
Screen Shot 2021-12-09 at 9 14 00 PM

**Review by ShendMikullovci — APPROVED** [review]
Viewed the deployment. The envelope's color is correct, reacts to interaction. The counter also follows with each marking READ/UNREAD. 
Looks great!

**Pull request merged**
