### PR TITLE
1116: Allow data table to be sorted by Reference or Updated columns

### LINKED ISSUE #1116: Allow data table to be sorted by Reference or Updated columns
Some users would like the COA table to be sorted by document ID (so they're in persistent locations), and others would like them to be sorted in updated order.

We could support this with `Sort` icons on the relevant columns in the header.  The `updated` column currently shows the value produced by "moments" - which is difficult to sort.  Instead we should store the age (prob in millis) but convert that to `moment` on rendering.

I _guess_ we need to pass additional props to the data-table, maybe with a boolean on `sort`.

Obvs we need to re-run the Active Sort on table updates.

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1116

### CODE REVIEW

**Comment by IanMayo** [comment]
Nice work, @lebaphi 

Could we have an indication in the header for which sort is in place please?  Maybe color in the relevant arrow?

**Comment by IanMayo** [comment]
Aah, we lose the sort order on new (or updated) message. I guess we need to re-run the current sort on each change.

**Comment by lebaphi** [comment]
> Aah, we lose the sort order on new (or updated) message. I guess we need to re-run the current sort on each change.

yep, Im working on it.

**Comment by IanMayo** [comment]
@lebaphi - note the conflict on the branch.  We've changed how we generate the `key` for the `data-table`.  The `random()` key was causing the table to re-generate on every new message. We now use the `message._id` and the flicker has gone :-)

This caused a few changes in the file.  You may find it easier to re-apply your changes to an updated version of `data-table\index.tsx`.

**Comment by lebaphi** [comment]
> @lebaphi - note the conflict on the branch. We've changed how we generate the `key` for the `data-table`. The `random()` key was causing the table to re-generate on every new message. We now use the `message._id` and the flicker has gone :-)
> 
> This caused a few changes in the file. You may find it easier to re-apply your changes to an updated version of `data-table\index.tsx`.

thank you @Ian, I will resolve it

**Comment by IanMayo** [comment]
Nearly there :-)

Note below: the items are in ascending order of `ID`.

From another window, I create a new message.

When the table updates, the items appear to be in ascending `updated` order.
Screencast

**Review by IanMayo — CHANGES_REQUESTED** [review]
Fixes for sorting on receipt of new message, please.

**Comment by lebaphi** [comment]
> Fixes for sorting on receipt of new message, please.

yep, I'm working on this

**Comment by IanMayo** [comment]
> > Fixes for sorting on receipt of new message, please.
> 
> yep, I'm working on this

No rush @lebaphi  - I'm about to finish for the weekend.  

Oh, and I won't be merging it until at least Monday, because I've excitedly sent an analyst a link to the Heroku deployment for this PR.  If I merge it, the link will break.  Duh, Ian!

**Comment by IanMayo** [comment]
Thanks @lebaphi 
I'm sure the logic is complex, but we're still not quite there yet.

I sorted them so that the oldest is at the top, and the newest at the bottom.  Then I modified an item.   It should have moved to the bottom - but it stayed where it was.

screencast

**Comment by lebaphi** [comment]
> Thanks @lebaphi
> I'm sure the logic is complex, but we're still not quite there yet.
> 
> I sorted them so that the oldest is at the top, and the newest at the bottom. Then I modified an item. It should have moved to the bottom - but it stayed where it was.
> 
> screencast

wow, let me check this @IanMayo

**Comment by lebaphi** [comment]
Hi @IanMayo , in this case, when you edit one item, the data table will sort again but it occurs on the column ID as default. It should do based on the current sorting-column, I will update it 👍

**Comment by lebaphi** [comment]
I pushed the fix @IanMayo , now it tracks sort direction and sorting-column when data changed.

**Comment by IanMayo** [comment]
Working fine :-)
Will wait for tests to finish.

**Review by IanMayo — APPROVED** [review]
Working fine

**Pull request merged**
