### PR TITLE
1898: Display geometry name on polygons

### LINKED ISSUE #1898: Display geometry name on polygons
For a selected set of orders [*], we should display the "geometry name" in the polygon, or next to the marker point.

[*] we don't have orders yet

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1898 

https://user-images.githubusercontent.com/26705621/196971827-0fe2bdea-6ba6-4c68-baff-b8c0d13ac456.mov

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks @lebaphi - that looks like it took a lot of research.  Any chance of a transparent background for the labels?

**Comment by lebaphi** [comment]
> Thanks @lebaphi - that looks like it took a lot of research. Any chance of a transparent background for the labels?

sure @IanMayo

**Comment by IanMayo** [comment]
Thanks @lebaphi 

It works fine, but I don't really like the popup, and having to cancel the popup.  It _looks-like_ it's going to introduce some performance hit with lots of labelled polygons.

Could you have a look at this method please?
https://stackoverflow.com/questions/50856182/add-text-inside-leaflet-rectangle

It looks like it will automatically centre the text in the parent polygon.

**Comment by lebaphi** [comment]
sure @IanMayo

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
