### PR TITLE
Introduce toggle for isUmpire in Force design UI

### LINKED ISSUE #938: Introduce toggle for `isUmpire` in Force design UI
The `force` structure has a toggle for `umpire`.

This is set automatically for the White force. In the current scenario there are other forces that require the `umpire` flag to be true. 

So, we should add a toggle/checkbox to the `Overview and objectives` part of the `Forces` design page:
image

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #938

### CODE REVIEW

**Comment by lebaphi** [comment]
Hi @IanMayo , I added the toggle for `isUmpire` flag and change the relevant places. 
image
I also plan to remove the `UMPIRE_FORCE` const but it is used in some places and the purpose of using does not related to determining this force is umpire or not, like this one `/serge/packages/components/src/local/mapping/index.tsx`, code line 246.
image
So I decide to leave it 🤔

**Comment by IanMayo** [comment]
> So I decide to leave it 🤔

Yes - correct.  For all of the `mapping` components we can keep the existing logic.

**Review by IanMayo — CHANGES_REQUESTED** [review]
Hello @lebaphi could you fix the use of `.umpire` in these two places please?
https://github.com/serge-web/serge/pull/961/commits/630f1ca41a1882e4827b1ea02dcf6bdebc8a5acc

**Comment by lebaphi** [comment]
> Hello @lebaphi could you fix the use of `.umpire` in these two places please?
> [630f1ca](https://github.com/serge-web/serge/commit/630f1ca41a1882e4827b1ea02dcf6bdebc8a5acc)

Fixed @IanMayo

**Comment by lebaphi** [comment]
It seems the build has failed, let me check this 🤔

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
