### PR TITLE
Hotfix/merge develop into 557

### PR DESCRIPTION
**Pull request by IanMayo**
This branch has been produced to allow a build error to be fixed.

The current `develop` branch fails `yarn install` on a `Big Sur` macos.  The branch in this PR (branched of #686) includes dependency updates, and the `yarn install` doesn't fail.

But, once we merge `develop` in, and fix the conflicts, it has two build issues.

1.  `DEPRECATION WARNING`

```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
@serge/client: Recommendation: math.div(-1 * $size, 2)
@serge/client: More info and automated migrator: https://sass-lang.com/d/slash-div
@serge/client:    ╷
@serge/client: 17 │   margin-top: -1 * $size/2;
@serge/client:    │               ^^^^^^^^^^^^
@serge/client:    ╵
@serge/client:     ../components/build/local/helper-elements/collapsible/header/styles.module.scss 17:15  root stylesheet

```

2. `Typescript Error`
```
/Users/ian/git/serge/packages/client/src/Views/AdminAndInsightsTabsContainer/AdminAndInsightsTabsContainer.tsx
@serge/client: TypeScript error in /Users/ian/git/serge/packages/client/src/Views/AdminAndInsightsTabsContainer/AdminAndInsightsTabsContainer.tsx(15,61):
@serge/client: Argument of type '{ global: { tabSetTabStripHeight: number; tabEnableClose: boolean; tabEnableRenderOnDemand: boolean; }; borders: never[]; layout: { type: string; weight: number; children: never[]; }; }' is not assignable to parameter of type 'IJsonModel'.
@serge/client:   The types of 'layout.type' are incompatible between these types.
@serge/client:     Type 'string' is not assignable to type '"row"'.  TS2345
@serge/client:     13 |   const state = usePlayerUiState()
@serge/client:     14 |   const [byPassUrl] = useState<URL>(getByPassUrl(state))
@serge/client:   > 15 |   const [model] = useState<Model>(FlexLayout.Model.fromJson(FLEX_LAYOUT_MODEL_DEFAULT))
@serge/client:        |                                                             ^
@serge/client:     16 |   const gameAdmin = 'Game Admin'
@serge/client:     17 |   const gameAdminTitle = 'Game Admin'
@serge/client:     18 |   const insights = 'Insights'

```

### CODE REVIEW

**Comment by lebaphi** [comment]
> This branch has been produced to allow a build error to be fixed.
> 
> The current `develop` branch fails `yarn install` on a `Big Sur` macos. The branch in this PR (branched of #686) includes dependency updates, and the `yarn install` doesn't fail.
> 
> But, once we merge `develop` in, and fix the conflicts, it has two build issues.
> 
> 1. `DEPRECATION WARNING`
> 
> ```
> DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
> @serge/client: Recommendation: math.div(-1 * $size, 2)
> @serge/client: More info and automated migrator: https://sass-lang.com/d/slash-div
> @serge/client:    ╷
> @serge/client: 17 │   margin-top: -1 * $size/2;
> @serge/client:    │               ^^^^^^^^^^^^
> @serge/client:    ╵
> @serge/client:     ../components/build/local/helper-elements/collapsible/header/styles.module.scss 17:15  root stylesheet
> ```
> 
> 1. `Typescript Error`
> 
> ```
> /Users/ian/git/serge/packages/client/src/Views/AdminAndInsightsTabsContainer/AdminAndInsightsTabsContainer.tsx
> @serge/client: TypeScript error in /Users/ian/git/serge/packages/client/src/Views/AdminAndInsightsTabsContainer/AdminAndInsightsTabsContainer.tsx(15,61):
> @serge/client: Argument of type '{ global: { tabSetTabStripHeight: number; tabEnableClose: boolean; tabEnableRenderOnDemand: boolean; }; borders: never[]; layout: { type: string; weight: number; children: never[]; }; }' is not assignable to parameter of type 'IJsonModel'.
> @serge/client:   The types of 'layout.type' are incompatible between these types.
> @serge/client:     Type 'string' is not assignable to type '"row"'.  TS2345
> @serge/client:     13 |   const state = usePlayerUiState()
> @serge/client:     14 |   const [byPassUrl] = useState<URL>(getByPassUrl(state))
> @serge/client:   > 15 |   const [model] = useState<Model>(FlexLayout.Model.fromJson(FLEX_LAYOUT_MODEL_DEFAULT))
> @serge/client:        |                                                             ^
> @serge/client:     16 |   const gameAdmin = 'Game Admin'
> @serge/client:     17 |   const gameAdminTitle = 'Game Admin'
> @serge/client:     18 |   const insights = 'Insights'
> ```

Hi @IanMayo , 
- This warning caused this file `bootstrap/scss/_variables.scss` contains `$headings-margin-bottom:      $spacer / 2 !default;`, I checked the latest version of `bootstrap` still also has this line. This warning msg comes from the library `boostrap` so if we want to fix this issue, need to fork the bootstrap repo to our GitHub, make some changes and force the  package.json to install the bootstrap from our Github, not from NPM.

- About the second error `Type 'string' is not assignable to type '"row"'.  TS2345`,  the type should be the `row` type in the `IJsonModel.d.ts`
```
interface IRowAttributes {
    height?: number;
    id?: string;
    type: "row";
    weight?: number;
    width?: number;
}
```
but we defined its type is 
```
layout: {
    type: "row",
    weight: 100,
    children: []
  }
```
=> I guess the compiler knows the type of "row" is a string, not a `row` type as it should be in IRowAttributes. I'm not sure what is the `row` type.

**Comment by IanMayo** [comment]
Hello @lebaphi 

> Recommendation: math.div(-1 * $size, 2)

The library gives a recommended fix.  That looks quite logical.

>  The types of 'layout.type' are incompatible between these types.

A value of `"row"` would seem to be right for a type specified as `"row"`

**Comment by lebaphi** [comment]
> Hello @lebaphi
> 
> > Recommendation: math.div(-1 * $size, 2)
> 
> The library gives a recommended fix. That looks quite logical.
> 
> > The types of 'layout.type' are incompatible between these types.
> 
> A value of `"row"` would seem to be right for a type specified as `"row"`

Hi @IanMayo, 
- We can not fix the code in the `node_modules/bootstrap` library, it should be installed via `npm` or `yarn`.
- The "row" seems right but this function `FlexLayout.Model.fromJson(FLEX_LAYOUT_MODEL_DEFAULT)` is casting "row" to string. I think `row` is the kind of class. That's why we got this error.

**Comment by IanMayo** [comment]
> We can not fix the code in the node_modules/bootstrap library, it should be installed via npm or yarn.

Ooops, I just went in to apply the fix, then realised its not in our code 🤣 

>  I think row is the kind of class. That's why we got this error.

I'll have another play - and see if I can learn anything.

**Comment by IanMayo** [comment]
We'll have to live with the deprecation warning.  I wonder if we can suppress just this specific deprecation?

It _looks-like_ this fixes the Json issue:
image

**Comment by IanMayo** [comment]
Hmm, I'm making progress.  I've fixed the `typescript` errors.

Now `stylelint` is failing in the pre-push hook:
image

Are you able to help with that?

**Comment by IanMayo** [comment]
Close this. Develop branch now builds fine.

**Pull request closed without merging**
