### PR TITLE
[SERGE-606] Provide multiple stacks by default

### LINKED ISSUE #606: Provide multiple stacks of tabs by default
It's common that users don't know they can display channel tabs side-by-side.

If we start off by providing a side-by-side arrange of tabs they will see it's possible to arrange them.

Note: typically the player _controlling_ the map will always have it full screen. We may wish to check if the player has authority to control the map (and plan routes) and display Channels full-screen in that case.

### PR DESCRIPTION
**Pull request by zukilover**
## 🧰 Issue
Closes #606 

## 🚀 Overview: 
Set flex layout model to have 2 tab sets by default, for multiple channels without mapping

## 🤔 Reason: 
It's common that users don't know they can display channel tabs side-by-side.
If we start off by providing a side-by-side arrange of tabs they will see it's possible to arrange them.

## 🔨Work carried out:

- [x] Update default model on `channelTabsContainer`
- [x] Fix racing conditions on `computeTabs` method 
- [x] Tests pass

## 🖥️ Screenshot
screenshot-localhost_3000-2021 02 19-21_54_18

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have assigned myself to this PR.
- [x] I have chosen an appropriate label for the PR.
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.
- [x] I confirm that I have checked for required README updates and acted accordingly.

## 📝 Developer Notes:
This PR will also fix unnoticed bug, where `computeTabs` initiates too early. This caused any flex layout model that had been saved into local storage overriden by the default model.

[Provide multiple stacks of tabs by default](https://app.gitkraken.com/glo/card/2b02d6b6f45347b7bc1496f1d119f308)

### CODE REVIEW

**Comment by IanMayo** [comment]
@zukilover  - this isn't working for me.  I get this _normal_ layout if I go into the Heroku deployment (above).

I've played with the code on my local PC, but `expiredStorage.getItem(modelName)` always returns a value.

I've gone into Chrome DevTools and cleared all storage related to FlexLayout.

image

Any tips to get it to show the new layout?

**Comment by IanMayo** [comment]
Aah, I think I've guessed at the logic.  We stick with one tab if there is a `mapping` channel defined.  (I may be wrong on that).  We should only stick to one big tab if the current user is registered for the `mapping` channel.

Ok - I've just deleted the `mapping` channel - and see the twin split panes.

I'm sure there is existing logic to find out if the current user is a member of a channel. Maybe `matchedAllRolesFilter` or `matchedForceAndRoleFilter`

Aah, maybe it's this logic, and the logic should be moved out to a helper function:
image

**Review by IanMayo — APPROVED** [review]
Approving this, since `check channel membership` has been moved to another issue:
https://github.com/serge-web/serge/issues/615

**Comment by zukilover** [comment]
> Aah, I think I've guessed at the logic. We stick with one tab if there is a `mapping` channel defined. (I may be wrong on that). We should only stick to one big tab if the current user is registered for the `mapping` channel.
> 
> Ok - I've just deleted the `mapping` channel - and see the twin split panes.
> 
> I'm sure there is existing logic to find out if the current user is a member of a channel. Maybe `matchedAllRolesFilter` or `matchedForceAndRoleFilter`
> 
> Aah, maybe it's this logic, and the logic should be moved out to a helper function:
> image

You've guessed it correctly. I'll update the condition as per your suggestion.

**Pull request merged**
