### PR TITLE
Feature/384 add turn decoration to history planned routes

### PR DESCRIPTION
**Pull request by AxelleDRouge**
## 🧰 Issue

Implement the turn decoration #384 

## 🚀 Overview: 

- add the turn decoration, depending on the orientation of the turn, with svg markers
- add the button to remove the last turn, for each route with the activation by clicking on the markers

## 🔗 Link to preview

https://serge-review-feature-38-kta7lv.herokuapp.com/storybook/?path=/story/local-mapping--with-route

## 🤔 Reason: 

As a player I wish to see where a platform has been in the past, and where it's planned steps are.

When a platform is selected, I wish to see the route(s) in more detail.

I wish to have a toggle setting to indicate if I just see a time-limited window of the planned/historic routes, or whether to see all data.

## 🔨Work carried out:

- [x] New functionality visible in Mapping/With Route
- [x] Selecting the selected checkbox in the story makes more detail visible:
        - [x] past and future steps shown in bold
        - [x] perpendicular turn markers displayed (see turn markers note below)
        - [x] when a route is selected, clicking on a turn marker shows a popup button titled "Clear from '[turn number]". Clicking this button fires an method received in context, clicking elsewhere cancels the button.
- [x] Flicking the trimmed checkbox makes the route shown as window-trimmed, or all of route

- [x] Tests pass

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have assigned myself to this PR.
- [x] I have chosen an appropriate label for the PR.
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.
- [x] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Comment by AxelleDRouge** [comment]
I just had a brainwave on how to resolve my last problem which was "Clicking this button fires an method received in context, clicking elsewhere cancels the button.", This PR is complete now

**Comment by IanMayo** [comment]
Thanks Axelle :-)

We're temporarily using the area at the top-left of the screen for the button, but this is going to be used by the *Forces* panel - an overview of ships the current player can control.

I'm not sure how to do it, but for the "Clear route from this step" capability, would you be able to create a mini popup menu next to the turn?  The menu would just contain the single command `Clear route from Turn 0x`

Also, this turn marker is at the wrong angle - it should be horizontal:
image

This turn marker need to rotate about 5-10 degrees anticlockwise:
image

To be perpendicular to the direction of travel, the blue line ends will point to the hexagon corners at approximately  2 o'clock and 8 o'clock on a clock-face.

The popup command appears to always say it's for Leg 06.  It should use the leg number that was clicked upon.

Aah. one last feature.  When the route isn't selected, we would still like to see small circular markers at the end of each turn. Here's the original mockup:
image


Heres is how the were implemented in the legacy version of the mapping:
image

(BTW - Celine would want them in the ship/force color, not black - as in her design.)

**Comment by IanMayo** [comment]
@AxelleDRouge - the SVG turn markers are quite complex - using quite a lot of coordinates.  It is an option to have a single line that joins two points, then give that line a "fat" width?

**Comment by AxelleDRouge** [comment]
I have not created the svg marker but used a converter, yes I suppose it would be possible.

**Comment by IanMayo** [comment]
Thanks for the update @AxelleDRouge - I ❤️  the new SVG icon solution, it's what I imagined us using from the start, though I've been unable to implement it myself ;-)

One remaining issue, a turn marker still isn't oriented correctly:
image

Aah, and this one:
image

The second one represents the end of the line, which is a _special case_.  For the first one, I _think_ the logic in `calculateTurnAngle` isn't quite right.  T04 should look like T02 in your sample data (in the `Storybook` demo).  

When we originally worked on the turn markers, I'm pretty sure the calculation required the "ingoing" angle as well as the "outgoing" angle.  I've sent @AxelleDRouge a link to a spreadsheet that calculates the turn marker angle.

**Review by IanMayo — APPROVED** [review]
Much better logic than the previous version, thanks :-)

**Pull request merged**
