### PR TITLE
2720_Channel_row_are_generated_when_switch_channel

### LINKED ISSUE #2720: Channel row are generated when switch channel
## 🐞 Bug description
In Channels tab, some rows are auto generated when we switch from one channel to another channel

## 🔢 Steps to Reproduce
 
1. Login app as admin
2. Create a new game 
3. From 'Forces' tab, create some forces ( White, Blue, Red)
4. From 'Channels' tab, create channel 1 with some participant rows > Save Channel
5. Create channel 2 with some participant row > Save Channel
6. Switch from channel 1 and channel 2, notice the rows are auto generated

More details from below screencast : 

## ⚙️ Expected behavior
No more row is generated when switch from channels

## 🖥️ Screencast

https://github.com/serge-web/serge/assets/107697044/3fd123c6-d655-4fde-93c0-54cd31b987ed

## 💻 System information

 - Operating System: [e.g. iOS, Windows, etc...]
 - Browser : Chrome
 - Browser Version : Version 120.0.6099.111

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
Fixes #2720 

## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks @lilitkarapetyan .  Could you please verify that this fixes the issue please @Tristina1788 ?

**Comment by lilitkarapetyan** [comment]
Fixes #2720

**Comment by Tristina1788** [comment]
> Thanks @lilitkarapetyan . Could you please verify that this fixes the issue please @Tristina1788 ?

Hi @lilitkarapetyan @IanMayo , now the issue 'Channel row are generated when switch channel' is fixed. But still have one issue relate to channel is a participants with 'Red - All Roles' is always generated when create a channel. Should we also fix it on this branch or I should create another issue for it? (More details from below screencast)

https://github.com/serge-web/serge/assets/107697044/55976ee3-025a-4d99-876e-f8e46af9cca9

**Comment by IanMayo** [comment]
another issue, please @Tristina1788

**Review by Tristina1788 — APPROVED** [review]
The issue is fixed.

**Pull request merged**
