### PR TITLE
2416: Persistent Planning Channel layout/status

### LINKED ISSUE #2416: Persistent Planning Channel layout/status
It would be great if we could make these aspects of the PlanningChannel persistent between browser reloads (via storing as cookies, like we do for page layout):
* [x] Current tab
* [x] Current width of support panel
* For tables:
    * [x] Currently visible columns
    * [x] Whether filters are shown
    * [x] Which filters are applied
    * [x] Sort on any columns
    * [x] Number of rows visible
    * [x] Current turn number (_think_ this is stored in `ChannelPlanning` - so it would probably be stored/retrieved from there)

Note: I'd like the key to start with `serge.planning` and be suffixed with the current role-id (`selectedRoleId` - passed down from `SupportPanel` if necessary)

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #2416 

* [x] Current tab
* [x] Current width of support panel
* For tables:
    * [x] Currently visible columns
    * [ ] Whether filters are shown
    * [ ] Which filters are applied
    * [ ] Sort on any columns

### CODE REVIEW

**Comment by IanMayo** [comment]
I just tried to view the deployment for this, but it's crashing with this error:
image

Hmm, you haven't changed `ArrowHead` - it's probably nothing to worry about.  No. I've checked out the branch - and it's failing with same error (but with a little more detail in the trace):
image

Very strange 😮

**Comment by lebaphi** [comment]
> I just tried to view the deployment for this, but it's crashing with this error: image
> 
> Hmm, you haven't changed `ArrowHead` - it's probably nothing to worry about. No. I've checked out the branch - and it's failing with same error (but with a little more detail in the trace): image
> 
> Very strange 😮

yep, I also see this error, and I'm not sure the root cause, I don't touch this file 🤣

**Comment by IanMayo** [comment]
> yep, I also see this error, and I'm not sure the root cause, I don't touch this file 🤣

I _think_ this is a case where you need a fresh branch off develop, and make your changes one at a time - and track when the problem starts.

**Comment by lebaphi** [comment]
Close due to https://github.com/serge-web/serge/pull/2446

**Pull request closed without merging**
