### PR TITLE
1522: Update Icon Type Dropdown

### PR DESCRIPTION
**Pull request by lebaphi**
Update fixed for #1522 

https://user-images.githubusercontent.com/26705621/169949578-1baf157f-328d-42ea-b0da-0fb77c2911da.mp4

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks @lebaphi .  We don't have the color editor in the top bar (that's ok for now).  But, could you put a `fill-color` icon next to the coloured rectangle please - as a further reminder for what it is, as described here:
https://github.com/serge-web/serge/issues/1522#issuecomment-1130013933

**Comment by lebaphi** [comment]
sure @IanMayo 😉

**Comment by IanMayo** [comment]
Can you give a quick static screenshot of the new icon please @lebaphi ?

**Comment by lebaphi** [comment]
Here it is @IanMayo 

image

**Review by IanMayo — APPROVED** [review]
Great, thanks.

**Pull request merged**
