### PR TITLE
Assets now display perceived data including name

### PR DESCRIPTION
**Pull request by foxleigh81**
## 🧰 Issue
#414 

## 🚀 Overview: 

The data passed to the forms in the `Mapping` component doesn't work correctly. This PR corrects both the sanitisation of data passed to the forms as well as updating the data model itself.

## 🤔 Reason: 
The forms work in their own stories but not within the `Mapping` component.

## 🔨Work carried out:

- [x] Updated data passing in `Mapping`
- [x] Updated the data model
- [x] Updated the stories.
- [x] Tests pass

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have assigned myself to this PR.
- [x] I have chosen an appropriate label for the PR.
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.
- [x] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Comment by IanMayo** [comment]
I've found an issue. I think it's that there isn't a list of speeds for the RCB control.

screencast

**Comment by foxleigh81** [comment]
> I've found an issue. I think it's that there isn't a list of speeds for the RCB control.
> 
> screencast

I have fixed this but in doing so I came across a larger issue.

Because the forms use their own internal state and are not yet connected to a wider state in `mapping` the forms cannot retain their updated value - always defaulting back to their initial state from mock data. At first, I wasn't too concerned about this as it was something that would fix itself when we start capturing state in mapping later on but I'm now concerned that this behaviour is hiding bugs, so this PR is going to be extended to include that mapping state work.

**Comment by IanMayo** [comment]
One naming issue.  We have, for example, two objects called `AdjudicateTurnForm` - one is the react element, the other is the data passed to the element.

Could we rename the data interface type to `AdjudicateTurnFormData`?

**Comment by foxleigh81** [comment]
> One naming issue. We have, for example, two objects called `AdjudicateTurnForm` - one is the react element, the other is the data passed to the element.
> 
> Could we rename the data interface type to `AdjudicateTurnFormData`?

Fixed, will be available on the next push.

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
