### PR TITLE
Cascading menu to trigger creation of new orders

### LINKED ISSUE #1895: Cascading menu to trigger creation of new orders
@IanMayo has produced the list of activities, now we need to create the menu.

Ok. The data is in there for the PlanningChannel story (#1907). `MapControl` is receiving the `actionItems` data (a tree of menu items).  We just need to make the menu popup, and pass the values to the `actionCallback` callback:
image

On Thursday I tried a number of different components to do this, but failed every time :-(. So, I don't really mind if we use an existing popup menu control or do it by hand.

Here is a control that provides a menu:
https://github.com/adammertel/Leaflet.Control.Select

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1895

### CODE REVIEW

**Comment by lebaphi** [comment]
Hi @IanMayo, I think I have integrated the select control successfully, since we don't have any wrapper I import the js and css files in index.html, I also add a type for the Select control but the problem I have must be the control position. As you can see, the library only supports displaying the menu from left to right, not vice versa. So if you put the button on the right side, the menu will be cut off.

https://user-images.githubusercontent.com/26705621/195992896-335db209-fec1-4a01-ae28-63302a05c28a.mov

**Comment by IanMayo** [comment]
> Hi @IanMayo, I think I have integrated the select control successfully, since we don't have any wrapper I import the js and css files in index.html, I also add a type for the Select control but the problem I have must be the control position. As you can see, the library only supports displaying the menu from left to right, not vice versa. So if you put the button on the right side, the menu will be cut off.

Ok, I can live with it being on the left-hand side.  Just one change: we don't need checkboxes for the menu items - clicking a menu item will trigger an event.  So, when a "branch" is clicked it will expand, and when a "leaf" is clicked the event fires and the menu collapses.

**Comment by IanMayo** [comment]
Aah, DeepScan is failing because of errors in `Leaflet.control.select`.  I don't want us to fix third party code.  So, I'd like you to configure the build to exclude these files from testing, please.

**Comment by lebaphi** [comment]
sure @IanMayo

**Comment by lebaphi** [comment]
https://user-images.githubusercontent.com/26705621/196020969-0c70c1ca-fbb6-4666-87be-bacdf776c054.mov

**Comment by IanMayo** [comment]
Nice work.
Two things:
1. there is another tier/level above the one in your demo: the Land, Maritime, Air one.
2. We don't show the bottom tier/level (route-in, search, route-out). So, stop at the level of `precision strike`.

**Comment by IanMayo** [comment]
Any idea why Heroku is failing build? It was intermittent,now it seems to always be failing.

**Comment by lebaphi** [comment]
> Any idea why Heroku is failing build? It was intermittent,now it seems to always be failing.

Do you have a log of the heroku?

**Comment by IanMayo** [comment]
Log here: will also attach screenshot, since the build always just terminates on the same line:
``` -----> Building on the Heroku-22 stack
-----> Determining which buildpack to use for this app
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       USE_YARN_CACHE=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  16.x
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version 16.x...
       Downloading and installing node 16.18.0...
       Using default npm version: 8.19.2
       Resolving yarn version 1.22.x...
       Downloading and installing yarn (1.22.19)
       Installed yarn 1.22.19
       
-----> Installing dependencies
       Installing node modules (yarn.lock)
       yarn install v1.22.19
       warning @serge/executable@0.3.0: Invalid bin entry for "executable" (in "@serge/executable").
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       warning @serge/executable@0.3.0: Invalid bin entry for "executable" (in "@serge/executable").
       [3/4] Linking dependencies...
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/client > bootstrap@4.6.2" has unmet peer dependency "jquery@1.9.1 - 3".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/client > bootstrap@4.6.2" has unmet peer dependency "popper.js@^1.16.1".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/client > react-addons-css-transition-group@15.6.2" has incorrect peer dependency "react@^15.4.2".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/client > react-font-awesome@1.0.3" has incorrect peer dependency "react@~0.11.2".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/client > reactour@1.18.7" has unmet peer dependency "react-is@^16.8 || ^17.0.0-0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/client > eslint-config-standard@14.1.1" has unmet peer dependency "eslint-plugin-import@>=2.18.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > babel-loader@8.2.5" has unmet peer dependency "webpack@>=2".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > css-loader@3.6.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > react-data-table-component@7.4.5" has unmet peer dependency "styled-components@>= 4".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > react-leaflet-cluster@1.0.3" has incorrect peer dependency "react@^17.0.1".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > react-leaflet-cluster@1.0.3" has incorrect peer dependency "react-dom@^17.0.1".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > react-leaflet-cluster@1.0.3" has incorrect peer dependency "react-leaflet@^3.0.2".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > react-leaflet-geoman-v2@0.2.0" has incorrect peer dependency "react@^17.0.0 || ^18.0.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > react-leaflet-geoman-v2@0.2.0" has incorrect peer dependency "react-dom@^17.0.0 || ^18.0.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > react-leaflet-geoman-v2@0.2.0" has incorrect peer dependency "react-leaflet@^4.0.2".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > react-leaflet-v4@4.1.0" has incorrect peer dependency "react@^18.0.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > react-leaflet-v4@4.1.0" has incorrect peer dependency "react-dom@^18.0.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > react-leaflet-vectorgrid@2.2.1" has incorrect peer dependency "leaflet@1.4.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > react-leaflet-vectorgrid@2.2.1" has incorrect peer dependency "react-leaflet@^1.9.1 || 2.2.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > react-scrollbar@0.5.6" has unmet peer dependency "prop-types@^15.6.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > sass-loader@10.3.1" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > storybook-addon-react-docgen@1.2.42" has unmet peer dependency "@storybook/addons@*".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > storybook-addon-react-docgen@1.2.42" has unmet peer dependency "@storybook/components@*".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > storybook-addon-react-docgen@1.2.42" has unmet peer dependency "@storybook/core-events@*".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > style-loader@2.0.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > stylelint-config-css-modules@2.3.0" has unmet peer dependency "stylelint@11.x - 14.x".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > stylelint-config-standard@20.0.0" has unmet peer dependency "stylelint@>=10.1.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > stylelint-css-modules@0.9.0" has unmet peer dependency "stylelint@^9.0.0 || ^10.0.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > @storybook/addon-knobs@6.4.0" has unmet peer dependency "@storybook/addons@^6.4.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > @storybook/addon-knobs@6.4.0" has unmet peer dependency "@storybook/api@^6.4.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > @storybook/addon-knobs@6.4.0" has unmet peer dependency "@storybook/components@^6.4.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > @storybook/addon-knobs@6.4.0" has unmet peer dependency "@storybook/core-events@^6.4.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > @storybook/addon-knobs@6.4.0" has unmet peer dependency "@storybook/theming@^6.4.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > @storybook/react@6.5.12" has unmet peer dependency "require-from-string@^2.0.2".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/executable > @babel/eslint-parser@7.19.1" has unmet peer dependency "@babel/core@>=7.11.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/executable > @babel/eslint-parser@7.19.1" has incorrect peer dependency "eslint@^7.5.0 || ^8.0.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > react-docgen-typescript-loader > @webpack-contrib/schema-utils@1.0.0-beta.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > react-leaflet-v4 > @react-leaflet/core@2.1.0" has incorrect peer dependency "react@^18.0.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > react-leaflet-v4 > @react-leaflet/core@2.1.0" has incorrect peer dependency "react-dom@^18.0.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > storybook-readme > vuex@3.6.2" has unmet peer dependency "vue@^2.0.0".
       warning "workspace-aggregator-38f9e78a-dc75-416a-bb7a-fec3d0947270 > @serge/components > stylelint-config-standard > stylelint-config-recommended@3.0.0" has unmet peer dependency "stylelint@>=10.1.0".
       warning Workspaces can only be enabled in private projects.
       warning Workspaces can only be enabled in private projects.
       warning Workspaces can only be enabled in private projects.
       [4/4] Building fresh packages...
       $ yarn run snyk-protect && husky install
       yarn run v1.22.19
       $ set NODE_OPTIONS=–max_old_space_size=8192 snyk protect
       Done in 0.06s.
       fatal: not a git repository (or any parent up to mount point /)
       Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
       Done in 202.33s.
       
-----> Build
       Detected both "build" and "heroku-postbuild" scripts
       Running heroku-postbuild (yarn)
       yarn run v1.22.19
       $ yarn build && yarn build-storybook
       $ lerna run build --scope @serge/components --scope @serge/config --scope @serge/helpers --scope @serge/store --scope @serge/client --stream
lerna notice cli v5.6.2
lerna info versioning independent
lerna notice filter including ["@serge/components","@serge/config","@serge/helpers","@serge/store","@serge/client"]
lerna info filter [
lerna info filter   '@serge/components',
lerna info filter   '@serge/config',
lerna info filter   '@serge/helpers',
lerna info filter   '@serge/store',
lerna info filter   '@serge/client'
lerna info filter ]
lerna info Executing command in 4 packages: "yarn run build"
       @serge/config: $ tsc --pretty
       @serge/helpers: $ tsc --pretty
       @serge/components: $ rimraf build && yarn copy && yarn copy-assets && yarn copy-assets-storybook && tsc && yarn cleanup
       @serge/components: $ copyfiles -u 1 -e src/**/*.ts* -e src/**/*.md src/**/*.* build
       @serge/components: $ copyfiles -u 4 src/local/asset-icon/counters/*.svg ../client/public/assets/counters
       @serge/components: $ copyfiles -u 4 src/local/asset-icon/counters/*.svg static/assets/counters
       @serge/components: $ rimraf build/vendor && rimraf build/local/**/mocks && rimraf build/local/**/*.stories.* && rimraf build/local/**/*.spec.*
       @serge/client: $ react-scripts --max_old_space_size=8192 build
       @serge/client: Creating an optimized production build...
```
image

**Comment by IanMayo** [comment]
> Nice work. Two things:
> 
> 1. there is another tier/level above the one in your demo: the Land, Maritime, Air one.
> 2. We don't show the bottom tier/level (route-in, search, route-out). So, stop at the level of `precision strike`.

This still needs to be changed too, please.

**Comment by lebaphi** [comment]
> Nice work. Two things:
> 
> 1. there is another tier/level above the one in your demo: the Land, Maritime, Air one.
> 2. We don't show the bottom tier/level (route-in, search, route-out). So, stop at the level of `precision strike`.

I build the menu based on `planningActivities`, you can see we render it in `PlanningActitivityMenu`, interface for data structure:
```
export type PlanningActitivityMenuType = {
  label: string
  value: string
  items?: PlanningActitivityMenuType[]
}
```
if we don't show the bottom tier/level, we don't set the items for it.

**Comment by lebaphi** [comment]
@IanMayo you meant the build is terminated at this code line `@serge/client: Creating an optimized production build...`?

**Comment by IanMayo** [comment]
> @IanMayo you meant the build is terminated at this code line `@serge/client: Creating an optimized production build...`?

Yes, always on that line.

**Comment by lebaphi** [comment]
> 

strangely no errors appear in the log...

**Comment by IanMayo** [comment]
I know, no clues. Will have to Google it tomorrow. I don't think I can merge though, since it looks like it will break develop branch.

**Comment by lebaphi** [comment]
> I know, no clues. Will have to Google it tomorrow. I don't think I can merge though, since it looks like it will break develop branch.

Yes, I agree, I am looking on that too

**Comment by lebaphi** [comment]
I've removed all `node_module` and install again, then run
- yarn build
- yarn build-storybook
- yarn lint

all green, strange 🤔

**Comment by lebaphi** [comment]
looks like the Heroku issue has been fixed @IanMayo

**Comment by IanMayo** [comment]
> looks like the Heroku issue has been fixed @IanMayo

or it's intermittent, and worked this time by chance 🤣

**Review by IanMayo — APPROVED** [review]

**Comment by lebaphi** [comment]
> > looks like the Heroku issue has been fixed @IanMayo
> 
> 
> 
> or it's intermittent, and worked this time by chance 🤣 
> 
> 

maybe 😂

**Pull request merged**
