### PR TITLE
Provide explanatory message on Endorse or Request Changes

### LINKED ISSUE #996: Provide explanatory message on Endorse or Request Changes
When the `Release manager` either endorses a document, or requests changes on a document, they are able to provide some notes of explanation. See the two `Review changes` items below:

image

We need to modify Serge to allow this additional content to be provided.

Suggest these changes:
## Dialog
- produce popup dialog, taking title as parameter
- dialog has text-area for explanation to be provided
- dialog has `Cancel` and `Send` buttons
- on `Cancel` nothing happens. On `Send` callback is called.

## COA Message Detail - UI
- in `channel-coa-message-detail\index.tsx`
- modify `handleEndors` and `handleRequestChanges` handlers
- popup dialog when handler called
- if dialog cancelled, no further processing
- if dialog `Sent` call existing `requestChanges` or `endors` handlers - passing the new (possibly empty) message to them

##  COA Message Detail - changes
- modify `requestChanges` and `endors` to take a new `FeedbackItem`, to be stored in the message `CollaboraionDetails`. The `feedback` field can be blank if none was provided, but the item should still be created

The above should be tested through the existing `Storybook` for `COA Status Board`

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #996

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks - you may have missed this one bit:
image

It's how/where we store the item of feedback.

(not by changing the existing `feedback` element from `boolean` to `string`)

Happy to give more advice tomorrow.

**Comment by lebaphi** [comment]
> Thanks - you may have missed this one bit:
> image
> 
> It's how/where we store the item of feedback.
> 
> (not by changing the existing `feedback` element from `boolean` to `string`)
> 
> Happy to give more advice tomorrow.

ahh, we already set the `feedback` in the `message.feedback`, in the `endorse` helper, I see we just produce the message structure like:
```
return {
    ...message,
    details: {
      ...message.details,
      collaboration: {
        ...message.details.collaboration,
        status: CollaborativeMessageStates.DocumentPending,
        owner: undefined
      }
    }
  }
```
So I think if we create a new item `feedback` in the `collaboration` object, will it be redundant?

**Comment by IanMayo** [comment]
`message.feedback`.  That's a boolean flag for if this message is an item of feedback.

The _new_ feedback is feedback on the message itself. Yes - confusing 🤣

**Comment by lebaphi** [comment]
> `message.feedback`. That's a boolean flag for if this message is an item of feedback.
> 
> The _new_ feedback is feedback on the message itself. Yes - confusing 🤣

okay I see, will update 2moro 😆

**Comment by IanMayo** [comment]
I'm afraid I've made some mods to `coa channel message detail`.  If they're not straightforward to resolve, I'll have a go.

**Comment by lebaphi** [comment]
> I'm afraid I've made some mods to `coa channel message detail`. If they're not straightforward to resolve, I'll have a go.

resolved @IanMayo

**Comment by IanMayo** [comment]
I've made some changes @lebaphi - I'd appreciate you checking my code.

Can I ask for a cosmetic change?

Could you make the top/bottom bars on the dialog a little darker grey?    It wasn't clear where the editable central was when I first saw it:
image

**Comment by lebaphi** [comment]
> I've made some changes @lebaphi - I'd appreciate you checking my code.
> 
> Can I ask for a cosmetic change?
> 
> Could you make the top/bottom bars on the dialog a little darker grey? It wasn't clear where the editable central was when I first saw it:
> image

sure @IanMayo, let me update this 👍

**Comment by lebaphi** [comment]
Screen Shot 2021-08-24 at 9 24 11 AM
w
Screen Shot 2021-08-24 at 8 57 38 AM
we have 2 versions, which one do you prefer Ian, do you think we need a placeholder (e.g: Typing here...) for the textarea?

**Comment by IanMayo** [comment]
Thanks @lebaphi 
Let's go for the one with darker shade at top & bottom.

Yes - a placeholder would be useful - particularly if text was all selected by default, so it got replaced as the user starts typing.  Oh, or if it just disappears once the cursor goes in there - like the placeholder text [here](https://getbootstrap.com/docs/4.0/components/forms/).   Suggest text can be provided as a prop, since for `Request changes` we need detail of changes, but for `Endorse message` it is optional.  So, `Detail of changes` for the first, but `Feedback (optional)` for the second.

**Comment by IanMayo** [comment]
Hello @lebaphi - if we can get the UI cosmetics sorted, we can merge this PR, and push ahead with the `Assign to` list.

Note: I have sneaked in some logic ready for `Create new message`.

**Comment by lebaphi** [comment]
updated @IanMayo 
Notes: I see you change the way we store the feedback item likes
```
message.details.collaboration.feedback.push(feedbackItem)
```
So I think we don't need to make a change in the `helpers/changers` because we already handle it in
```
return {
    ...message,
    details: {
      ...message.details,
      collaboration: {
        ...message.details.collaboration, // <== the 'message.details.collaboration.feedback' in here
        status: CollaborativeMessageStates.DocumentPending,
        owner: undefined
      }
    }
  }
```

**Comment by IanMayo** [comment]
thanks @lebaphi :-)

We need to append the new item to the list of existing feedback items _somewhere_.

Is that already being done somewhere?

**Comment by lebaphi** [comment]
> thanks @lebaphi :-)
> 
> We need to append the new item to the list of existing feedback items _somewhere_.
> 
> Is that already being done somewhere?

Yep, this line is enough: `message.details.collaboration.feedback.push(feedbackItem)`.

**Comment by IanMayo** [comment]
> > thanks @lebaphi :-)
> > We need to append the new item to the list of existing feedback items _somewhere_.
> > Is that already being done somewhere?
> 
> Yep, this line is enough: `message.details.collaboration.feedback.push(feedbackItem)`.

Ok, so this PR is ready to go?

**Comment by lebaphi** [comment]
> > > thanks @lebaphi :-)
> > > We need to append the new item to the list of existing feedback items _somewhere_.
> > > Is that already being done somewhere?
> > 
> > 
> > Yep, this line is enough: `message.details.collaboration.feedback.push(feedbackItem)`.
> 
> Ok, so this PR is ready to go?

Yep, go to moon 🚀

**Review by IanMayo — APPROVED** [review]
Very happy with this. Thanks @lebaphi

**Comment by IanMayo** [comment]
(closed & re-opened, to try to wake up static analysis)

**Pull request merged**
