### PR TITLE
1291 Add popup to edit the form attribute value

### LINKED ISSUE #1291: Variable Tracking UX/UI
Questions to be addressed for the variable tracking UX/UI: 

Essentially, what do we want the player to feel and be able to do when playing with assets (vehicles) on the map? 

1. Do we want the player to have/feel full control with a major focus on the asset itself? Tunnel vision focused on the vehicle selected?

2. Do we want the player to have (and feel that they have) thorough visibility of the resources of each asset? Can that be another lever for the game? Could the White Force choose not to show some of the resources that an asset has at a specific time? etc.
 
3. Do we want the player to have (and feel that they have) partial control of the asset with a major focus on the map? Do we want asset resources visible but not overbearing, so a clear and dominating perception/view of the map is maintained?

These questions beg the following ones: 
- How important is the surrounding information when making a decision for an asset? 
- Does the importance of the surrounding information when making a decision for an asset change according to asset type?
- Do other assets' status, location, resources (etc.) come into play when making a decision? To what degree?
- Can asset goals temporarily (or permanently) overcome mission goals?

Depending on the answers to these questions, we can come up with different designs for (and essentially, a different feel of) variable tracking.

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1291

### CODE REVIEW

**Comment by lebaphi** [comment]
image

When the list is too long, it will enable the scroll bar.

**Comment by IanMayo** [comment]
Thanks @lebaphi - I'll take over this for a while. We need some attributes to not be editable by player, but all of them editable by umpire. I also want to display more data. I'll have a play :-)

**Comment by IanMayo** [comment]
I have a remaining issue in here @lebaphi .

There is a z-order like issue with the attribute editor:
image

The list of assets is being shown over it.

**Comment by IanMayo** [comment]
Great, thanks @lebaphi

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
