### PR TITLE
Get_white_screen_when_send_feedback_or_send_message_and_send_message_…

### LINKED ISSUE #2921: Get white screen when send feedback or send message and send message from admin
## 🐞 Bug description
- Get white screen when send feedback or send message and send message from admin

## 🔢 Steps to Reproduce

1. Go to https://serge-inet.herokuapp.com/
2. Create a basic game
3. Try to send feedback / send message from channel and send message from admin
4. Notice the white screen shows and user need to refresh page and login again

Note: this bug is not present when run on `develop`

image

## ⚙️ Expected behavior
User can send message or send feedback without issue

## 🖥️ Screenscast

https://github.com/serge-web/serge/assets/107697044/b0c822e1-dbae-48e7-a841-d798a49a68d2

## 💻 System information
- Browser : Chrome
- Browser Version : Version 120.0.6099.111

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
…from_admin

Fixes #2921 

## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Comment by IanMayo** [comment]
Hello @lilitkarapetyan - can you explain how this fix works please?  Surely we don't have a database called `_global_changes`?

**Comment by lilitkarapetyan** [comment]
> Hello @lilitkarapetyan - can you explain how this fix works please? Surely we don't have a database called `_global_changes`?
The _global_changes" database is automatically generated by CouchDB by default. It's part of CouchDB's built-in functionality to track changes across all databases within the instance.
Screenshot (284)
it's just that its structure doesn't match the new messages we're receving, that's why we get an erro.

**Comment by IanMayo** [comment]
I don't remember this feature. Can you remind me please @lilitkarapetyan ?

**Update**: sorry I missed the CouchDb part of the message. Got it.

**Comment by lilitkarapetyan** [comment]
I've updated it so that the updates from _global_changes aren't sent to tthe client through socket anymore
I think it is not necessary for us in the client section

**Review by IanMayo — APPROVED** [review]
Merging, so we can test on Heroku

**Pull request merged**
