### PR TITLE
1305: Fix issue mapping cursor

### LINKED ISSUE #1305: Mapping Cursor
Cursor change to pointer hand

The cursor should change to a pointer/hand click when hovering over each asset.

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1305 

Hi @ShendMikullovci @IanMayo , please have a look on the deploy link, I can not capture the cursor icon 😄

### CODE REVIEW

**Comment by ShendMikullovci** [comment]
This deployment also sends me to Papafoxtrot.

**Comment by IanMayo** [comment]
Hmm, @ShendMikullovci - the cursor changes to pointer as it goes over the icon for an asset.

hover icon

But, did you think it should be a pointer over the asset name too?  Hmm, the whole of the row acts as a "click target" - so maybe it should change to a pointer when it goes on the row.

Do you have an opinion @lebaphi ?

**Comment by lebaphi** [comment]
> Hmm, @ShendMikullovci - the cursor changes to pointer as it goes over the icon for an asset.
> 
> hover icon
> 
> But, did you think it should be a pointer over the asset name too? Hmm, the whole of the row acts as a "click target" - so maybe it should change to a pointer when it goes on the row.
> 
> Do you have an opinion @lebaphi ?

Yes, I have the same idea with you @IanMayo 👍

**Comment by ShendMikullovci** [comment]
> Hmm, @ShendMikullovci - the cursor changes to pointer as it goes over the icon for an asset.
> 
> hover icon
> 
> But, did you think it should be a pointer over the asset name too? Hmm, the whole of the row acts as a "click target" - so maybe it should change to a pointer when it goes on the row.
> 
> Do you have an opinion @lebaphi ?

Yes, I was thinking for it to be a pointer over asset name as well.

**Comment by IanMayo** [comment]
Ok,  @lebaphi -  let's go for the pointer over the asset name as well as the icon.

**Review by IanMayo — APPROVED** [review]
Modified so pointer cursor over whole asset

**Pull request merged**
