### PR TITLE
Fix icon bug

### LINKED ISSUE #29: Bug in Serge-Web: retrieve icons
When we run serge-player, we don't get the images that are in the repo.

Here's an example of a missing icon:
image

Chrome dev tools show that the images aren't found:
image

I _guess_ the URL isn't being constructed correctly by the Node server

### PR DESCRIPTION
**Pull request by zukilover**
## 🧰 Ticket
Closes #29 

## 🚀 Overview: 
Refactor image asset directory

## 🤔 Reason: 
When we run serge-player, we don't get the images that are in the repo.

## 🔨Work carried out:
- [x] Move asset dir from server to client/public
- [x] Add static asset config to serve public dir
- [x] Tests pass
[Bug in Serge-Web: retrieve icons](https://app.gitkraken.com/glo/board/XZIuhoko5QAPaF0f/card/Xa78U36ElQAPAoKK)

### CODE REVIEW

**Comment by IanMayo** [comment]
@zukilover - this fixes the issue for displaying existing icons.

But, when the user uploads a new icon for a force, or changes the icon in the welcome page, the icon isn't found - since these new icons are still pushed into a server page.

So, I think we need a _little_ more.  We need to either 
1. correct the client code to refer to the server hosting location for the icons
or
2. change the "upload" logic to push the image to a folder in the client package

The second option doesn't seem logical. So, I _think_ we need to unpick the image location changes in this PR, and direct the client to look in the correct server location (somehow...)

**Review by IanMayo — CHANGES_REQUESTED** [review]
But, when the user uploads a new icon for a force, or changes the icon in the welcome page, the icon isn't found - since these new icons are still pushed into a server page.

So, I think we need a little more. We need to either

correct the client code to refer to the server hosting location for the icons
or
change the "upload" logic to push the image to a folder in the client package
The second option doesn't seem logical. So, I think we need to unpick the image location changes in this PR, and direct the client to look in the correct server location (somehow...)

**Comment by zukilover** [comment]
> But, when the user uploads a new icon for a force, or changes the icon in the welcome page, the icon isn't found - since these new icons are still pushed into a server page.
> 
> So, I think we need a little more. We need to either
> 
> correct the client code to refer to the server hosting location for the icons
> or
> change the "upload" logic to push the image to a folder in the client package
> The second option doesn't seem logical. So, I think we need to unpick the image location changes in this PR, and direct the client to look in the correct server location (somehow...)

Code updated with images served from `server/img` and `server/default_img`

**Review by IanMayo — CHANGES_REQUESTED** [review]
We still don't see the Serge icon on the player welcome screen:
image

Nor do we see the `White Force` icon on the White Force edit panel in the admin page:
image

**Comment by zukilover** [comment]
> We still don't see the Serge icon on the player welcome screen:
> 
> Nor do we see the `White Force` icon on the White Force edit panel in the admin page

it works okay from my end. Are you sure you've got the correct env settings? (or simply check on the broken image, and please see where it comes from)

**Review by IanMayo — APPROVED** [review]
Great, working.  I'm stumped about why the earlier fix didn't work for me.

There is a chance that _Ian_ has looking at the wrong branch, but let's not talk about that any further.

**Pull request merged**
