### PR TITLE
1001: As participant in Collaborative Working, I need to see the feedback history for a message

### LINKED ISSUE #1001: As participant in Collaborative Working, I need to see the feedback history for a message
If I am being asked to modify a document (or it has been endorsed), then I need to view the feedback provided.

I certainly need to view the most recent feedback, and optionally previous items too.

The `Channel COA message detail` component should be extended to show the feedback on a message - with date and author.

I _guess_ this could be a block at the bottom of the control.  I should see the most recent feedback item, with a collapsed set of rows beneath it.  A `more` button/link should expand the feedback.

I _guess_ this feedback block should _steal_ vertical space, and the JSON-Editor (enabled or disabled) should get scroll-bars when necessary.  Hmm, no. That's wrong. The status board can be of infinite length.  So, the JSON-editor can always be full height. It's the channel that has scroll bars.

mockups

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1001

### CODE REVIEW

**Comment by lebaphi** [comment]
image

Expanded:
image

**Comment by IanMayo** [comment]
Thanks. Could you include date/time and author for each feedback item too, please?

**Comment by lebaphi** [comment]
> Thanks. Could you include date/time and author for each feedback item too, please?

sure Ian 👍

**Comment by lebaphi** [comment]
Updated 👍 
image

**Comment by IanMayo** [comment]
Merged in #1026 
https://github.com/serge-web/serge/pull/1026/commits/0466c34f5034f436c1d10791e3f82943078cae1f

demo

**Pull request closed without merging**
