### PR TITLE
The new shape umpire should not have black color as default

### LINKED ISSUE #2842: The new shape umpire should not have black color as default
## 🐞 Bug description
The new shape item should not have black color as default

## 🔢 Steps to Reproduce
1. Play game with data wargame-l6nngxlk
2. Click on channel 'Core Mapping'
3. Create a new Shape item
4. Notice it 's created with default color is black although the force default is 'f-Red'

image

View  below screencast for more detail
## ⚙️ Expected behavior
The shape item should show default color same as default force color

## 🖥️ Screencast

https://github.com/serge-web/serge/assets/107697044/3cbb6233-c07b-49bc-b2a7-251953cd3112

## 💻 System information
Browser : Chrome
Browser Version : Version 120.0.6099.111

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #2842

### CODE REVIEW

**Comment by IanMayo** [comment]
I've had a play with this, and I'm not convinced it's an issue. The color should be the color of the logged in player. If the player is logged in as umpire force, then black is the correct color.

I'll have another look at this tomorrow.

**Comment by Tristina1788** [comment]
> I've had a play with this, and I'm not convinced it's an issue. The color should be the color of the logged in player. If the player is logged in as umpire force, then black is the correct color.
> 
> I'll have another look at this tomorrow.

@IanMayo you 're correct. Login with 'Umpire' force user and the shape is black as default. So do you think the issue is from default force is not correct? It should get default Force depends on user login, so above case, it should show black color and the default force is 'f-umpire' instead of 'f-red'? (Currently login with any force user, it always create new item with default force is 'F-red' 

https://github.com/serge-web/serge/assets/107697044/a15af4a3-aed0-4bdf-b87e-ef7f6c16b283

- Currently the fixing will make the color of icon Item (on Items panel) and color of Shape Item is changed follow the 'Force' properties.


https://github.com/serge-web/serge/assets/107697044/c2dc7e25-c6df-4125-bf65-ec79ab65952e

**Comment by IanMayo** [comment]
Ok @Tristina1788 - this is ready for checking again, please.

**Comment by Tristina1788** [comment]
> Ok @Tristina1788 - this is ready for checking again, please.

@IanMayo  The color of Item is correct with user login (Umpire), but the Force should show f-umpire instead of f-red (We don't have f-umpire on the dropdown list). I raised the issue before for 'Force' selection should have all force #2806.

image

- And the new text item doesn't have 'Color' properties and the background color and color text is same. So we can't see the text on it.

image

**Comment by IanMayo** [comment]
Ok, ready for re-checking, please @Tristina1788

**Comment by Tristina1788** [comment]
> Ok, ready for re-checking, please @Tristina1788

@IanMayo  Now the color is follow 'Force' and the 'Force' is correct (It also has Umpire on Force list). Ony one thing is created Text item for Umpire, it has background color and color of text is black. So we can't see the text. 

image

**Comment by IanMayo** [comment]
Hello @lebaphi - can you think of a solution for the above issue?  Put the text in a light shade when the background fill is dark?  Is there a standard solution to this issue?

**Comment by lebaphi** [comment]
> Hello @lebaphi - can you think of a solution for the above issue? Put the text in a light shade when the background fill is dark? Is there a standard solution to this issue?

Hi @IanMayo , I think we can add the text shadow if the text's color is the same with force color. e.g: text red and the force is f-red or text black & force is umpire...

**Comment by IanMayo** [comment]
that's clever!

**Comment by lebaphi** [comment]
how about this one @IanMayo ?

image image

**Comment by IanMayo** [comment]
Hello @lebaphi - thanks for having a go.   I'm a bit nervous about:
1.  whether there is enough contrast for the new strategy
2. whether there could be a performance cost of the calculations for this rendering across hundreds of shapes

But, I couldn't reproduce the issue.  I logged into the deployed game as a member of `umpire` force, and tried to add a text box.  But  the UI fell over. I _Think_ it was at the `subString` method in the new calculation code.

How about another strategy?   
1. Find out if the background color is dark using [this](https://github.com/bgrins/TinyColor#isdark) library
2. If it is dark, make the text white

**Comment by Tristina1788** [comment]
@IanMayo  Checking on '2842-shape-umpire-color' branch, screen becomes white when I create a 'Text' item. I try to reload, sign out and sign in with another role but screen is white and can 't do anything on Core Mapping


https://github.com/serge-web/serge/assets/107697044/45a3155f-d369-4a44-a921-cbfe70307b44

This is error from console : 

image

**Comment by IanMayo** [comment]
> @IanMayo Checking on '2842-shape-umpire-color' branch, screen becomes white when I create a 'Text' item. I try to reload, sign out and sign in with another role but screen is white and can 't do anything on Core Mapping
> 
Hello Tristina - yes, I think I also had that issue [this morning](https://github.com/serge-web/serge/pull/2852#issuecomment-1955967171).

**Comment by lebaphi** [comment]
Hi @IanMayo , @Tristina1788 , okay I will take a look in this issue.

```
How about another strategy?

Find out if the background color is dark using [this](https://github.com/bgrins/TinyColor#isdark) library
If it is dark, make the text white
```
I think it good in case the text's color does not changes, it's always black and we do not plan to provide an ability to change text color in the future. If yes there are some cases that we need to deal:
- force umpire and text's color is black
- force f-red and text's color is red
- force f-blue and text's color is blue
- force f-green and  text's color is green

**Comment by Tristina1788** [comment]
@lebaphi Try to build with current code on '2842-shape-umpire-color' branch but get error.

image

**Comment by lebaphi** [comment]
I'm working on it, just pushed the fixes @IanMayo @Tristina1788 

image

**Comment by IanMayo** [comment]
You'll need to remove one of the lock files, please @lebaphi 
image

**Comment by Tristina1788** [comment]
@lebaphi , @IanMayo Sorry for response late on this. I don't notice we have change on this.
- Checking on this branch, now the new shape and text has correct Force color. But should we change blue color to dark blue. I mean the current blue is hard to see on map.

image

**Comment by IanMayo** [comment]
> Checking on this branch, now the new shape and text has correct Force color. But should we change blue color to dark blue. I mean the current blue is hard to see on map.

Good point @Tristina1788 .   I _think_ we have to use the shade of blue that the Game Designer specified.  But, could we make it less transparent please @lebaphi ?

**Comment by Tristina1788** [comment]
@lebaphi , @IanMayo  Now the color of shape get from force color, and the color green/blue is better to see in gameplay. => It works as expected

image

But from Storybook, although the shape with 'Force' color Red, but it shows pink color

image

**Comment by Tristina1788** [comment]
@IanMayo The red color in Story board is bolder than gameplay. Is this ok?

image

**Comment by IanMayo** [comment]
> @IanMayo The red color in Story board is bolder than gameplay. Is this ok?
> 
Yes - I manually created some colors for the story, so they could be different.

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
