### PR TITLE
2979 collab channel phases

### PR DESCRIPTION
**Pull request by IanMayo**
Supports #2979

### CODE REVIEW

**Comment by IanMayo** [comment]
Hello @Tristina1788 - this PR won't be ready for review until the admin pages have been updated. Then, you should be able to check Serge matches the behaviour specified in the issue.

**Comment by IanMayo** [comment]
It looks good to me, I look forward to @Tristina1788 verifying that when phases are specified, they are reflected in which controls are offered to players in which phases.

**Comment by Tristina1788** [comment]
@IanMayo  @lebaphi The header should be left of column (as 'Force' header).

image


image

- User still can't interact message  when user have permission on specific phase. The user only can interract message when has permission for 'All Phase' => User should have permission on any define phase.

Ex : setting collab Channel with user Blue - 3rd Party have permission on 'Planning' phase. But playing game with this user, no action this user can do for message : https://app.screencast.com/fYQ8u101YL6lU

**Comment by Tristina1788** [comment]
@IanMayo @lebaphi 

- Now the header shows as expected

image

- 'User still can interact message when user have permission on specific phase as expected.

Everything is fine now. I think we can close it.

**Pull request merged**
