### PR TITLE
1199 alternative table

### PR DESCRIPTION
**Pull request by IanMayo**
Supports #1199

Trial use of another table control

### CODE REVIEW

**Comment by IanMayo** [comment]
Hello @philb89  - I've created a PR for your branch, to capture some feedback.

* [x] For an empty table, could it still display the headers please?  It helps the players to understand what they are going to see
* [x] Could you remove the pagination controls please? We just want one long list of items - so that <ctrl-f> covers the whole table
* [x] The table doesn't (currently) update when new data is received, or when a new message is sent.  A page refresh does show the new content.
* [x] I can expand a message ,but when I try to collapse it again, and [error](https://i.gyazo.com/725f15c3dfb43b223fa346757c005de5.png) is thrown

**Comment by lebaphi** [comment]
> Hello @philb89 - I've created a PR for your branch, to capture some feedback.
> 
> * [ ]  For an empty table, could it still display the headers please?  It helps the players to understand what they are going to see
> * [ ]  Could you remove the pagination controls please? We just want one long list of items - so that  covers the whole table
> * [ ]  The table doesn't (currently) update when new data is received, or when a new message is sent.  A page refresh does show the new content.
> * [ ]  I can expand a message ,but when I try to collapse it again, and [error](https://i.gyazo.com/725f15c3dfb43b223fa346757c005de5.png) is thrown

Yep @IanMayo , I saw all of these error and Im working on it. No worries :D

**Comment by IanMayo** [comment]
Looking good so far @philb89  :-)

**Comment by IanMayo** [comment]
Thanks for the steady progress @lebaphi 

We still need to be able to filter by status, from and owner. We currently just sort by it.

We also need to display the `Location` fields.

**Comment by lebaphi** [comment]
> Thanks for the steady progress @lebaphi
> 
> We still need to be able to filter by status, from and owner. We currently just sort by it.
> 
> We also need to display the `Location` fields.

okay @IanMayo

**Pull request merged**
