### PR TITLE
1618: Attribute Features out of Alignment 

### LINKED ISSUE #1618: Attribute Features out of Alignment
In the downloadable version, the features of the attribute box seem to have left alignment with their respective text boxes/toggles:

Attribute out of alignment

It'd be nice if we could realign them.

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1618 

Screen Shot 2022-07-05 at 10 45 34 AM

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks @lebaphi - but the layout doesn't work as the window gets wider.
gif

I'm probably being old fashioned, but I _guess_ it all needs to be in table.

**Comment by lebaphi** [comment]
> Thanks @lebaphi - but the layout doesn't work as the window gets wider. gif [ ](https://camo.githubusercontent.com/4debdd376ca653abaf0d7b310f9d41439085cb909f9341b48d920055c875d18e/68747470733a2f2f692e6779617a6f2e636f6d2f39663638623332306165323834666262393438663766646165343436383034622e676966) gif [ ](https://camo.githubusercontent.com/4debdd376ca653abaf0d7b310f9d41439085cb909f9341b48d920055c875d18e/68747470733a2f2f692e6779617a6f2e636f6d2f39663638623332306165323834666262393438663766646165343436383034622e676966)
> 
> I'm probably being old fashioned, but I _guess_ it all needs to be in table.

Yes, if it be in the table, everything goes well. The issue is the way we implement this component: content (reuse SortableList) and the header in separate places:

image

So there is 2 solutions for this:
- Refactor this component using table (style might inconsistent with others)
- Keep using SortableList and try to sync position of the icon header by CSS

I decided to go with 2), let me play more with this :D

**Comment by IanMayo** [comment]
> I decided to go with 2), let me play more with this :D

Sure, ok.

In the longer term, I'm happy for us to switch to an off-the-shelf component.

**Comment by IanMayo** [comment]
Thanks @lebaphi 

I'll check the fix once the deployment is ready.  But, the workaround does seem a little _fragile_.  I look forward to finding an off-the-shelf data table component.

**Comment by lebaphi** [comment]
okay, I will try with table now 😄

**Comment by IanMayo** [comment]
> okay, I will try with table now 😄

No, don't worry @lebaphi .  I don't want to invest effort in the workaround if we're going to (eventually) move to an off-the-shelf component.

**Review by IanMayo — APPROVED** [review]
The workaround works, thanks :-)

**Pull request merged**
