### PR TITLE
1748: Create Orders Component

### LINKED ISSUE #1748: C. Create orders component
Use table component to display list of messages.  A _placeholder_ for this has been created as `Planning-Messages-List`.

Suggest this component: https://github.com/mbrn/material-table

Props (all from state):
* channel id (to be used when sending new message)
* messages for this channel (duh)
* player role (to be used when sending new message)
* player force (to filter messages)
* isUmpire (if true, include drop-down at top of channel to choose `view-as` force)
* templates for this wargame (used to render message _detail_, and for creating new messages).

Component will run "map" on messages to produced reduced array suitable for rendering.  The reduce function will extract the fields displayed below.

Display one row per message, initially (*) with these headers:
* id
* title
* from-role
* status
* start date
* finish date

(*) Users to provide exact fields in early Sept.

Page should have `sort` on id, title, start-date, finish-date. Page should have `filter` on `status`.

It should be possible for players to expand messages, to read the detail (presented using the JSON-Editor with the relevant template - like how we did for `COA Status Board`).

Have mocked up how a player may view their orders here:
image

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1748

### CODE REVIEW

**Comment by IanMayo** [comment]
would love to see a screenshot, please.

**Comment by lebaphi** [comment]
Hi @IanMayo , I just added some dummy data to test this component

image

**Comment by IanMayo** [comment]
dummy data: perfect 😊

**Comment by IanMayo** [comment]
Thanks for that @lebaphi .  The mock data isn't in the branch, is it?  (I can't see it)

The `storybook` could use the `p9.mock.ts` dataset to get a list of messages to display.  (will work on better sample data when I'm back next week).

**Comment by IanMayo** [comment]
@lebaphi - I don't think I'll be properly able to review this until I'm back in the office on Monday (or even Tuesday, since Monday is an official holiday).

But. it would be great if you could get started on #1749 . We're using the same table control,  but with expanding `parent-child` triangle when one `asset` _comprises_ several others.

**Comment by lebaphi** [comment]
> Thanks for that @lebaphi .  The mock data isn't in the branch, is it?  (I can't see it)
> 
> 
> 
> The `storybook` could use the `p9.mock.ts` dataset to get a list of messages to display.  (will work on better sample data when I'm back next week).

yep I don't push the function to generate the mock data, I just show you how the messages are display in this table

**Comment by lebaphi** [comment]
> @lebaphi - I don't think I'll be properly able to review this until I'm back in the office on Monday (or even Tuesday, since Monday is an official holiday).
> 
> 
> 
> But. it would be great if you could get started on #1749 . We're using the same table control,  but with expanding `parent-child` triangle when one `asset` _comprises_ several others.

sure @IanMayo, Im working on it

**Comment by IanMayo** [comment]
Hello @lebaphi - I've added some sample data to the story.

As the next step, I'd like you to implement the "Expand" functionality, please. So, when the player clicks on a message, it will expand to show the detail of the `message.message` using a disabled `json-editor`, like we did for `CollabStatusBoard`.

I would also like to have drop-down filter menus on the `Role` and `Status` columns.  like the `Birth-place` column here: https://material-table.com/#/docs/features/filtering

**Comment by lebaphi** [comment]
okay @IanMayo

**Comment by IanMayo** [comment]
Hello @lebaphi,
the `PlanningMessagesList` and `Orders` components both seem quite _thin_.   Is it possible to pull the `Orders` functionality back up into `PlanningMessagesList`?

Hmm. I'm happy to work on the "drop-down" filters, but I'll wait until we've done the above refactoring.

**Comment by IanMayo** [comment]
Hello @lebaphi - I've had a "big push" with this today.  

We'll use the `<NewMessage/>` control to create new messages in the "My Orders" panel, but I need to get that refactored into the `components` package from the `client` package before we can do that.  I've created an issue for @lilitkarapetyan to work on that, #1787 

But, we can still try to sort out the `detail` view, that shows existing messages in the `JsonEditor` control - just like with `CollabStatusBoard`. [Here is](https://serge-1748-order-compon-x7qdto.herokuapp.com/storybook/?path=/story/local-collabstatusboard--collaborative-edit-release-manager) a playable link.

The code to do that is in `CollabMessageDetail`.

**Comment by lebaphi** [comment]
Hi @IanMayo, I will be back in 2moro, I got sick for a few days ago, maybe i have covid even though i got 4 doses of vaccine. No worries

**Comment by lebaphi** [comment]
Hi @IanMayo , it seems that the latest change in 'develop' breaks the UI of the support panel component

image

**Comment by IanMayo** [comment]
Oops, I bet it was me.  I've done lots of changes.

These two planning PRs are getting large. I'm going to try to merge/resolve them tomorrow morning (if not today). 

It would be great if you could still investigate the `detail` view of orders, please.

**Comment by lebaphi** [comment]
I resolved it already:D

**Comment by IanMayo** [comment]
@lebaphi - I'm going to merge this, so at least `SupportPanel` can be stable. Then we can work on smaller PRs that don't bring conflicts.

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
