### PR TITLE
Adjudicate_Tab_not_getting_updates

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks @lilitkarapetyan  - but this isn't quite right.

While the panel knows about `planningMessages` - it's the `adjudicationMessages` that it displays - and it's these messages that we have to track.  So, I'm pretty sure we don't need to worry about `planningMessage` updates.  It's the `interactionMessages` that we need to handle carefully.

**Comment by IanMayo** [comment]
@lilitkarapetyan - I've attempted an update.

Could you check it please?

Steps to test:
- login as Game Control and Adjudicator 1
- as Game Control, move game to `Adjudication` (if necessary)
- as Game Control, click on `Get Next Interaction` - when the form loads, start to type some data into a field
- as Adjudicator 1, click on `Get Next Interaction`, write some data into the form and `Submit`.
- check the content of the Game Control form isn't lost.

**Comment by lilitkarapetyan** [comment]
Okay now.

>

**Review by IanMayo — APPROVED** [review]
Tested. Working fine.

**Pull request merged**
