### PR TITLE
1389: Fix PLayerLog marker styles

### LINKED ISSUE #1389: Reactive Online Marker
The online/offline marker is reactive to the text box next to it. It squeezes or expands depending on if the text box says "a few seconds ago" or "X minutes ago".

A Few Seconds Ago Bug

A Minute Ago Bug

Could we make the text box a two-liner so it doesn't impact the marker?

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1389 

For this issue, I updated:
- increate player log modal width to 50px 
- add min width css property for the marker
- in case the text content of the cell is too long, the scroll x auto appear to view all the text if need.

https://user-images.githubusercontent.com/26705621/158003059-1b6691cf-9a27-4fc1-b323-4069f3672f76.mov

### CODE REVIEW

**Comment by ShendMikullovci** [comment]
This is how it looks once last active time hits double digits:

Last Active Spacing

I think in a game with plenty of players this would end up cluttering the log. Could we maybe reduce a little bit of the "Role" tab size? Even in games with long role names, like Papafoxtrot, there seems to be just a little space we could sacrifice for the "Role" tab to add to the Last Active: 

Papafoxtrot Player Log

**Comment by IanMayo** [comment]
> This is how it looks once last active time hits double digits:

Yes @lebaphi - I think the next steps is to start providing different column widths, please.

**Comment by lebaphi** [comment]
> > This is how it looks once last active time hits double digits:
> 
> 
> 
> Yes @lebaphi - I think the next steps is to start providing different column widths, please.

sure, it sounds interesting 👍🏻

**Comment by lebaphi** [comment]
https://user-images.githubusercontent.com/26705621/160058367-3b1a20bc-5854-40db-95da-ca239f257481.mov

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
